-- recovery_items_sylvanas.lua -- TBC food/drink ITEM ids, for classifying what is
-- already in the player's bags when the pull gate has parked the bot to recover.
-- WHAT:  { [item_id] = { name = "Item Name", kind = "food"|"drink", min_level = N } }.
-- WHEN:  read by shared/recovery.lua; generated, never hand-edited -- see
--        EaxAutoQuester/tools/generate_recovery_items.py (run with --check for drift).
-- SOURCE: PublicGithubs/tbc/assets/item_data/all_item_tooltips.csv -- tbc.wowhead.com
--         tooltip answers, one JSON object per row.
-- RULE:  a Use: line restoring health or mana over a duration AND "Must remain seated".
--        Excluded: cut content (deprecated/test/[DNT]), cooking recipe PAGES and mage
--        conjure TOMES (their tooltips quote the dish's or water's restore line).
--        Conjured food and water are INCLUDED: what is in the bags is usable, and a
--        mage's own conjured water is exactly what a recovery pause should drink.
-- SAFETY: data only -- no requires, no calls, no state. An id here can only ever be
--         matched against an item ALREADY in the bags, so a stale entry is inert.
-- COUNT: 335 ids as of 2026-09-23.

return {
    [117] = { name = "Tough Jerky", kind = "food", min_level = 1 },
    [159] = { name = "Refreshing Spring Water", kind = "drink", min_level = 1 },
    [414] = { name = "Dalaran Sharp", kind = "food", min_level = 5 },
    [422] = { name = "Dwarven Mild", kind = "food", min_level = 15 },
    [724] = { name = "Goretusk Liver Pie", kind = "food", min_level = 5 },
    [733] = { name = "Westfall Stew", kind = "food", min_level = 5 },
    [787] = { name = "Slitherskin Mackerel", kind = "food", min_level = 1 },
    [961] = { name = "Healing Herb", kind = "food", min_level = 1 },
    [1017] = { name = "Seasoned Wolf Kabob", kind = "food", min_level = 15 },
    [1082] = { name = "Redridge Goulash", kind = "food", min_level = 10 },
    [1113] = { name = "Conjured Bread", kind = "food", min_level = 5 },
    [1114] = { name = "Conjured Rye", kind = "food", min_level = 15 },
    [1119] = { name = "Bottled Spirits", kind = "food", min_level = 1 },
    [1179] = { name = "Ice Cold Milk", kind = "drink", min_level = 5 },
    [1205] = { name = "Melon Juice", kind = "drink", min_level = 15 },
    [1326] = { name = "Sauteed Sunfish", kind = "food", min_level = 1 },
    [1401] = { name = "Green Tea Leaf", kind = "drink", min_level = 4 },
    [1487] = { name = "Conjured Pumpernickel", kind = "food", min_level = 25 },
    [1645] = { name = "Moonberry Juice", kind = "drink", min_level = 35 },
    [1707] = { name = "Stormwind Brie", kind = "food", min_level = 25 },
    [1708] = { name = "Sweet Nectar", kind = "drink", min_level = 25 },
    [2070] = { name = "Darnassian Bleu", kind = "food", min_level = 1 },
    [2136] = { name = "Conjured Purified Water", kind = "drink", min_level = 15 },
    [2287] = { name = "Haunch of Meat", kind = "food", min_level = 5 },
    [2288] = { name = "Conjured Fresh Water", kind = "drink", min_level = 5 },
    [2679] = { name = "Charred Wolf Meat", kind = "food", min_level = 1 },
    [2680] = { name = "Spiced Wolf Meat", kind = "food", min_level = 1 },
    [2681] = { name = "Roasted Boar Meat", kind = "food", min_level = 1 },
    [2683] = { name = "Crab Cake", kind = "food", min_level = 5 },
    [2684] = { name = "Coyote Steak", kind = "food", min_level = 5 },
    [2685] = { name = "Succulent Pork Ribs", kind = "food", min_level = 10 },
    [2687] = { name = "Dry Pork Ribs", kind = "food", min_level = 5 },
    [2888] = { name = "Beer Basted Boar Ribs", kind = "food", min_level = 1 },
    [3220] = { name = "Blood Sausage", kind = "food", min_level = 5 },
    [3662] = { name = "Crocolisk Steak", kind = "food", min_level = 5 },
    [3663] = { name = "Murloc Fin Soup", kind = "food", min_level = 15 },
    [3664] = { name = "Crocolisk Gumbo", kind = "food", min_level = 15 },
    [3665] = { name = "Curiously Tasty Omelet", kind = "food", min_level = 15 },
    [3666] = { name = "Gooey Spider Cake", kind = "food", min_level = 15 },
    [3726] = { name = "Big Bear Steak", kind = "food", min_level = 15 },
    [3727] = { name = "Hot Lion Chops", kind = "food", min_level = 15 },
    [3728] = { name = "Tasty Lion Steak", kind = "food", min_level = 20 },
    [3729] = { name = "Soothing Turtle Bisque", kind = "food", min_level = 25 },
    [3770] = { name = "Mutton Chop", kind = "food", min_level = 15 },
    [3771] = { name = "Wild Hog Shank", kind = "food", min_level = 25 },
    [3772] = { name = "Conjured Spring Water", kind = "drink", min_level = 25 },
    [3927] = { name = "Fine Aged Cheddar", kind = "food", min_level = 35 },
    [4457] = { name = "Barbecued Buzzard Wing", kind = "food", min_level = 25 },
    [4536] = { name = "Shiny Red Apple", kind = "food", min_level = 1 },
    [4537] = { name = "Tel'Abim Banana", kind = "food", min_level = 5 },
    [4538] = { name = "Snapvine Watermelon", kind = "food", min_level = 15 },
    [4539] = { name = "Goldenbark Apple", kind = "food", min_level = 25 },
    [4540] = { name = "Tough Hunk of Bread", kind = "food", min_level = 1 },
    [4541] = { name = "Freshly Baked Bread", kind = "food", min_level = 5 },
    [4542] = { name = "Moist Cornbread", kind = "food", min_level = 15 },
    [4544] = { name = "Mulgore Spice Bread", kind = "food", min_level = 25 },
    [4592] = { name = "Longjaw Mud Snapper", kind = "food", min_level = 5 },
    [4593] = { name = "Bristle Whisker Catfish", kind = "food", min_level = 15 },
    [4594] = { name = "Rockscale Cod", kind = "food", min_level = 25 },
    [4599] = { name = "Cured Ham Steak", kind = "food", min_level = 35 },
    [4601] = { name = "Soft Banana Bread", kind = "food", min_level = 35 },
    [4602] = { name = "Moon Harvest Pumpkin", kind = "food", min_level = 35 },
    [4603] = { name = "Raw Spotted Yellowtail", kind = "food", min_level = 35 },
    [4604] = { name = "Forest Mushroom Cap", kind = "food", min_level = 1 },
    [4605] = { name = "Red-speckled Mushroom", kind = "food", min_level = 5 },
    [4606] = { name = "Spongy Morel", kind = "food", min_level = 15 },
    [4607] = { name = "Delicious Cave Mold", kind = "food", min_level = 25 },
    [4608] = { name = "Raw Black Truffle", kind = "food", min_level = 35 },
    [4656] = { name = "Small Pumpkin", kind = "food", min_level = 1 },
    [4696] = { name = "Lapidis Tankard of Tidesippe", kind = "drink", min_level = 54 },
    [4791] = { name = "Enchanted Water", kind = "drink", min_level = 25 },
    [5057] = { name = "Ripe Watermelon", kind = "food", min_level = 1 },
    [5066] = { name = "Fissure Plant", kind = "food", min_level = 5 },
    [5095] = { name = "Rainbow Fin Albacore", kind = "food", min_level = 5 },
    [5349] = { name = "Conjured Muffin", kind = "food", min_level = 1 },
    [5350] = { name = "Conjured Water", kind = "drink", min_level = 1 },
    [5472] = { name = "Kaldorei Spider Kabob", kind = "food", min_level = 1 },
    [5474] = { name = "Roasted Kodo Meat", kind = "food", min_level = 1 },
    [5476] = { name = "Fillet of Frenzy", kind = "food", min_level = 5 },
    [5477] = { name = "Strider Stew", kind = "food", min_level = 5 },
    [5478] = { name = "Dig Rat Stew", kind = "food", min_level = 10 },
    [5479] = { name = "Crispy Lizard Tail", kind = "food", min_level = 12 },
    [5480] = { name = "Lean Venison", kind = "food", min_level = 15 },
    [5525] = { name = "Boiled Clams", kind = "food", min_level = 5 },
    [5526] = { name = "Clam Chowder", kind = "food", min_level = 10 },
    [5527] = { name = "Goblin Deviled Clams", kind = "food", min_level = 15 },
    [5845] = { name = "Flank of Meat", kind = "food", min_level = 15 },
    [6038] = { name = "Giant Clam Scorcho", kind = "food", min_level = 25 },
    [6289] = { name = "Raw Longjaw Mud Snapper", kind = "food", min_level = 5 },
    [6290] = { name = "Brilliant Smallfish", kind = "food", min_level = 1 },
    [6291] = { name = "Raw Brilliant Smallfish", kind = "food", min_level = 1 },
    [6299] = { name = "Sickly Looking Fish", kind = "food", min_level = 1 },
    [6303] = { name = "Raw Slitherskin Mackerel", kind = "food", min_level = 1 },
    [6308] = { name = "Raw Bristle Whisker Catfish", kind = "food", min_level = 15 },
    [6316] = { name = "Loch Frenzy Delight", kind = "food", min_level = 5 },
    [6317] = { name = "Raw Loch Frenzy", kind = "food", min_level = 5 },
    [6361] = { name = "Raw Rainbow Fin Albacore", kind = "food", min_level = 5 },
    [6362] = { name = "Raw Rockscale Cod", kind = "food", min_level = 25 },
    [6458] = { name = "Oil Covered Fish", kind = "food", min_level = 5 },
    [6807] = { name = "Frog Leg Stew", kind = "food", min_level = 1 },
    [6887] = { name = "Spotted Yellowtail", kind = "food", min_level = 35 },
    [6888] = { name = "Herb Baked Egg", kind = "food", min_level = 1 },
    [6890] = { name = "Smoked Bear Meat", kind = "food", min_level = 5 },
    [7097] = { name = "Leg Meat", kind = "food", min_level = 1 },
    [7228] = { name = "Tigule's Strawberry Ice Cream", kind = "food", min_level = 15 },
    [7806] = { name = "Lollipop", kind = "food", min_level = 1 },
    [7807] = { name = "Candy Bar", kind = "food", min_level = 1 },
    [7808] = { name = "Chocolate Square", kind = "food", min_level = 1 },
    [8075] = { name = "Conjured Sourdough", kind = "food", min_level = 35 },
    [8076] = { name = "Conjured Sweet Roll", kind = "food", min_level = 45 },
    [8077] = { name = "Conjured Mineral Water", kind = "drink", min_level = 35 },
    [8078] = { name = "Conjured Sparkling Water", kind = "drink", min_level = 45 },
    [8079] = { name = "Conjured Crystal Water", kind = "drink", min_level = 55 },
    [8364] = { name = "Mithril Head Trout", kind = "food", min_level = 25 },
    [8365] = { name = "Raw Mithril Head Trout", kind = "food", min_level = 25 },
    [8543] = { name = "Underwater Mushroom Cap", kind = "food", min_level = 25 },
    [8683] = { name = "Clara's Fresh Apple", kind = "food", min_level = 1 },
    [8766] = { name = "Morning Glory Dew", kind = "drink", min_level = 45 },
    [8932] = { name = "Alterac Swiss", kind = "food", min_level = 45 },
    [8948] = { name = "Dried King Bolete", kind = "food", min_level = 45 },
    [8950] = { name = "Homemade Cherry Pie", kind = "food", min_level = 45 },
    [8952] = { name = "Roasted Quail", kind = "food", min_level = 45 },
    [8953] = { name = "Deep Fried Plantains", kind = "food", min_level = 45 },
    [8957] = { name = "Spinefin Halibut", kind = "food", min_level = 45 },
    [8959] = { name = "Raw Spinefin Halibut", kind = "food", min_level = 45 },
    [9451] = { name = "Bubbling Water", kind = "drink", min_level = 15 },
    [9681] = { name = "Grilled King Crawler Legs", kind = "food", min_level = 35 },
    [10841] = { name = "Goldthorn Tea", kind = "drink", min_level = 25 },
    [11109] = { name = "Special Chicken Feed", kind = "food", min_level = 1 },
    [11415] = { name = "Mixed Berries", kind = "food", min_level = 45 },
    [11444] = { name = "Grim Guzzler Boar", kind = "food", min_level = 45 },
    [11584] = { name = "Cactus Apple Surprise", kind = "food", min_level = 1 },
    [11950] = { name = "Windblossom Berries", kind = "food", min_level = 45 },
    [12209] = { name = "Lean Wolf Steak", kind = "food", min_level = 15 },
    [12210] = { name = "Roast Raptor", kind = "food", min_level = 25 },
    [12211] = { name = "Spiced Wolf Ribs", kind = "food", min_level = 25 },
    [12212] = { name = "Jungle Stew", kind = "food", min_level = 25 },
    [12213] = { name = "Carrion Surprise", kind = "food", min_level = 25 },
    [12214] = { name = "Mystery Stew", kind = "food", min_level = 25 },
    [12215] = { name = "Heavy Kodo Stew", kind = "food", min_level = 35 },
    [12216] = { name = "Spiced Chili Crab", kind = "food", min_level = 40 },
    [12218] = { name = "Monster Omelet", kind = "food", min_level = 40 },
    [12224] = { name = "Crispy Bat Wing", kind = "food", min_level = 1 },
    [12238] = { name = "Darkshore Grouper", kind = "food", min_level = 5 },
    [12763] = { name = "Un'Goro Etherfruit", kind = "food", min_level = 45 },
    [13546] = { name = "Bloodbelly Fish", kind = "food", min_level = 25 },
    [13754] = { name = "Raw Glossy Mightfish", kind = "food", min_level = 35 },
    [13755] = { name = "Winter Squid", kind = "food", min_level = 35 },
    [13756] = { name = "Raw Summer Bass", kind = "food", min_level = 35 },
    [13758] = { name = "Raw Redgill", kind = "food", min_level = 35 },
    [13759] = { name = "Raw Nightfin Snapper", kind = "food", min_level = 35 },
    [13760] = { name = "Raw Sunscale Salmon", kind = "food", min_level = 35 },
    [13810] = { name = "Blessed Sunfruit", kind = "food", min_level = 45 },
    [13813] = { name = "Blessed Sunfruit Juice", kind = "drink", min_level = 45 },
    [13851] = { name = "Hot Wolf Ribs", kind = "food", min_level = 25 },
    [13888] = { name = "Darkclaw Lobster", kind = "food", min_level = 45 },
    [13889] = { name = "Raw Whitescale Salmon", kind = "food", min_level = 45 },
    [13893] = { name = "Large Raw Mightfish", kind = "food", min_level = 45 },
    [13927] = { name = "Cooked Glossy Mightfish", kind = "food", min_level = 35 },
    [13928] = { name = "Grilled Squid", kind = "food", min_level = 35 },
    [13929] = { name = "Hot Smoked Bass", kind = "food", min_level = 35 },
    [13930] = { name = "Filet of Redgill", kind = "food", min_level = 35 },
    [13931] = { name = "Nightfin Soup", kind = "food", min_level = 35 },
    [13932] = { name = "Poached Sunscale Salmon", kind = "food", min_level = 35 },
    [13933] = { name = "Lobster Stew", kind = "food", min_level = 45 },
    [13934] = { name = "Mightfish Steak", kind = "food", min_level = 45 },
    [13935] = { name = "Baked Salmon", kind = "food", min_level = 45 },
    [16166] = { name = "Bean Soup", kind = "food", min_level = 1 },
    [16167] = { name = "Versicolor Treat", kind = "food", min_level = 5 },
    [16168] = { name = "Heaven Peach", kind = "food", min_level = 35 },
    [16169] = { name = "Wild Ricecake", kind = "food", min_level = 25 },
    [16170] = { name = "Steamed Mandu", kind = "food", min_level = 15 },
    [16171] = { name = "Shinsollo", kind = "food", min_level = 45 },
    [16766] = { name = "Undermine Clam Chowder", kind = "food", min_level = 35 },
    [16971] = { name = "Clamlette Surprise", kind = "food", min_level = 40 },
    [17119] = { name = "Deeprun Rat Kabob", kind = "food", min_level = 5 },
    [17197] = { name = "Gingerbread Cookie", kind = "food", min_level = 1 },
    [17198] = { name = "Egg Nog", kind = "food", min_level = 1 },
    [17199] = { name = "Bad Egg Nog", kind = "food", min_level = 1 },
    [17222] = { name = "Spider Sausage", kind = "food", min_level = 35 },
    [17344] = { name = "Candy Cane", kind = "food", min_level = 1 },
    [17404] = { name = "Blended Bean Brew", kind = "drink", min_level = 5 },
    [17405] = { name = "Green Garden Tea", kind = "drink", min_level = 25 },
    [17406] = { name = "Holiday Cheesewheel", kind = "food", min_level = 5 },
    [17407] = { name = "Graccu's Homemade Meat Pie", kind = "food", min_level = 25 },
    [17408] = { name = "Spicy Beefstick", kind = "food", min_level = 35 },
    [18045] = { name = "Tender Wolf Steak", kind = "food", min_level = 40 },
    [18254] = { name = "Runn Tum Tuber Surprise", kind = "food", min_level = 45 },
    [18255] = { name = "Runn Tum Tuber", kind = "food", min_level = 45 },
    [18300] = { name = "Hyjal Nectar", kind = "drink", min_level = 55 },
    [18632] = { name = "Moonbrook Riot Taffy", kind = "food", min_level = 25 },
    [18633] = { name = "Styleen's Sour Suckerpop", kind = "food", min_level = 5 },
    [18635] = { name = "Bellara's Nutterbar", kind = "food", min_level = 35 },
    [19223] = { name = "Darkmoon Dog", kind = "food", min_level = 1 },
    [19224] = { name = "Red Hot Wings", kind = "food", min_level = 25 },
    [19225] = { name = "Deep Fried Candybar", kind = "food", min_level = 45 },
    [19299] = { name = "Fizzy Faire Drink", kind = "drink", min_level = 15 },
    [19300] = { name = "Bottled Winterspring Water", kind = "drink", min_level = 35 },
    [19304] = { name = "Spiced Beef Jerky", kind = "food", min_level = 5 },
    [19305] = { name = "Pickled Kodo Foot", kind = "food", min_level = 15 },
    [19306] = { name = "Crunchy Frog", kind = "food", min_level = 35 },
    [19318] = { name = "Bottled Alterac Spring Water", kind = "drink", min_level = 55 },
    [20074] = { name = "Heavy Crocolisk Stew", kind = "food", min_level = 20 },
    [20452] = { name = "Smoked Desert Dumplings", kind = "food", min_level = 45 },
    [20857] = { name = "Honey Bread", kind = "food", min_level = 1 },
    [21023] = { name = "Dirge's Kickin' Chimaerok Chops", kind = "food", min_level = 55 },
    [21030] = { name = "Darnassus Kimchi Pie", kind = "food", min_level = 35 },
    [21031] = { name = "Cabbage Kimchi", kind = "food", min_level = 45 },
    [21033] = { name = "Radish Kimchi", kind = "food", min_level = 45 },
    [21552] = { name = "Striped Yellowtail", kind = "food", min_level = 35 },
    [22018] = { name = "Conjured Glacier Water", kind = "drink", min_level = 65 },
    [22019] = { name = "Conjured Croissant", kind = "food", min_level = 65 },
    [22324] = { name = "Winter Kimchi", kind = "food", min_level = 45 },
    [22645] = { name = "Crunchy Spider Surprise", kind = "food", min_level = 5 },
    [22895] = { name = "Conjured Cinnamon Roll", kind = "food", min_level = 55 },
    [23160] = { name = "Friendship Bread", kind = "food", min_level = 45 },
    [23161] = { name = "Freshly-Squeezed Lemonade", kind = "drink", min_level = 45 },
    [23495] = { name = "Springpaw Appetizer", kind = "food", min_level = 1 },
    [23585] = { name = "Stouthammer Lite", kind = "drink", min_level = 1 },
    [23756] = { name = "Cookie's Jumbo Gumbo", kind = "food", min_level = 1 },
    [24006] = { name = "Grunt's Waterskin", kind = "drink", min_level = 45 },
    [24007] = { name = "Footman's Waterskin", kind = "drink", min_level = 55 },
    [24008] = { name = "Dried Mushroom Rations", kind = "food", min_level = 55 },
    [24009] = { name = "Dried Fruit Rations", kind = "food", min_level = 55 },
    [24072] = { name = "Sand Pear Pie", kind = "food", min_level = 5 },
    [24105] = { name = "Roasted Moongraze Tenderloin", kind = "food", min_level = 1 },
    [24338] = { name = "Hellfire Spineleaf", kind = "food", min_level = 55 },
    [24408] = { name = "Edible Stalks", kind = "food", min_level = 1 },
    [24539] = { name = "Marsh Lichen", kind = "food", min_level = 55 },
    [24540] = { name = "Edible Fern", kind = "food", min_level = 1 },
    [27635] = { name = "Lynx Steak", kind = "food", min_level = 1 },
    [27636] = { name = "Bat Bites", kind = "food", min_level = 5 },
    [27651] = { name = "Buzzard Bites", kind = "food", min_level = 55 },
    [27655] = { name = "Ravager Dog", kind = "food", min_level = 55 },
    [27657] = { name = "Blackened Basilisk", kind = "food", min_level = 55 },
    [27658] = { name = "Roasted Clefthoof", kind = "food", min_level = 55 },
    [27659] = { name = "Warp Burger", kind = "food", min_level = 55 },
    [27660] = { name = "Talbuk Steak", kind = "food", min_level = 55 },
    [27661] = { name = "Blackened Trout", kind = "food", min_level = 55 },
    [27662] = { name = "Feltail Delight", kind = "food", min_level = 55 },
    [27663] = { name = "Blackened Sporefish", kind = "food", min_level = 55 },
    [27664] = { name = "Grilled Mudfish", kind = "food", min_level = 55 },
    [27665] = { name = "Poached Bluefish", kind = "food", min_level = 55 },
    [27666] = { name = "Golden Fish Sticks", kind = "food", min_level = 55 },
    [27667] = { name = "Spicy Crawdad", kind = "food", min_level = 55 },
    [27854] = { name = "Smoked Talbuk Venison", kind = "food", min_level = 55 },
    [27855] = { name = "Mag'har Grainbread", kind = "food", min_level = 55 },
    [27856] = { name = "Skethyl Berries", kind = "food", min_level = 55 },
    [27857] = { name = "Garadar Sharp", kind = "food", min_level = 55 },
    [27858] = { name = "Sunspring Carp", kind = "food", min_level = 55 },
    [27859] = { name = "Zangar Caps", kind = "food", min_level = 55 },
    [27860] = { name = "Purified Draenic Water", kind = "drink", min_level = 65 },
    [28399] = { name = "Filtered Draenic Water", kind = "drink", min_level = 60 },
    [28486] = { name = "Moser's Magnificent Muffin", kind = "food", min_level = 55 },
    [28501] = { name = "Ravager Egg Omelet", kind = "food", min_level = 55 },
    [29292] = { name = "Helboar Bacon", kind = "food", min_level = 55 },
    [29293] = { name = "Bonestripper Buzzard Hotwings", kind = "food", min_level = 55 },
    [29393] = { name = "Diamond Berries", kind = "food", min_level = 55 },
    [29394] = { name = "Lyribread", kind = "food", min_level = 65 },
    [29395] = { name = "Ethermead", kind = "drink", min_level = 65 },
    [29401] = { name = "Sparkling Southshore Cider", kind = "drink", min_level = 65 },
    [29402] = { name = "Jessen's Special Slop OLD", kind = "food", min_level = 50 },
    [29412] = { name = "Jessen's Special Slop", kind = "food", min_level = 55 },
    [29448] = { name = "Mag'har Mild Cheese", kind = "food", min_level = 65 },
    [29449] = { name = "Bladespire Bagel", kind = "food", min_level = 65 },
    [29450] = { name = "Telaari Grapes", kind = "food", min_level = 65 },
    [29451] = { name = "Clefthoof Ribs", kind = "food", min_level = 65 },
    [29452] = { name = "Zangar Trout", kind = "food", min_level = 65 },
    [29453] = { name = "Sporeggar Mushroom", kind = "food", min_level = 65 },
    [29454] = { name = "Silverwine", kind = "drink", min_level = 55 },
    [30155] = { name = "Clam Bar", kind = "food", min_level = 55 },
    [30355] = { name = "Grilled Shadowmoon Tuber", kind = "food", min_level = 65 },
    [30357] = { name = "Oronok's Tuber of Healing", kind = "food", min_level = 65 },
    [30358] = { name = "Oronok's Tuber of Agility", kind = "food", min_level = 65 },
    [30359] = { name = "Oronok's Tuber of Strength", kind = "food", min_level = 65 },
    [30361] = { name = "Oronok's Tuber of Spell Power", kind = "food", min_level = 65 },
    [30457] = { name = "Gilneas Sparkling Water", kind = "drink", min_level = 65 },
    [30458] = { name = "Stromgarde Muenster", kind = "food", min_level = 55 },
    [30610] = { name = "Smoked Black Bear Meat", kind = "food", min_level = 55 },
    [30703] = { name = "Conjured Mountain Spring Water", kind = "drink", min_level = 60 },
    [30816] = { name = "Spice Bread", kind = "food", min_level = 1 },
    [31672] = { name = "Mok'Nathal Shortribs", kind = "food", min_level = 55 },
    [31673] = { name = "Crunchy Serpent", kind = "food", min_level = 55 },
    [32453] = { name = "Star's Tears", kind = "drink", min_level = 65 },
    [32455] = { name = "Star's Lament", kind = "drink", min_level = 55 },
    [32668] = { name = "Dos Ogris", kind = "drink", min_level = 65 },
    [32685] = { name = "Ogri'la Chicken Fingers", kind = "food", min_level = 65 },
    [32686] = { name = "Mingo's Fortune Giblets", kind = "food", min_level = 65 },
    [32721] = { name = "Skyguard Rations", kind = "food", min_level = 55 },
    [33004] = { name = "Clamlette Surprise", kind = "food", min_level = 40 },
    [33023] = { name = "Savory Sausage", kind = "food", min_level = 35 },
    [33024] = { name = "Pickled Sausage", kind = "food", min_level = 45 },
    [33025] = { name = "Spicy Smoked Sausage", kind = "food", min_level = 55 },
    [33026] = { name = "The Golden Link", kind = "food", min_level = 65 },
    [33028] = { name = "Barleybrew Light", kind = "drink", min_level = 5 },
    [33029] = { name = "Barleybrew Dark", kind = "drink", min_level = 15 },
    [33030] = { name = "Barleybrew Clear", kind = "drink", min_level = 1 },
    [33031] = { name = "Thunder 45", kind = "drink", min_level = 25 },
    [33032] = { name = "Thunderbrew Ale", kind = "drink", min_level = 35 },
    [33033] = { name = "Thunderbrew Stout", kind = "drink", min_level = 45 },
    [33034] = { name = "Gordok Grog", kind = "drink", min_level = 55 },
    [33035] = { name = "Ogre Mead", kind = "drink", min_level = 65 },
    [33036] = { name = "Mudder's Milk", kind = "drink", min_level = 65 },
    [33042] = { name = "Black Coffee", kind = "drink", min_level = 65 },
    [33043] = { name = "The Essential Brewfest Pretzel", kind = "food", min_level = 1 },
    [33048] = { name = "Stewed Trout", kind = "food", min_level = 65 },
    [33052] = { name = "Fisherman's Feast", kind = "food", min_level = 65 },
    [33234] = { name = "Iced Berry Slush", kind = "drink", min_level = 45 },
    [33236] = { name = "Fizzy Faire Drink \"Classic\"", kind = "drink", min_level = 60 },
    [33246] = { name = "Funnel Cake", kind = "food", min_level = 55 },
    [33254] = { name = "Forest Strider Drumstick", kind = "food", min_level = 65 },
    [33825] = { name = "Skullfish Soup", kind = "drink", min_level = 65 },
    [33867] = { name = "Broiled Bloodfin", kind = "food", min_level = 55 },
    [33872] = { name = "Spicy Hot Talbuk", kind = "food", min_level = 65 },
    [34017] = { name = "Small Step Brew", kind = "drink", min_level = 1 },
    [34018] = { name = "Long Stride Brew", kind = "drink", min_level = 5 },
    [34019] = { name = "Path of Brew", kind = "drink", min_level = 15 },
    [34020] = { name = "Jungle River Water", kind = "drink", min_level = 25 },
    [34021] = { name = "Brewdoo Magic", kind = "drink", min_level = 35 },
    [34022] = { name = "Stout Shrunken Head", kind = "drink", min_level = 45 },
    [34063] = { name = "Dried Sausage", kind = "food", min_level = 15 },
    [34064] = { name = "Succulent Sausage", kind = "food", min_level = 25 },
    [34065] = { name = "Spiced Onion Cheese", kind = "food", min_level = 5 },
    [34410] = { name = "Honeyed Holiday Ham", kind = "food", min_level = 65 },
    [34411] = { name = "Hot Apple Cider", kind = "drink", min_level = 65 },
    [34412] = { name = "Sparkling Apple Cider", kind = "drink", min_level = 35 },
    [35285] = { name = "Giant Sunfish", kind = "food", min_level = 55 },
    [35563] = { name = "Charred Bear Kabobs", kind = "food", min_level = 45 },
    [35565] = { name = "Juicy Bear Burger", kind = "food", min_level = 45 },
    [35710] = { name = "Delicious Baked Ham", kind = "food", min_level = 65 },
    [38427] = { name = "Pickled Egg", kind = "food", min_level = 55 },
    [38428] = { name = "Rock-Salted Pretzel", kind = "food", min_level = 65 },
    [38429] = { name = "Blackrock Spring Water", kind = "drink", min_level = 45 },
    [38430] = { name = "Blackrock Mineral Water", kind = "drink", min_level = 60 },
    [38431] = { name = "Blackrock Fortified Water", kind = "drink", min_level = 65 },
}
