namespace Core;

public enum UI_ERROR
{
    NONE = 0,
    ERR_BADATTACKFACING = 1,
    ERR_SPELL_FAILED_S = 2,
    ERR_SPELL_OUT_OF_RANGE = 3,
    ERR_BADATTACKPOS = 4,
    ERR_AUTOFOLLOW_TOO_FAR = 5,
    SPELL_FAILED_MOVING = 6,
    ERR_SPELL_COOLDOWN = 7,
    ERR_SPELL_FAILED_ANOTHER_IN_PROGRESS = 8,
    ERR_SPELL_FAILED_STUNNED = 9,
    ERR_SPELL_FAILED_INTERRUPTED = 10,
    SPELL_FAILED_ITEM_NOT_READY = 11,
    SPELL_FAILED_TRY_AGAIN = 12,
    SPELL_FAILED_NOT_READY = 13,
    SPELL_FAILED_TARGETS_DEAD = 14,
    ERR_LOOT_LOCKED = 15,
    ERR_ATTACK_PACIFIED = 16,
    ERR_REQUIRES_S = 17,
    SPELL_FAILED_LINE_OF_SIGHT = 18,

    MAX_ERROR_RANGE = 2000,

    CAST_SENT = 999997,
    CAST_START = 999998,
    CAST_SUCCESS = 999999
}