-- rogue/class_sylvanas.lua — Rogue class spells, constants, and shared helpers.
-- WHAT:  spell ID tables, stance/form mappings, and class-specific utilities.
-- WHEN:  loaded by all rogue specs; consumed via NS.RogueSpells.
-- WHY:   single source of truth for rogue spell IDs and class constants.
-- SAFETY: nil-guarded lookups; no runtime allocations.

-- Rogue spell table, playstyle config, and child module loader.

local NS = _G.EaxRotations
if not NS then return nil end
local cl = require("shared/class_loader_sylvanas")
local load_child = cl.create_loader("rogue", "Rogue")
local load_spec = cl.create_expansion_loader("rogue", "Rogue")
local enums = cl.get_enums()
local player = NS.GetPlayer and NS.GetPlayer()
local ok_cls, cls_id = pcall(function() return player and player:get_class() end)
if not ok_cls or cls_id ~= enums.class_id.ROGUE then return nil end

local SPELLS = {
    AdrenalineRush = NS.spell_action({
        name = "AdrenalineRush",
        ids = {13750},
        levels = {50},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Ambush = NS.spell_action({
        name = "Ambush",
        ids = {27441, 11269, 11268, 11267, 8725, 8724, 8676},
        levels = {66, 58, 50, 42, 34, 26, 18},
        cast_time = 0,
        cooldown = 0,
        power_cost = 60,
        power_type = "energy",
        school = "physical",
    }),
    Backstab = NS.spell_action({
        name = "Backstab",
        ids = {26863, 25300, 11281, 11280, 11279, 8721, 2591, 2590, 2589, 53},
        levels = {68, 60, 60, 52, 44, 36, 28, 20, 12, 4},
        cast_time = 0,
        cooldown = 0,
        power_cost = 60,
        power_type = "energy",
        school = "physical",
    }),
    BladeFlurry = NS.spell_action({
        name = "BladeFlurry",
        ids = {13877},
        levels = {40},
        cast_time = 0,
        cooldown = 120,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Blind = NS.spell_action({
        name = "Blind",
        ids = {2094},
        levels = {34},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    CheapShot = NS.spell_action({
        name = "CheapShot",
        ids = {1833},
        levels = {26},
        cast_time = 0,
        cooldown = 10,
        power_cost = 60,
        power_type = "energy",
        school = "physical",
    }),
    CloakOfShadows = NS.spell_action({
        name = "CloakOfShadows",
        ids = {31224},
        levels = {66},
        cast_time = 0,
        cooldown = 60,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    ColdBlood = NS.spell_action({
        name = "ColdBlood",
        ids = {14177},
        levels = {40},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    DeadlyThrow = NS.spell_action({
        name = "DeadlyThrow",
        ids = {26679},
        levels = {64},
        cast_time = 0,
        cooldown = 15,
        power_cost = 25,
        power_type = "energy",
        school = "physical",
    }),
    Envenom = NS.spell_action({
        name = "Envenom",
        ids = {32684, 32645},
        levels = {69, 62},
        cast_time = 0,
        cooldown = 0,
        power_cost = 35,
        power_type = "energy",
        school = "nature",
    }),
    Evasion = NS.spell_action({
        name = "Evasion",
        ids = {26669, 5277},
        levels = {50, 8},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Eviscerate = NS.spell_action({
        name = "Eviscerate",
        ids = {26865, 31016, 11300, 11299, 8624, 8623, 6762, 6761, 6760, 2098},
        levels = {64, 60, 56, 48, 40, 32, 24, 16, 8, 1},
        cast_time = 0,
        cooldown = 0,
        power_cost = 35,
        power_type = "energy",
        school = "physical",
    }),
    ExposeArmor = NS.spell_action({
        name = "ExposeArmor",
        ids = {26866, 11198, 11197, 8650, 8649, 8647},
        levels = {66, 56, 46, 36, 26, 14},
        cast_time = 0,
        cooldown = 0,
        power_cost = 25,
        power_type = "energy",
        school = "physical",
    }),
    Feint = NS.spell_action({
        name = "Feint",
        ids = {27448, 25302, 11303, 8637, 6768, 1966},
        levels = {64, 60, 52, 40, 28, 16},
        cast_time = 0,
        cooldown = 10,
        power_cost = 20,
        power_type = "energy",
        school = "physical",
    }),
    Garrote = NS.spell_action({
        name = "Garrote",
        ids = {26884, 26839, 11290, 11289, 8633, 8632, 8631, 703},
        levels = {70, 61, 54, 46, 38, 30, 22, 14},
        cast_time = 0,
        cooldown = 0,
        power_cost = 50,
        power_type = "energy",
        school = "physical",
    }),
    GhostlyStrike = NS.spell_action({
        name = "GhostlyStrike",
        ids = {14278},
        levels = {56},
        cast_time = 0,
        cooldown = 20,
        power_cost = 40,
        power_type = "energy",
        school = "physical",
    }),
    Gouge = NS.spell_action({
        name = "Gouge",
        ids = {11286, 11285, 8629, 1777, 1776},
        levels = {60, 46, 32, 18, 6},
        cast_time = 0,
        cooldown = 10,
        power_cost = 45,
        power_type = "energy",
        school = "physical",
        cc_type = "incapacitate",
    }),
    Hemorrhage = NS.spell_action({
        name = "Hemorrhage",
        ids = {26864, 17348, 17347, 16511},
        levels = {70, 58, 46, 30},
        cast_time = 0,
        cooldown = 0,
        power_cost = 35,
        power_type = "energy",
        school = "physical",
    }),
    KidneyShot = NS.spell_action({
        name = "KidneyShot",
        ids = {8643, 408},
        levels = {50, 30},
        cast_time = 0,
        cooldown = 20,
        power_cost = 25,
        power_type = "energy",
        school = "physical",
    }),
    Kick = NS.spell_action({
        name = "Kick",
        ids = {38768, 1769, 1768, 1767, 1766},
        levels = {69, 58, 42, 26, 12},
        cast_time = 0,
        cooldown = 10,
        power_cost = 25,
        power_type = "energy",
        school = "physical",
    }),
    Mutilate = NS.spell_action({
        name = "Mutilate",
        ids = {34413, 34412, 34411, 1329},
        levels = {70, 60, 50, 40},
        cast_time = 0,
        cooldown = 0,
        power_cost = 60,
        power_type = "energy",
        school = "physical",
    }),
    Premeditation = NS.spell_action({
        name = "Premeditation",
        ids = {14183},
        levels = {56},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Preparation = NS.spell_action({
        name = "Preparation",
        ids = {14185},
        levels = {40},
        cast_time = 0,
        cooldown = 600,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Rupture = NS.spell_action({
        name = "Rupture",
        ids = {26867, 11275, 11274, 11273, 8640, 8639, 1943},
        levels = {68, 60, 52, 44, 36, 28, 20},
        cast_time = 0,
        cooldown = 0,
        power_cost = 25,
        power_type = "energy",
        school = "physical",
    }),
    Sap = NS.spell_action({
        name = "Sap",
        ids = {11297, 2070, 6770},
        levels = {48, 28, 10},
        cast_time = 0,
        cooldown = 10,
        power_cost = 45,
        power_type = "energy",
        school = "physical",
        cc_type = "sap",
    }),
    Shadowstep = NS.spell_action({
        name = "Shadowstep",
        ids = {36554},
        levels = {70},
        cast_time = 0,
        cooldown = 30,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Shiv = NS.spell_action({
        name = "Shiv",
        ids = {5938},
        levels = {28},
        cast_time = 0,
        cooldown = 0,
        power_cost = 20,
        power_type = "energy",
        school = "physical",
    }),
    SinisterStrike = NS.spell_action({
        name = "SinisterStrike",
        ids = {26862, 26861, 11294, 11293, 8621, 1760, 1759, 1758, 1757, 1752},
        levels = {70, 62, 54, 46, 38, 30, 22, 14, 6, 1},
        cast_time = 0,
        cooldown = 0,
        power_cost = 45,
        power_type = "energy",
        school = "physical",
    }),
    SliceAndDice = NS.spell_action({
        name = "SliceAndDice",
        ids = {6774, 5171},
        levels = {42, 10},
        cast_time = 0,
        cooldown = 0,
        power_cost = 25,
        power_type = "energy",
        school = "physical",
    }),
    Sprint = NS.spell_action({
        name = "Sprint",
        ids = {11305, 8696, 2983},
        levels = {58, 34, 10},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Stealth = NS.spell_action({
        name = "Stealth",
        ids = {1787, 1786, 1785, 1784},
        levels = {60, 40, 20, 1},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    ThistleTea = NS.spell_action({
        name = "ThistleTea",
        ids = {9513},
        levels = {30},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Vanish = NS.spell_action({
        name = "Vanish",
        ids = {26889, 1857, 1856},
        levels = {62, 42, 22},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    UnavailableClassicRogueBuilder = nil,
    UnavailableClassicRogueDefensive = nil,
    UnavailableClassicRogueFinisher = nil,
    UnavailableClassicRogueThrow = nil,
    UnavailableClassicRogueUtility = nil,
}

NS.RogueSpells = SPELLS

local config = {
    class_key = "rogue",
    class_name = "Rogue",
    default_playstyle = "combat",
    playstyles = {
        { name = "leveling", display_name = "Leveling" },
        { name = "assassination", display_name = "Assassination" },
        { name = "combat", display_name = "Combat" },
        { name = "subtlety", display_name = "Subtlety" },
    },
}
NS.rotation_registry:set_class_config(config)

load_child("middleware_sylvanas")
load_spec("leveling", true)
load_spec("assassination")
load_spec("combat")
load_spec("subtlety")
-- class module initialized
return config
