-- run_clean_checkout_probe.lua -- clean-checkout dependency probe.
-- WHAT:  scans every test/runner .lua under EaxRotations/tests/ for
--        file-read targets (io.open / read_file / open_first string
--        literals, plus any other path-like string literal) and asserts
--        each resolves to a git-TRACKED file or a known SELF-PROVISIONING
--        artifact. A test reading a file that exists locally but is
--        gitignored (wowsims.db, .omo/evidence/*) passes on a dev box and
--        silently fails on a clean checkout -- the exact gap class that
--        broke the 5 rotation suites (see
--        docs/rotation_suite_env_gap_triage_2026-08-08.md). This probe
--        turns that class into a hard CI failure. require() spells a module
--        name WITHOUT its .lua suffix, so an extension-less module literal
--        resolved to no file and was silently skipped; the .lua sibling is
--        now tried as well, so an untracked module a test requires is caught
--        exactly like an untracked file read.
-- WHEN:  invoked via lua EaxRotations/tests/run_clean_checkout_probe.lua
--        (standalone) or as a component of run_verify_all.lua.
-- EXIT:  0 = all read targets tracked or self-provisioning (prints [PASS]);
--        1 = at least one untracked read target (prints [FAIL] lines).
-- SAFETY: read-only over tests/ + git ls-files. No writes, no mutation.
--         Named run_* so test_spec_layout_compliance's banned-API scan of
--         EaxRotations/tests/ exempts the os.execute/io.popen calls.

local lfs_ok, lfs = pcall(require, "lfs")

-- ---------------------------------------------------------------------------
-- Tracked-file set from git (repo tracks ONLY EaxRotations/ + README.md;
-- everything else -- tools/, wowheadScrape/, .omo/ -- is gitignored).
-- ---------------------------------------------------------------------------
local TRACKED = {}
local function load_tracked()
    -- NOTE: no `2>/dev/null` — on Windows cmd.exe that redirect targets a
    -- literal file and popen fails, silently emptying the tracked set.
    local pipe = io.popen("git ls-files")
    if not pipe then return end
    for line in pipe:lines() do
        local p = line:gsub("\\", "/"):gsub("^%./", "")
        if p ~= "" then TRACKED[p] = true end
    end
    pipe:close()
end

-- Self-provisioning roots: artifacts regenerated by tracked generators
-- before the suite runs (see tools/generate_sod_task1_action_map.lua ->
-- .omo/evidence/; EaxRotations/tools/generate_buff_debuff_verification.py
-- -> EaxRotations/tools/buff_debuff_full_verification.json).
local SELF_PROVISIONING_PREFIXES = {
    ".omo/",
    "EaxRotations/.omo/",
    "../.omo/",
}

local function is_self_provisioning(path)
    for _, prefix in ipairs(SELF_PROVISIONING_PREFIXES) do
        if path:sub(1, #prefix) == prefix then return true end
    end
    -- buff_debuff json is TRACKED (committed), so it needs no allowance;
    -- only .omo evidence is regenerated per-run.
    return false
end

-- Tests run with cwd at the repo root OR inside EaxRotations/ (the runners
-- chdir to match), so a literal may appear as "EaxRotations/...",
-- "classes/...", "main.lua", or "/tests/...". Canonicalize every spelling
-- to the repo-root-relative form before checking the tracked set.
local EAX_PREFIX = "EaxRotations/"
local function canonical(path)
    local p = path:gsub("\\", "/"):gsub("^%./", ""):gsub("^/", "")
    if p:sub(1, #EAX_PREFIX) ~= EAX_PREFIX then
        p = EAX_PREFIX .. p
    end
    return p
end

-- Directory fragments from path concatenation (root .. "/" .. file) carry a
-- trailing separator ("EaxRotations/classes/", "/", "//").  Strip it before
-- the lfs mode check: lfs.attributes() with a trailing slash is inconsistent
-- across Windows spawn contexts (works from bash, returns nil under
-- cmd.exe-spawned os.execute), which would otherwise make the file-only check
-- platform/context-dependent.
local function strip_trailing_sep(p)
    return (p:gsub("[/\\]+$", ""))
end

-- ---------------------------------------------------------------------------
-- Module-name resolution (a require() carries no .lua suffix)
-- ---------------------------------------------------------------------------
-- A literal only reaches the report as a clean-checkout risk when it resolves
-- to a real file, so "shared/bar" or "classes/x/y/z" resolved to nothing and
-- was skipped: a test requiring an untracked module passed locally and failed
-- on a clean checkout, which is this probe's entire reason to exist. Try the
-- .lua sibling too, and let is_tracked use the SAME spelling list, so the
-- "exists but untracked" decision is made about one and the same file. Uniform
-- across every namespace: when the priest helper was untracked this probe and
-- run_module_enrollment_probe.lua each named it, and that is two independent
-- invariants rather than double-reporting noise.
local function module_spellings(path)
    if path:match("%.lua$") then return { path } end
    return { path, path .. ".lua" }
end

-- A path is trackable only if it is actually listed by git ls-files.
-- canonical(path) rewrites EaxRotations-cwd spellings ("shared/x.lua" ->
-- "EaxRotations/shared/x.lua") for tests that read relative to EaxRotations/;
-- but repo-root spellings ("tools/evidence/apl/fire_wotlk.apl.json") must
-- match the tracked set as-is, so check BOTH forms. (The repo historically
-- tracked only EaxRotations/ + README.md; tools/evidence/ is now tracked too,
-- which is exactly why the raw form must not be canonicalized away.) The
-- .lua sibling is consulted after the literal's own spellings, so a
-- fully-suffixed path resolves exactly as before.
local function is_tracked(path)
    local raw = path:gsub("\\", "/"):gsub("^%./", "")
    for _, spelling in ipairs(module_spellings(raw)) do
        if TRACKED[canonical(spelling)] or TRACKED[spelling] then return true end
    end
    return false
end

-- ---------------------------------------------------------------------------
-- Extract path-like string literals from a test file.
-- ---------------------------------------------------------------------------
-- Patterns that open a file with a string literal:
--   io.open("path"[, mode])        read_file("path")        open_first({...})
-- We also catch any string literal that LOOKS like a path (contains a slash
-- and a dot) so a new helper form cannot silently slip past.
local function extract_paths(content)
    local paths = {}
    local seen = {}
    local function add(p)
        if not p or p == "" then return end
        p = p:gsub("^%s+", ""):gsub("%s+$", "")
        if p:find("?") then return end              -- pattern, not a path
        if p:find("%%s") then return end            -- format string
        if p:sub(1, 1) == "%" then return end
        -- mode args ("rb", "r", "w", "wb") and non-path words: a path
        -- must contain a separator or a file-ish extension.
        local has_sep = p:find("/", 1, true) or p:find("\\", 1, true)
        local fileish = p:match("%.%w+$")
        if not has_sep and not fileish then return end
        -- normalize separators
        p = p:gsub("\\", "/")
        if not seen[p] then
            seen[p] = true
            paths[#paths + 1] = p
        end
    end

    -- Collect ALL string literals (double-quoted and single-quoted) so a new
    -- helper form (open_first, read, io.open, etc.) cannot slip past -- then
    -- let add() filter out non-path strings like mode args and labels.
    for literal in content:gmatch('"([^"\r\n]*)"') do
        add(literal)
    end
    for literal in content:gmatch("'([^'\r\n]*)'") do
        add(literal)
    end
    return paths
end

-- Does the path resolve to a real file on disk? Tests run with cwd at the
-- repo root OR inside EaxRotations/, so a literal may mean either a
-- repo-root path ("wowheadScrape/dbc_extract/wowsims.db", "../.omo/...")
-- or an EaxRotations-relative path ("shared/...", "main.lua"). Check all
-- spellings: raw (repo-root cwd), canonical (EaxRotations cwd), and the
-- ../-stripped form. canonical() is reused for the EaxRotations cwd reading
-- so normalization stays single-sourced.
local function exists_on_disk(path)
    local candidates = { path, canonical(path) }
    if path:sub(1, 3) == "../" then
        candidates[#candidates + 1] = path:sub(4)
    end
    -- Extension-less module names get their .lua sibling added here, so an
    -- untracked module a test requires reports the same way an untracked file
    -- read does (see module_spellings + the single-signal guard above).
    local expanded = {}
    for _, cand in ipairs(candidates) do
        for _, spelling in ipairs(module_spellings(cand)) do
            expanded[#expanded + 1] = spelling
        end
    end
    candidates = expanded
    for _, cand in ipairs(candidates) do
        -- Only a regular FILE is a clean-checkout risk.  Directory fragments
        -- (e.g. "classes/" / "EaxRotations/" from `root .. "/" .. file`
        -- concatenation) must NOT count: on POSIX io.open succeeds on a
        -- directory, so the old io.open probe flagged them on Linux CI while
        -- passing on Windows — a platform-dependent false positive.  Use lfs
        -- (already required below) to check the mode explicitly, falling back
        -- to the io.open probe only when lfs is unavailable.  Strip the
        -- trailing separator first (see strip_trailing_sep): lfs.attributes
        -- on "dir/" is inconsistent across spawn contexts on Windows.
        cand = strip_trailing_sep(cand)
        if lfs_ok then
            local attr = lfs.attributes(cand)
            if attr and attr.mode == "file" then return true end
        else
            local f = io.open(cand, "rb")
            if f then f:close() return true end
        end
    end
    return false
end

-- ---------------------------------------------------------------------------
-- Self-test: prove the directory-vs-file fix is live on every platform.
-- ---------------------------------------------------------------------------
-- The fix under test: exists_on_disk() must only count REGULAR FILES.  On
-- POSIX io.open(dir, "rb") succeeds (a directory is openable for read), so
-- the old io.open probe flagged directory fragments like "classes/" / "/" /
-- "//" / "EaxRotations/" (path-concatenation leftovers in audit files) as
-- untracked read targets on Linux CI while passing on Windows.  These
-- assertions fail if the mode check is ever reverted to the bare io.open
-- probe.
local function run_self_tests()
    local function expect(cond, label)
        if not cond then
            error("run_clean_checkout_probe self-test: " .. label)
        end
    end

    -- 1. Root-cause guard: a directory's lfs mode must NOT be "file".  This is
    --    the exact property the old io.open probe got wrong on POSIX (io.open
    --    on a directory returns a handle there), so it is the regression pin.
    --    The trailing separator is stripped first (same normalization the
    --    probe applies) so the assertion is valid under every spawn context.
    local dattr = lfs.attributes(strip_trailing_sep(canonical("EaxRotations/classes/")))
    expect(dattr ~= nil, "EaxRotations/classes/ must resolve via lfs.attributes")
    expect(dattr.mode == "directory", "EaxRotations/classes/ must be a directory")
    expect(dattr.mode ~= "file", "directory must not report mode=file (POSIX io.open regression guard)")

    -- 2. exists_on_disk must be file-only for directory fragments.
    expect(exists_on_disk("EaxRotations/classes/") == false, "classes/ directory fragment must not count as a file")
    expect(exists_on_disk("EaxRotations/") == false, "repo-root dir must not count as a file")
    expect(exists_on_disk("/") == false, "root dir must not count as a file")
    expect(exists_on_disk("EaxRotations/tests/") == false, "tests/ dir must not count as a file")

    -- 3. Real files must still be detected (the probe must keep catching the
    --    gitignored-read gap class it exists for).
    expect(exists_on_disk("EaxRotations/tests/run_clean_checkout_probe.lua") == true, "real tracked file must be detected")

    -- 4. Nonexistent paths must not be detected.
    expect(exists_on_disk("EaxRotations/tests/__no_such_probe_fixture__.lua") == false, "nonexistent path must not be detected")

    -- 5. Classification helpers stay sane: tracked-set loads from git and the
    --    self-provisioning allowance for .omo evidence still holds.
    load_tracked()
    local tcount = 0
    for _ in pairs(TRACKED) do tcount = tcount + 1 end
    expect(tcount > 0, "git ls-files must return tracked files (git on PATH)")
    expect(is_tracked("EaxRotations/tests/run_clean_checkout_probe.lua") == true, "probe file must be tracked")
    expect(is_tracked("EaxRotations/classes/") == false, "directory fragment must not be tracked")
    expect(is_self_provisioning(".omo/evidence/x.json") == true, ".omo evidence must be self-provisioning")

    -- 6. Module-name resolution: an extension-less require() must resolve to a
    --    real file, and agree with is_tracked on the SAME spelling, so the
    --    tracked set stays silent instead of false-flagging every module.
    local own_module = "EaxRotations/tests/run_clean_checkout_probe"
    expect(exists_on_disk(own_module) == true,
        "extension-less module name must resolve to its .lua sibling")
    expect(is_tracked(own_module) == true,
        "a tracked module resolved by its .lua sibling must stay silent")
    -- 7. The path this probe exists for: a real module that is NOT tracked must
    --    be flagged. Simulated in the tracked set (no writes) so the pin cannot
    --    go stale when the helper/whatever it names is eventually committed.
    local saved_entry = TRACKED[own_module .. ".lua"]
    TRACKED[own_module .. ".lua"] = nil
    local would_flag = exists_on_disk(own_module) and not is_tracked(own_module)
        and not is_self_provisioning(own_module)
    TRACKED[own_module .. ".lua"] = saved_entry
    expect(would_flag == true,
        "an untracked module required by a test must be flagged (forgotten git add)")

    print("[PASS] run_clean_checkout_probe self-tests: dir-vs-file (POSIX regression guard), real-file detection, missing-path handling, tracked-set + self-provisioning classification, and extension-less module resolution (resolves, stays silent when tracked, flags when untracked)")
    return 0
end

-- ---------------------------------------------------------------------------
-- Main scan
-- ---------------------------------------------------------------------------
local function scan_dir(dir)
    local files = {}
    local function walk(d)
        for entry in lfs.dir(d) do
            if entry ~= "." and entry ~= ".." then
                local full = d .. "/" .. entry
                local attr = lfs.attributes(full)
                if attr then
                    if attr.mode == "file" and entry:match("%.lua$") then
                        files[#files + 1] = full
                    elseif attr.mode == "directory" then
                        walk(full)
                    end
                end
            end
        end
    end
    walk(dir)
    return files
end

local function main()
    if arg and arg[1] == "--self-test" then
        return run_self_tests()
    end
    if not lfs_ok or not lfs then
        -- Hard-fail (not SKIP): this probe is the enforcement gate for the
        -- gitignored-read gap class, so it must never silently disappear on a
        -- box without lfs. CI installs luafilesystem via luarocks.
        print("FAIL run_clean_checkout_probe: lfs unavailable (install luafilesystem) — cannot scan test files")
        return 1
    end
    load_tracked()

    local tracked_count = 0
    for _ in pairs(TRACKED) do tracked_count = tracked_count + 1 end
    if tracked_count == 0 then
        -- Fail-closed but legible: an empty tracked set means git ls-files
        -- yielded nothing (git not on PATH), so "untracked" would be
        -- meaningless and every existing file would false-flag.
        print("FAIL run_clean_checkout_probe: git ls-files returned no tracked files (git not on PATH?) — cannot verify the tracked set")
        return 1
    end

    local root = "EaxRotations/tests"
    local files = scan_dir(root)
    local untracked = {}
    local checked = 0

    for _, file in ipairs(files) do
        -- Skip the probe's own file: its comments legitimately name the
        -- gitignored paths it guards (e.g. the wowheadScrape docstring)
        -- and would self-flag.
        if file:find("run_clean_checkout_probe%.lua$") then
            checked = checked + 1
        else
            local f = io.open(file, "rb")
            if f then
                local content = f:read("*a") or ""
                f:close()
                for _, p in ipairs(extract_paths(content)) do
                    -- Skip package.path patterns and obviously non-path strings.
                    -- A path is only a clean-checkout risk if it actually exists
                    -- on disk (a nonexistent read would fail the test locally
                    -- too). If it exists but is untracked + not self-provisioning,
                    -- it passes locally and breaks in CI -- flag it.
                    if not p:find("%?") then
                        if exists_on_disk(p) and not is_tracked(p) and not is_self_provisioning(p) then
                            untracked[#untracked + 1] = { file = file, path = p }
                        end
                        checked = checked + 1
                    end
                end
            end
        end
    end

    if #untracked == 0 then
        print(string.format("clean-checkout probe: %d path literals checked across %d test files — all tracked or self-provisioning", checked, #files))
        print("[PASS] run_clean_checkout_probe")
        return 0
    end

    print(string.format("FAIL: %d untracked read target(s) found (pass locally, fail on clean checkout):", #untracked))
    for _, u in ipairs(untracked) do
        print(string.format("  [FAIL] %s  ->  %s", u.file, u.path))
    end
    print("  Fix: commit the file, point the test at a tracked file, or mark the path self-provisioning.")
    return 1
end

os.exit(main())
