-- run_era_pair_audit_tests.lua -- Static audit: era-mirror strategy coverage.
-- WHAT:  Compares the strategy-name sets of era sibling files
--        (<spec>_sylvanas.lua / <spec>_vanilla.lua / <spec>_wotlk.lua) and
--        flags a strategy present in one era but missing in a sibling. The
--        flagged set must stay within the reviewed baseline table
--        (tests/era_pair_seed.lua, regenerated by
--        EaxRotations/tools/generate_era_pair_seed.py) — the badge-drift
--        pattern applied to era coverage: the seed records the CURRENT,
--        deliberately-accepted divergences (WotLK-era build-out, vanilla
--        mirror leanness, TBC-via-middleware naming, era-only abilities), and
--        the audit FAILS when the live tree's divergence set grows beyond it.
-- WHEN:  Run manually, in CI (verify_all), and in the pre-commit gate.
-- WHY:   The WotLK rogue interrupt gap (combat/subtlety/assassination had zero
--        Kick handling while the TBC era covered rogues centrally) was found
--        only by hand. This audit makes that defect class mechanical: adding a
--        strategy to one era without its siblings, or removing a strategy from
--        one sibling, surfaces as a new divergence outside the baseline.
-- SAFETY: Read-only text scan + static classification; --self-test has no
--         filesystem writes (synthetic in-memory content only).

package.path = "EaxRotations/?.lua;EaxRotations/?/?.lua;EaxRotations/?/?/?.lua;./?.lua;tools/?.lua;" .. package.path

local CLASS_ROOT = "EaxRotations/classes"

-- ---------------------------------------------------------------------------
-- Comment stripping: identical to the dead-matcher audit — replace comment
-- text with same-length spaces so comment text can never count as a name.
-- A `--` inside a string is treated as a comment opener, which can only cause
-- FALSE NEGATIVES (missed divergence), never false positives.
-- ---------------------------------------------------------------------------
local function strip_comments(content)
    local pieces = {}
    local pos = 1
    local len = #content
    while pos <= len do
        local s = content:find("%-%-", pos)
        if not s then
            pieces[#pieces + 1] = content:sub(pos)
            break
        end
        pieces[#pieces + 1] = content:sub(pos, s - 1)
        local eq = content:match("^%-%-%[(=*)%[", s)
        if eq then
            local close = content:find("%]" .. eq .. "%]", s + 3 + #eq)
            if close then
                pieces[#pieces + 1] = content:sub(s, close + #eq + 1):gsub(".", " ")
                pos = close + #eq + 2
            else
                pieces[#pieces + 1] = content:sub(s):gsub(".", " ")
                pos = len + 1
            end
        else
            local nl = content:find("\n", s + 2)
            if nl then
                pieces[#pieces + 1] = content:sub(s, nl - 1):gsub(".", " ")
                pos = nl
            else
                pieces[#pieces + 1] = content:sub(s):gsub(".", " ")
                pos = len + 1
            end
        end
    end
    return table.concat(pieces)
end

-- ---------------------------------------------------------------------------
-- Strategy-name resolver. Recognizes every definition style used in the repo:
--   * literal `name = "X"` — strategy tables, DSL_DEFS entries, and the
--     name-only placeholder lists the DSL substitutes (`{ name = "X" }`).
--   * `build_action("X", ...)` — the warrior strategy-builder helper
--     (warrior/shared_helpers_sylvanas.lua:115), whose row.name = X.
--   * `register_interrupt_spell("cls", "X", ...)` / `create_interrupt_strategy`
--     in the class middleware — class-baseline interrupts (handled by the
--     middleware fold, which adds these names to every TBC spec of the class).
-- ---------------------------------------------------------------------------
local function names_in(content)
    local stripped = strip_comments(content)
    local names = {}
    for token in stripped:gmatch('name%s*=%s*"([%a_][%w_]*)"') do
        names[token] = true
    end
    for token in stripped:gmatch('build_action%s*%(%s*"([%a_][%w_]*)"') do
        names[token] = true
    end
    return names
end

-- Class middleware interrupt registrations (register_interrupt_spell /
-- create_interrupt_strategy). These are class-baseline capabilities the
-- middleware provides era-wide, so they fold into the sylvanas spec sets.
local function middleware_interrupts()
    local pipe = io.popen("find " .. CLASS_ROOT .. " -name 'middleware_sylvanas.lua'")
    local by_class = {}
    for line in pipe:lines() do
        local cls = line:match("classes/([^/]+)/middleware_sylvanas%.lua$")
            or line:match("classes[\\]([^\\]+)[\\]middleware_sylvanas%.lua$")
        local f = io.open(line, "rb")
        if cls and f then
            local content = f:read("*a")
            f:close()
            local stripped = strip_comments(content)
            local regs = {}
            for name in stripped:gmatch('register_interrupt_spell%s*%(%s*"[^"]*"%s*,%s*"([%a_][%w_]*)"') do
                regs[name] = true
            end
            for name in stripped:gmatch('create_interrupt_strategy%s*%(%s*%{%s*[^}]*name%s*=%s*"([%a_][%w_]*)"') do
                regs[name] = true
            end
            by_class[cls] = regs
        end
    end
    pipe:close()
    return by_class
end

-- ---------------------------------------------------------------------------
-- Scan: group era files by (class, spec) and compute per-era name sets.
-- ---------------------------------------------------------------------------
local function run_scan()
    local pipe = io.popen("find " .. CLASS_ROOT .. " -name '*.lua'")
    local files = {}
    for line in pipe:lines() do
        local rel = line:gsub("^" .. CLASS_ROOT .. "/", ""):gsub("\\", "/")
        files[#files + 1] = rel
    end
    pipe:close()
    table.sort(files)

    local mid = middleware_interrupts()
    local specs = {} -- key = "class/spec" -> { era = names }
    for _, rel in ipairs(files) do
        local base = rel:match("([^/]+)%.lua$") -- stem without .lua
        -- NOTE: Lua patterns have NO alternation (|), so the era must be
        -- matched as a class then checked for membership -- a literal
        -- (sylvanas|vanilla|wotlk) group matches nothing (the bug this audit
        -- fixed while first being run: the scan silently collected 0 files).
        local spec, era = base:match("^(.+)_([%a_]+)$")
        if not (era == "sylvanas" or era == "vanilla" or era == "wotlk") then
            spec, era = nil, nil
        end
        if spec and era then
            -- Class infrastructure, not per-spec era rotations.
            if base:match("leveling") or base:match("middleware") or base:match("class_sylvanas")
                or base:match("schema") or base:match("shared_helpers") then
                -- excluded by design (documented in the seed header)
            else
                local cls = rel:match("^([^/]+)/")
                local key = cls .. "/" .. spec
                local f = io.open(CLASS_ROOT .. "/" .. rel, "rb")
                if f then
                    local content = f:read("*a")
                    f:close()
                    local names = names_in(content)
                    if era == "sylvanas" and mid[cls] then
                        for n in pairs(mid[cls]) do names[n] = true end
                    end
                    if not specs[key] then specs[key] = {} end
                    specs[key][era] = names
                end
            end
        end
    end
    return specs
end

-- Divergence set: for each spec with >= 2 era files and each era, the names
-- present in a sibling era but missing in this era.
-- Returns list of { spec, era, name }.
local function divergences(specs)
    local out = {}
    for key, eras in pairs(specs) do
        local era_names = {}
        for era in pairs(eras) do era_names[#era_names + 1] = era end
        if #era_names >= 2 then
            for era in pairs(eras) do
                local missing = {}
                for other in pairs(eras) do
                    if other ~= era then
                        for n in pairs(eras[other]) do
                            if not eras[era][n] then missing[n] = true end
                        end
                    end
                end
                for n in pairs(missing) do
                    out[#out + 1] = { spec = key, era = era, name = n }
                end
            end
        end
    end
    return out
end

-- Seed key: spec|era|name
local function seed_keys()
    local ok, seed = pcall(dofile, "EaxRotations/tests/era_pair_seed.lua")
    if not ok or type(seed) ~= "table" then
        return nil, "cannot load era_pair_seed.lua: " .. tostring(seed)
    end
    local keys = {}
    for _, e in ipairs(seed) do
        if type(e.spec) == "string" and type(e.missing_in) == "string" and type(e.names) == "table" then
            for _, n in ipairs(e.names) do
                keys[e.spec .. "|" .. e.missing_in .. "|" .. n] = true
            end
        end
    end
    return keys
end

-- ---------------------------------------------------------------------------
-- Self-tests (non-vacuity): resolver styles, middleware fold, divergence and
-- seed semantics. Synthetic in-memory content only.
-- ---------------------------------------------------------------------------
local function run_self_tests()
    local function expect(actual, expected, label)
        if actual ~= expected then
            error(label .. ": expected " .. tostring(expected) .. ", got " .. tostring(actual))
        end
    end

    -- Style 1: literal name = "X" in a strategy table (repo convention is
    -- double-quoted names — 3,739 double vs 0 single in classes/).
    local lit = names_in('local S = {\n    { name = "SliceAndDice", matches = fn },\n}')
    expect(lit.SliceAndDice, true, "literal name resolves")
    expect(lit.Missing, nil, "no false name")

    -- Style 2: DSL_DEFS + name-only placeholder list.
    local dsl = names_in('local DSL_DEFS = { { name = "Kick", conditions = {} } }\nlocal s = { { name = "Kick" }, { name = "Eviscerate" } }')
    expect(dsl.Kick, true, "DSL def name resolves")
    expect(dsl.Eviscerate, true, "placeholder name resolves")

    -- Style 3: build_action("X", ...) (warrior helper).
    local ba = names_in('return build_action("Hamstring", ACTION.Hamstring, { min_rage = 10 })')
    expect(ba.Hamstring, true, "build_action name resolves")

    -- Style 4: comment text must NOT resolve (line + block).
    local com = names_in('-- name = "PhantomInComment"\n--[[ name = "PhantomInBlock" ]]')
    expect(com.PhantomInComment, nil, "line-comment mention ignored")
    expect(com.PhantomInBlock, nil, "block-comment mention ignored")

    -- Style 5: middleware fold — interrupt registrations are folded in by
    -- run_scan() via middleware_interrupts(), NOT by names_in. Assert names_in
    -- does not hallucinate a name from a register_interrupt_spell call, and
    -- that the real rogue middleware's registration is picked up by the fold
    -- source (real-file probe, like the rogue-trio probe below).
    local mid_src = names_in('    interrupt_manager.register_interrupt_spell("rogue", "Kick", SPELLS)')
    expect(mid_src.Kick, nil, "names_in does not extract interrupt registrations (fold's job)")
    local mid_table = middleware_interrupts()
    expect(mid_table.rogue and mid_table.rogue.Kick, true, "real rogue middleware registers Kick (fold source)")

    -- Divergence semantics: {sylvanas:{A}, vanilla:{A}, wotlk:{}} ->
    -- A is missing in wotlk (the rogue-Kick pre-fix shape).
    local s1 = { ["rogue/combat"] = { sylvanas = { A = true }, vanilla = { A = true }, wotlk = {} } }
    local d1 = divergences(s1)
    local found = false
    for _, d in ipairs(d1) do
        if d.spec == "rogue/combat" and d.era == "wotlk" and d.name == "A" then found = true end
    end
    expect(found, true, "missing-sibling divergence detected")

    -- Seed semantics: divergence within the seed passes; outside fails.
    local keys = { ["rogue/combat|vanilla|A"] = true } -- allowlist "A missing vanilla"
    local d2 = {
        { spec = "rogue/combat", era = "vanilla", name = "A" },  -- allowlisted
        { spec = "rogue/combat", era = "wotlk", name = "A" },    -- NOT allowlisted
    }
    local unallowed = 0
    for _, d in ipairs(d2) do
        if not keys[d.spec .. "|" .. d.era .. "|" .. d.name] then unallowed = unallowed + 1 end
    end
    expect(unallowed, 1, "seed allows listed divergences only")

    -- seed_keys(): loads the real seed and it must parse (covers all eras).
    local sk, err = seed_keys()
    expect(sk ~= nil, true, "seed loads: " .. tostring(err))
    expect(next(sk) ~= nil, true, "seed is non-empty")

    -- Real-file probe: the fixed rogue trio — the ONLY rogue divergences in the
    -- seed must be the vanilla-naming ones (Kick/KickInterrupt); no divergence
    -- may be unallowlisted. This is the "passes on the now-fixed rogue trio".
    -- Non-vacuous: assert the real scan actually FOUND the rogue trio with all
    -- three eras first, so a broken run_scan (empty set) fails the self-test
    -- instead of passing over zero data.
    local specs = run_scan()
    -- Lua patterns have no alternation -- compare against the three explicit
    -- rogue spec keys instead of a (combat|subtlety|assassination) group.
    local ROGUE_SPECS = { ["rogue/combat"] = true, ["rogue/subtlety"] = true, ["rogue/assassination"] = true }
    local rogue_found = 0
    for key, eras in pairs(specs) do
        if ROGUE_SPECS[key] and eras.sylvanas and eras.vanilla and eras.wotlk then
            rogue_found = rogue_found + 1
        end
    end
    expect(rogue_found, 3, "real scan finds the rogue trio with all three eras (non-vacuous)")
    local keys2 = seed_keys()
    local rogue_bad = 0
    for _, d in ipairs(divergences(specs)) do
        if ROGUE_SPECS[d.spec]
            and not keys2[d.spec .. "|" .. d.era .. "|" .. d.name] then
            rogue_bad = rogue_bad + 1
        end
    end
    expect(rogue_bad, 0, "rogue trio has zero unallowlisted divergences (post-fix)")

    -- Non-vacuity injection: a synthetic spec where WotLK lacks a strategy the
    -- other eras have must FAIL the check (the audit catches the rogue class).
    local inj = {
        ["druid/bear"] = { sylvanas = { Growl = true }, vanilla = { Growl = true }, wotlk = {} },
    }
    local inj_keys = { ["druid/bear|vanilla|Growl"] = true, ["druid/bear|sylvanas|Growl"] = true }
    local inj_bad = 0
    for _, d in ipairs(divergences(inj)) do
        if not inj_keys[d.spec .. "|" .. d.era .. "|" .. d.name] then inj_bad = inj_bad + 1 end
    end
    expect(inj_bad > 0, true, "injected missing-wotlk strategy is flagged (non-vacuous)")

    print("[PASS] Era-pair audit self-tests: name resolver (literal / DSL / build_action / "
        .. "middleware registration), comment exclusion, divergence semantics, seed "
        .. "allowlist semantics, real-file rogue-trio probe, missing-sibling injection")
    os.exit(0)
end

-- ---------------------------------------------------------------------------
-- CLI
-- ---------------------------------------------------------------------------
if arg and arg[1] == "--self-test" then
    run_self_tests()
end

local specs = run_scan()
local keys, load_err = seed_keys()
if not keys then
    io.stderr:write("ERROR: " .. tostring(load_err) .. "\n")
    os.exit(1)
end

local divs = divergences(specs)
local failures = {}
local covered = 0
for _, d in ipairs(divs) do
    if keys[d.spec .. "|" .. d.era .. "|" .. d.name] then
        covered = covered + 1
    else
        failures[#failures + 1] = d
    end
end

print("=============================================================================")
print("  ERA-PAIR COVERAGE AUDIT (strategy present in one era, missing in a sibling)")
print("=============================================================================")
local spec_rows = {}
for _, d in ipairs(divs) do
    if not spec_rows[d.spec] then spec_rows[d.spec] = { total = 0, bad = 0 } end
    spec_rows[d.spec].total = spec_rows[d.spec].total + 1
    if not keys[d.spec .. "|" .. d.era .. "|" .. d.name] then
        spec_rows[d.spec].bad = spec_rows[d.spec].bad + 1
    end
end
local clean_specs = 0
local order = {}
for spec in pairs(spec_rows) do order[#order + 1] = spec end
table.sort(order)
for _, spec in ipairs(order) do
    local r = spec_rows[spec]
    if r.bad == 0 then
        clean_specs = clean_specs + 1
        print(string.format("  [ PASS ]  %-40s %d divergences, 0 unallowlisted", spec, r.total))
    end
end
print("=============================================================================")
print(string.format("  Specs compared:  %d (era siblings with divergences)", #order))
print(string.format("  Clean:           %d", clean_specs))
print(string.format("  Divergences:     %d (%d covered by seed, %d unallowlisted)", #divs, covered, #failures))
print("=============================================================================")

if #failures > 0 then
    print("  Era-coverage drift NOT in the baseline seed (era_pair_seed.lua):")
    for _, d in ipairs(failures) do
        print(string.format("    %s: %s missing %s", d.spec, d.name, d.era))
    end
    print("")
    print("  A strategy is present in one era file of a spec but missing in a sibling.")
    print("  Fix: add it to the sibling era file(s) (if it is a live rotation gap) or")
    print("  regenerate the seed after an intentional re-baseline with")
    print("  python EaxRotations/tools/generate_era_pair_seed.py and review the diff.")
    os.exit(1)
end

print("  Every era-mirror divergence is covered by the reviewed baseline seed.")
os.exit(0)
