-- run_clean_checkout_probe.lua -- clean-checkout dependency probe.
-- WHAT:  scans every test/runner .lua under EaxRotations/tests/ for
--        file-read targets (io.open / read_file / open_first string
--        literals, plus any other path-like string literal) and asserts
--        each resolves to a git-TRACKED file or a known SELF-PROVISIONING
--        artifact. A test reading a file that exists locally but is
--        gitignored (wowsims.db, .omo/evidence/*) passes on a dev box and
--        silently fails on a clean checkout -- the exact gap class that
--        broke the 5 rotation suites (see
--        docs/rotation_suite_env_gap_triage_2026-08-08.md). This probe
--        turns that class into a hard CI failure.
-- WHEN:  invoked via lua EaxRotations/tests/run_clean_checkout_probe.lua
--        (standalone) or as a component of run_verify_all.lua.
-- EXIT:  0 = all read targets tracked or self-provisioning (prints [PASS]);
--        1 = at least one untracked read target (prints [FAIL] lines).
-- SAFETY: read-only over tests/ + git ls-files. No writes, no mutation.
--         Named run_* so test_spec_layout_compliance's banned-API scan of
--         EaxRotations/tests/ exempts the os.execute/io.popen calls.

local lfs_ok, lfs = pcall(require, "lfs")

-- ---------------------------------------------------------------------------
-- Tracked-file set from git (repo tracks ONLY EaxRotations/ + README.md;
-- everything else -- tools/, wowheadScrape/, .omo/ -- is gitignored).
-- ---------------------------------------------------------------------------
local TRACKED = {}
local function load_tracked()
    -- NOTE: no `2>/dev/null` — on Windows cmd.exe that redirect targets a
    -- literal file and popen fails, silently emptying the tracked set.
    local pipe = io.popen("git ls-files")
    if not pipe then return end
    for line in pipe:lines() do
        local p = line:gsub("\\", "/"):gsub("^%./", "")
        if p ~= "" then TRACKED[p] = true end
    end
    pipe:close()
end

-- Self-provisioning roots: artifacts regenerated by tracked generators
-- before the suite runs (see tools/generate_sod_task1_action_map.lua ->
-- .omo/evidence/; EaxRotations/tools/generate_buff_debuff_verification.py
-- -> EaxRotations/tools/buff_debuff_full_verification.json).
local SELF_PROVISIONING_PREFIXES = {
    ".omo/",
    "EaxRotations/.omo/",
    "../.omo/",
}

local function is_self_provisioning(path)
    for _, prefix in ipairs(SELF_PROVISIONING_PREFIXES) do
        if path:sub(1, #prefix) == prefix then return true end
    end
    -- buff_debuff json is TRACKED (committed), so it needs no allowance;
    -- only .omo evidence is regenerated per-run.
    return false
end

-- Tests run with cwd at the repo root OR inside EaxRotations/ (the runners
-- chdir to match), so a literal may appear as "EaxRotations/...",
-- "classes/...", "main.lua", or "/tests/...". Canonicalize every spelling
-- to the repo-root-relative form before checking the tracked set.
local EAX_PREFIX = "EaxRotations/"
local function canonical(path)
    local p = path:gsub("\\", "/"):gsub("^%./", ""):gsub("^/", "")
    if p:sub(1, #EAX_PREFIX) ~= EAX_PREFIX then
        p = EAX_PREFIX .. p
    end
    return p
end

-- A path is trackable only if it lives under EaxRotations/ (the only
-- tracked subtree) and is actually listed by git ls-files.
local function is_tracked(path)
    return TRACKED[canonical(path)] or false
end

-- ---------------------------------------------------------------------------
-- Extract path-like string literals from a test file.
-- ---------------------------------------------------------------------------
-- Patterns that open a file with a string literal:
--   io.open("path"[, mode])        read_file("path")        open_first({...})
-- We also catch any string literal that LOOKS like a path (contains a slash
-- and a dot) so a new helper form cannot silently slip past.
local function extract_paths(content)
    local paths = {}
    local seen = {}
    local function add(p)
        if not p or p == "" then return end
        p = p:gsub("^%s+", ""):gsub("%s+$", "")
        if p:find("?") then return end              -- pattern, not a path
        if p:find("%%s") then return end            -- format string
        if p:sub(1, 1) == "%" then return end
        -- mode args ("rb", "r", "w", "wb") and non-path words: a path
        -- must contain a separator or a file-ish extension.
        local has_sep = p:find("/", 1, true) or p:find("\\", 1, true)
        local fileish = p:match("%.%w+$")
        if not has_sep and not fileish then return end
        -- normalize separators
        p = p:gsub("\\", "/")
        if not seen[p] then
            seen[p] = true
            paths[#paths + 1] = p
        end
    end

    -- Collect ALL string literals (double-quoted and single-quoted) so a new
    -- helper form (open_first, read, io.open, etc.) cannot slip past -- then
    -- let add() filter out non-path strings like mode args and labels.
    for literal in content:gmatch('"([^"\r\n]*)"') do
        add(literal)
    end
    for literal in content:gmatch("'([^'\r\n]*)'") do
        add(literal)
    end
    return paths
end

-- Does the path resolve to a real file on disk? Tests run with cwd at the
-- repo root OR inside EaxRotations/, so a literal may mean either a
-- repo-root path ("wowheadScrape/dbc_extract/wowsims.db", "../.omo/...")
-- or an EaxRotations-relative path ("shared/...", "main.lua"). Check all
-- spellings: raw (repo-root cwd), canonical (EaxRotations cwd), and the
-- ../-stripped form. canonical() is reused for the EaxRotations cwd reading
-- so normalization stays single-sourced.
local function exists_on_disk(path)
    local candidates = { path, canonical(path) }
    if path:sub(1, 3) == "../" then
        candidates[#candidates + 1] = path:sub(4)
    end
    for _, cand in ipairs(candidates) do
        local f = io.open(cand, "rb")
        if f then f:close() return true end
    end
    return false
end

-- ---------------------------------------------------------------------------
-- Main scan
-- ---------------------------------------------------------------------------
local function scan_dir(dir)
    local files = {}
    local function walk(d)
        for entry in lfs.dir(d) do
            if entry ~= "." and entry ~= ".." then
                local full = d .. "/" .. entry
                local attr = lfs.attributes(full)
                if attr then
                    if attr.mode == "file" and entry:match("%.lua$") then
                        files[#files + 1] = full
                    elseif attr.mode == "directory" then
                        walk(full)
                    end
                end
            end
        end
    end
    walk(dir)
    return files
end

local function main()
    if not lfs_ok or not lfs then
        -- Hard-fail (not SKIP): this probe is the enforcement gate for the
        -- gitignored-read gap class, so it must never silently disappear on a
        -- box without lfs. CI installs luafilesystem via luarocks.
        print("FAIL run_clean_checkout_probe: lfs unavailable (install luafilesystem) — cannot scan test files")
        return 1
    end
    load_tracked()

    local tracked_count = 0
    for _ in pairs(TRACKED) do tracked_count = tracked_count + 1 end
    if tracked_count == 0 then
        -- Fail-closed but legible: an empty tracked set means git ls-files
        -- yielded nothing (git not on PATH), so "untracked" would be
        -- meaningless and every existing file would false-flag.
        print("FAIL run_clean_checkout_probe: git ls-files returned no tracked files (git not on PATH?) — cannot verify the tracked set")
        return 1
    end

    local root = "EaxRotations/tests"
    local files = scan_dir(root)
    local untracked = {}
    local checked = 0

    for _, file in ipairs(files) do
        -- Skip the probe's own file: its comments legitimately name the
        -- gitignored paths it guards (e.g. the wowheadScrape docstring)
        -- and would self-flag.
        if file:find("run_clean_checkout_probe%.lua$") then
            checked = checked + 1
        else
            local f = io.open(file, "rb")
            if f then
                local content = f:read("*a") or ""
                f:close()
                for _, p in ipairs(extract_paths(content)) do
                    -- Skip package.path patterns and obviously non-path strings.
                    -- A path is only a clean-checkout risk if it actually exists
                    -- on disk (a nonexistent read would fail the test locally
                    -- too). If it exists but is untracked + not self-provisioning,
                    -- it passes locally and breaks in CI -- flag it.
                    if not p:find("%?") then
                        if exists_on_disk(p) and not is_tracked(p) and not is_self_provisioning(p) then
                            untracked[#untracked + 1] = { file = file, path = p }
                        end
                        checked = checked + 1
                    end
                end
            end
        end
    end

    if #untracked == 0 then
        print(string.format("clean-checkout probe: %d path literals checked across %d test files — all tracked or self-provisioning", checked, #files))
        print("[PASS] run_clean_checkout_probe")
        return 0
    end

    print(string.format("FAIL: %d untracked read target(s) found (pass locally, fail on clean checkout):", #untracked))
    for _, u in ipairs(untracked) do
        print(string.format("  [FAIL] %s  ->  %s", u.file, u.path))
    end
    print("  Fix: commit the file, point the test at a tracked file, or mark the path self-provisioning.")
    return 1
end

os.exit(main())
