-- run_forever_audit_tests.lua -- Audit _forever.lua rotation files for invalid spell IDs.
-- WHAT:  scans Forever rotation files for IDs that do not resolve in the
--        Forever spell-index bridge; scaffold mode until the beta DBC lands.
-- WHEN:  run manually, in the pre-commit gate, and in CI (verify_all).
-- WHY:   repo law: a spell exists only if the client DBC says so. Forever adds
--        NEW spells (Holy Strike, Seal of Fury, reworked racials) with
--        unknown-un-beta IDs; this audit is the gate that keeps guessed IDs
--        out of _forever files forever, mirroring run_wotlk_audit_tests.lua.
-- SAFETY: read-only text scan; --self-test has no filesystem writes; exits 2
--         on missing bridge, 1 on findings, 0 on pass. --check-bridge exits 1
--         when the loaded bridge looks like a fixture/synthetic (small count),
--         so a fixture-built bridge can never be mistaken for the real DBC.
--         LIVE-mode note: the bridge generated by the synthetic-DBC fixture
--         (build_tools/build_forever_bridge_fixture.py) does NOT carry
--         __forever_stub, so the audit enforces against it -- correct
--         fail-closed behavior: any real-era ID in a _forever file still
--         flags as VANILLA_ID_IN_FOREVER and only fixture IDs pass.

package.path = "EaxRotations/?.lua;EaxRotations/?/?.lua;EaxRotations/?/?/?.lua;./?.lua;" .. package.path

local bridge_ok, bridge = pcall(require, "shared/wowhead_data_bridge_spell_index_forever_sylvanas")
if not bridge_ok or not bridge then
    print("[ERROR] Could not load wowhead_data_bridge_spell_index_forever_sylvanas")
    print("        The stub bridge must exist; the real one replaces it on beta day")
    print("        (docs/forever/dbc_runbook.md).")
    os.exit(2)
end

-- Shape-tolerant: the stub returns the wrapper (M.spell_index_forever), the
-- generated bridge returns the bare table (same shape as the tbc/vanilla
-- spell-index modules). Accept both.
local forever_index = bridge.spell_index_forever or bridge
-- _forever spec files resolve Forever-new spells BY NAME through this mirror
-- (zero numeric literals in code). The audit pins its presence: spec files
-- require it, so a generator regression that drops it would break lanes at
-- runtime, not at audit time.
local forever_by_name = (type(bridge) == "table" and bridge.spell_index_by_name_forever) or {}
local STUB_MODE = bridge.__forever_stub == true

local bridge_entry_count = 0
for _ in pairs(forever_index) do bridge_entry_count = bridge_entry_count + 1 end

local valid_forever_ids = {}
for id in pairs(forever_index) do
    valid_forever_ids[id] = true
end

-- Cross-era membership for precise verdicts (a Forever file referencing a
-- vanilla ID must say VANILLA_ID_IN_FOREVER, not a bare INVALID).
local vanilla_ok, vanilla_bridge = pcall(require, "shared/wowhead_data_bridge_spell_index_vanilla_sylvanas")
local vanilla_index = (vanilla_ok and (vanilla_bridge.spell_index_vanilla or vanilla_bridge)) or {}
local valid_vanilla_ids = {}
for id in pairs(vanilla_index) do valid_vanilla_ids[id] = true end

-- ---------------------------------------------------------------------------
-- ID extraction (mirrors the wotlk audit's two patterns):
--   Pattern 1: define("Label", { 123, 456 }, "Label") / numeric 2nd arg
--   Pattern 2: pure numeric table literals { 123, 456 }
-- ---------------------------------------------------------------------------

local function extract_ids_from_line(line)
    if type(line) ~= "string" then return {} end
    local ids = {}
    local seen = {}
    local function collect(s)
        for num in s:gmatch("%d+") do
            local v = tonumber(num)
            if v and v >= 100 and v <= 999999 and not seen[v] then
                seen[v] = true
                ids[#ids + 1] = v
            end
        end
    end
    -- Pure numeric table literals. NOTE: gmatch with (%b{}) matches only the
    -- outermost balanced group at each position and resumes AFTER it, so
    -- NESTED numeric tables (e.g. `return { spell_ids = { 123 } }`) would be
    -- invisible to the scanner. Enumerate every balanced group instead.
    local opens = {}
    for i = 1, #line do
        local c = line:sub(i, i)
        if c == "{" then
            opens[#opens + 1] = i
        elseif c == "}" and #opens > 0 then
            local start = table.remove(opens)
            local inner = line:sub(start + 1, i - 1)
            if inner:match("^[%s,,%d]*$") then collect(inner) end
        end
    end
    -- define("X", 123, ...) single-numeric-arg form.
    for _, arg in ipairs({ line:match('define%s*%(%s*"[^"]*"%s*,%s*(%d+)') }) do
        collect(arg)
    end
    return ids
end

local function is_comment_line(line)
    return line:match("^%s*%-%-") ~= nil
end

local function classify_id(id)
    if valid_forever_ids[id] then return nil end
    if valid_vanilla_ids[id] then return "VANILLA_ID_IN_FOREVER" end
    return "INVALID"
end

local function scan_content(content)
    if type(content) ~= "string" then
        return { error = "content must be a string", hits = {} }
    end
    local hits = {}
    local line_no = 0
    for line in content:gmatch("[^\r\n]+") do
        line_no = line_no + 1
        if not is_comment_line(line) then
            for _, id in ipairs(extract_ids_from_line(line)) do
                local kind = classify_id(id)
                if kind then
                    hits[#hits + 1] = {
                        line = line_no,
                        id = id,
                        kind = kind,
                        snippet = (line:match("^%s*(.-)%s*$") or line):sub(1, 100),
                    }
                end
            end
        end
    end
    return { found = #hits > 0, hits = hits }
end

local function read_file(path)
    local f = io.open(path, "rb")
    if not f then return nil end
    local content = f:read("*a")
    f:close()
    return content
end

local function scan_file(filepath)
    local content = read_file(filepath)
    if not content then return { skipped = true, hits = {} } end
    return scan_content(content)
end

local function find_forever_files()
    local files = {}
    -- Class spec deltas: classes/<class>/<spec>_forever.lua
    -- Primary: GNU find (works under the sh-based pre-commit hook + CI).
    -- Fallback: `git ls-files EaxRotations/classes` filtered in Lua -- works
    -- on Windows where cmd.exe resolves `find` to Windows find.exe. Plain
    -- pathspec (no glob), because git's default `*` does not cross `/` and
    -- the class dirs are one level below classes/. No stderr redirects:
    -- cmd.exe cannot parse 2>/dev/null and popen captures stdout only.
    -- Untracked in-progress files are invisible to the fallback -- commit
    -- before auditing (clean-checkout probe's tracked-files contract).
    local pipe = io.popen('find EaxRotations/classes -name "*_forever.lua"')
    if pipe then
        for line in pipe:lines() do
            if line:match("_forever%.lua$") then
                files[#files + 1] = line:gsub("\\", "/")
            end
        end
        pipe:close()
    end
    if #files == 0 then
        local gp = io.popen("git ls-files EaxRotations/classes")
        if gp then
            for line in gp:lines() do
                if line:match("_forever%.lua$") then
                    files[#files + 1] = line:gsub("\\", "/")
                end
            end
            gp:close()
        end
    end
    table.sort(files)
    return files
end

-- ---------------------------------------------------------------------------
-- Self-tests: the scanner must PROVE it fires before it is allowed to pass.
-- Mirrors the wotlk audit's --self-test contract (a dropped pin / a scanner
-- that silently matches nothing must hard-fail).
-- ---------------------------------------------------------------------------

local function run_self_tests()
    local function expect(actual, expected, label)
        if actual ~= expected then
            error(label .. ": expected " .. tostring(expected) .. ", got " .. tostring(actual), 2)
        end
    end

    expect(#extract_ids_from_line(nil), 0, "malformed nil line")
    expect(scan_content(nil).error, "content must be a string", "malformed content")
    expect(scan_file("__missing_forever_audit_fixture__.lua").skipped, true, "missing fixture")

    -- Comment lines must never fire.
    local comment_scan = scan_content('-- define("SealOfFury", { 999999 }, "SealOfFury")')
    expect(#comment_scan.hits, 0, "comment lines are exempt")

    -- Unresolvable ids each yield a hit (deduped when equal). The probe ids
    -- resolve in NEITHER bridge in EITHER mode: 12345/12344 are gaps in both
    -- the vanilla and the Forever indexes, so this pin holds in stub mode
    -- and in live mode alike (a live-resolving id such as Holy Strike 678,
    -- or a vanilla-indexed id such as 12346 "Awaken the Soulflayer", must NOT
    -- be used here -- they yield a hit only while the bridge is a stub, or
    -- the vanilla-leak verdict instead of INVALID).
    local scan = scan_content('define("SealOfFury", { 12345, 12345, 12344 }, "SealOfFury")')
    expect(#scan.hits, 2, "scan dedupes and fires")
    expect(scan.hits[1].id, 12345, "first hit id")
    expect(scan.hits[2].kind, "INVALID", "unknown id classifies INVALID")

    -- A sub-100 number is not a spell id (rank literals etc.).
    local small = scan_content('local rank = 42')
    -- Nested numeric tables MUST be scanned: gmatch(%b{}) only ever sees
    -- the outermost balanced group, so a return-shape table hides its ids
    -- from a naive scanner (found live during the 2026-09-16 beta-day
    -- rehearsal -- a scratch file with a nested bogus id passed silently).
    local nested = scan_content('return { spell_ids = { 432100, 99999999 } }')
    expect(#nested.hits, 1, "nested numeric table is scanned (99999999 sits above the plausibility ceiling)")
    expect(nested.hits[1].id, 432100, "nested hit id")
    local nested2 = scan_content('local T = { a = { 24601 } }')
    expect(#nested2.hits, 1, "doubly-nested numeric table is scanned")

    expect(#small.hits, 0, "small numerics exempt")

    -- Vanilla-known IDs still report the precise era-leak verdict in code
    -- (bridge tables are data, and data tables are scanned only in real
    -- _forever files; the scanner itself just classifies). The probe must be
    -- vanilla-indexed but absent from the rank-1-baselined forever index in
    -- EVERY mode: 143 (Fireball non-baseline rank) qualifies, while 25898
    -- (live-resolving since the beta DBC landed) does not.
    expect(classify_id(143), "VANILLA_ID_IN_FOREVER", "vanilla id leaks precise verdict (143 = Fireball non-baseline rank)")

    -- By-name resolution contract (zero-literal spec design): the bridge
    -- module MUST expose the name mirror (spec files require it), and the
    -- audit's lane-dormancy rule -- a nil name lookup never fabricates an ID.
    expect(type(bridge.spell_index_by_name_forever), "table", "bridge exposes spell_index_by_name_forever (spec files require it)")
    expect(forever_by_name["__NonexistentSpell__"], nil, "missing name resolves nil (lane stays dormant)")

    -- Maxrank/buff mirror contract (beta-day DBC landing): cast lanes resolve
    -- max rank, buff lanes resolve the proc buff; both mirrors must exist and
    -- carry the DBC-proven ids (spot-pinned so a regeneration drift fails
    -- loudly instead of silently recasting lanes at the wrong rank).
    expect(type(bridge.spell_maxrank_by_name_forever), "table", "bridge exposes spell_maxrank_by_name_forever (cast lanes require it)")
    expect(type(bridge.spell_buff_by_name_forever), "table", "bridge exposes spell_buff_by_name_forever (buff lanes require it)")
    local maxrank = bridge.spell_maxrank_by_name_forever
    expect(maxrank["Holy Strike"], 10333, "maxrank Holy Strike is the 60 max (not the 678 baseline)")
    expect(maxrank["Light's Vigil"], 1311595, "maxrank Light's Vigil is the 60 cast row (not the 1310909 buff row)")
    expect(maxrank["Lava Burst"], 1238300, "maxrank Lava Burst is the 60 nuke (not the 408490 rank)")
    expect(maxrank["Fire Nova"], 408345, "maxrank Fire Nova is the trainer-taught totem-detonating cast (not the internal 11307 damage row)")
    expect(maxrank["Berserk"], 417141, "maxrank Berserk is the druid form-branched row (not the warrior 23397 cross-class lowest id)")
    expect(maxrank["Arcane Blast"], 1239700, "maxrank Arcane Blast is the 60 nuke (not the 400573 aura row)")
    expect(maxrank["Penance"], 1316995, "maxrank Penance is the dual-mode cast row (not the internal 1316991 heal channel)")
    local buffmap = bridge.spell_buff_by_name_forever
    expect(buffmap["Missile Barrage"], 400589, "buff Missile Barrage is the proc (not the 400588 talent)")
    expect(buffmap["Maelstrom Weapon"], 408505, "buff Maelstrom Weapon is the buff text row (not the 408498 talent)")
    expect(buffmap["Hot Streak"], 400625, "buff Hot Streak is the Forever stacking proc (not the legacy 48108 row)")
    expect(buffmap["Winter's Chill"], 12579, "buff Winter's Chill is the applied debuff row (not the 11180 talent)")
    expect(buffmap["Eclipse"], 408255, "buff Eclipse is the charge buff row (not the 408248 talent text)")
    expect(buffmap["Decimation"], 440873, "buff Decimation is the Soul Fire proc row (not the 440870 talent text)")
    -- Class-less aura rows (builder CLASS_LESS_BUFF_NAMES): the Shadow and
    -- Flame windows are applied by 426316 but carry no class row themselves.
    expect(buffmap["Shadow"], 1293816, "buff Shadow is the Shadow and Flame shadow window row (class-less, pinned)")
    expect(buffmap["Flame"], 426311, "buff Flame is the Shadow and Flame fire window row (class-less, pinned)")
    expect(buffmap["Divine Aegis"], 431624, "buff Divine Aegis is the applied absorb shield (not the 431622 talent text)")
    expect(buffmap["Thousand Cuts"], 1310723, "buff Thousand Cuts is the stack buff row (not the 1310721 talent text)")
    expect(buffmap["Cutthroat"], 462707, "buff Cutthroat is the stealth-free Ambush proc (not the 424980 grant row)")
    expect(buffmap["Prayer of Mending"], 1240849, "buff Prayer of Mending is the @60 applied aura (not the 401859 cast row)")
    expect(buffmap["Infusion of Light"], 437063, "buff Infusion of Light is the live 15s Holy Light row (not the orphaned TBC 53672, which nothing in this build applies)")
    expect(buffmap["Wake of Fire"], 1312934, "buff Wake of Fire is the 20s Fire Blast window (not the 11078 ability row, which is never on the player as an aura)")
    expect(buffmap["Arcane Blast"], 400573, "buff Arcane Blast keeps the stack-aura baseline")

    print("  self-test: scanner fires, comments exempt, dedupe works, verdicts precise")
end

-- ---------------------------------------------------------------------------
-- Main
-- ---------------------------------------------------------------------------

if arg and arg[1] == "--self-test" then
    local ok, err = pcall(run_self_tests)
    if not ok then
        print("[FAIL] forever audit self-test: " .. tostring(err))
        os.exit(2)
    end
    print("[PASS] forever audit self-test (scanner fires on synthetic violations)")
    os.exit(0)
end

if arg and arg[1] == "--check-bridge" then
    if STUB_MODE then
        print("FAIL: bridge is still the STUB (scaffold mode)")
        os.exit(2)
    end
    print(string.format("Forever bridge: %d entries (live mode)", bridge_entry_count))
    if bridge_entry_count < 1000 then
        print("  WARNING: fewer than 1000 entries -- this looks like the synthetic")
        print("  fixture bridge (build_forever_bridge_fixture.py), not the real beta")
        print("  DBC. The audit still enforces fail-closed against it, but the real")
        print("  extraction must land on beta day (docs/forever/dbc_runbook.md step 1).")
        os.exit(1)
    end
    print("[PASS] Forever bridge is live and populated")
    os.exit(0)
end

if STUB_MODE then
    -- Scaffold mode: no DBC yet, so a live scan would flag nothing meaningful.
    -- Prove the scanner still fires (the self-test above ran only under
    -- --self-test; run the core probes here so scaffold mode is not vacuous).
    local ok, err = pcall(run_self_tests)
    if not ok then
        print("[FAIL] forever audit scaffold probes: " .. tostring(err))
        os.exit(2)
    end
    print("Forever audit: SCAFFOLD MODE (beta DBC not yet extracted — docs/forever/dbc_runbook.md)")
    print("  scanner self-probes: PASS")
    print("  No _forever spec files exist yet; the audit enforces live scans once")
    print("  the bridge stub is replaced (docs/forever/dbc_runbook.md step 3-5).")
    os.exit(0)
end

local files = find_forever_files()
local invalid = 0
local findings = {}
for _, f in ipairs(files) do
    local result = scan_file(f)
    if result.hits and #result.hits > 0 then
        findings[#findings + 1] = { file = f, hits = result.hits }
        invalid = invalid + #result.hits
    end
end

print(string.format("Forever audit: %d _forever file(s) scanned, %d bridge entries", #files, bridge_entry_count))
if bridge_entry_count < 1000 then
    print("  NOTE: bridge entry count is small -- synthetic fixture bridge presumed")
    print("  (beta client not yet extracted). Enforcement stays fail-closed.")
end
if #findings > 0 then
    print(string.format("Invalid: %d", invalid))
    for _, f in ipairs(findings) do
        for _, hit in ipairs(f.hits) do
            print(string.format("    %s  line %d: id %d [%s]  %s", f.file, hit.line, hit.id, hit.kind, hit.snippet))
        end
    end
    print("  INVALID: no Forever-bridge or vanilla classification exists for the ID.")
    print("  VANILLA_ID_IN_FOREVER: a vanilla-era ID appears outside an explicit")
    print("  era-shared pin. Add a pinned entry with DBC evidence if the ID is")
    print("  genuinely era-shared (see run_wotlk_audit_tests.lua for the pin shape).")
    os.exit(1)
end

print("Invalid: 0")
print("  All _forever spell IDs resolve in the Forever bridge (or are pinned).")
os.exit(0)
