-- Readability notes:
--   What: regression checks for spell ID tables corrected against TBC spell databases.
--   When: run with lua from the repository root.
--   Why: prevents known bad IDs from drifting back into castable spell rank lists.
--   Safety: file-content assertions only; no game client or online service is called.

-- Decision notes:
--   Online spell DB checks are intentionally not part of the test run because CI and local
--   syntax checks must work without network access.
--   These assertions pin only confirmed bad IDs and corrected rank lists, not every spell in
--   the project, so legitimate future rank-table updates remain easy to review.

local function assert_true(v, label)
    if not v then error(label or "assert_true failed", 2) end
end

local function assert_not(v, label)
    if v then error(label or "assert_not failed", 2) end
end

local function read_file(path)
    local f = assert(io.open(path, "rb"))
    local data = f:read("*a")
    f:close()
    return data
end

local function contains(data, text)
    return data:find(text, 1, true) ~= nil
end

local function before(data, first, second)
    local a = data:find(first, 1, true)
    local b = data:find(second, 1, true)
    return a ~= nil and b ~= nil and a < b
end

local mage = read_file("EaxRotations/classes/mage/class_sylvanas.lua")
assert_true(contains(mage, 'ArcaneBlast = NS.spell_action({ 30451 }, "ArcaneBlast")'), "Arcane Blast should not use Pyroblast ID 33938")
assert_true(contains(mage, 'Blizzard = NS.spell_action({ 27085, 10187, 10186, 10185, 8427, 6141, 10 }, "Blizzard")'), "Blizzard ranks should be real Blizzard IDs")
assert_true(contains(mage, 'Flamestrike = NS.spell_action({ 27086, 10216, 10215, 8423, 8422, 2120 }, "Flamestrike")'), "Flamestrike ranks should use verified TBC IDs")
assert_true(contains(mage, 'FlamestrikeRank6 = NS.spell_action({ 10216 }, "FlamestrikeRank6")'), "Fire AoE should be able to pair highest Flamestrike with rank 6")
assert_true(contains(mage, 'Frostbolt = NS.spell_action({ 27072, 25304'), "Frostbolt should use 27072, not Cone of Cold 27087")
assert_not(contains(mage, "10198"), "unresolved Fire Blast rank placeholder 10198 should not be in mage table")

local druid = read_file("EaxRotations/classes/druid/class_sylvanas.lua")
assert_true(contains(druid, 'Cower = NS.spell_action({ 27004, 9892, 8998 }, "Cower")'), "Cower should not include Shoot ID 8997")
assert_true(contains(druid, 'DemoralizingRoar = NS.spell_action({ 26998, 9898, 9747, 9490, 1735, 99 }, "DemoralizingRoar")'), "Druid Demoralizing Roar ranks should be druid roar IDs")
assert_true(contains(druid, 'FaerieFireFeral = NS.spell_action({ 27011, 17392, 17391, 17390, 16857 }, "FaerieFireFeral")'), "Bear should use feral Faerie Fire ranks while shapeshifted")
assert_true(contains(druid, 'Shred = NS.spell_action({ 27002, 27001, 9830, 9829, 8992, 6800, 5221 }, "Shred")'), "Shred should use verified TBC rank IDs")
assert_true(contains(druid, 'MangleCat = NS.spell_action({ 33983, 33982, 33876 }, "MangleCat")'), "Mangle Cat ranks should be newest-to-oldest")
assert_true(contains(druid, 'Prowl = NS.spell_action({ 9913, 6783, 5215 }, "Prowl")'), "Prowl should include all TBC ranks")
assert_true(contains(druid, 'ForceOfNature = NS.spell_action({ 33831 }, "ForceOfNature")'), "Balance should expose Force of Nature")
assert_true(contains(druid, 'Swiftmend = NS.spell_action({ 18562 }, "Swiftmend")'), "Resto should expose Swiftmend")
assert_true(contains(druid, 'NaturesSwiftness = NS.spell_action({ 17116 }, "NaturesSwiftness")'), "Resto should expose Nature's Swiftness")
assert_not(contains(druid, "25275"), "Warrior Intercept ID should not be in druid table")

local druid_cat = read_file("EaxRotations/classes/druid/cat_sylvanas.lua")
assert_true(contains(druid_cat, "9913, 6783, 5215"), "cat stealth checks should include all Prowl ranks")
assert_not(contains(druid_cat, "12294"), "Mortal Strike should not suppress cat Mangle maintenance")

local druid_bear = read_file("EaxRotations/classes/druid/bear_sylvanas.lua")
local druid_balance = read_file("EaxRotations/classes/druid/balance_sylvanas.lua")
local druid_caster = read_file("EaxRotations/classes/druid/caster_sylvanas.lua")
local druid_healing = read_file("EaxRotations/classes/druid/healing_sylvanas.lua")
local druid_resto = read_file("EaxRotations/classes/druid/resto_sylvanas.lua")
assert_true(contains(druid_bear, 'name = "DemoralizingRoar"') and contains(druid_bear, "cooldown = 25"), "bear Demo Roar should be throttled")
assert_true(contains(druid_bear, 'name = "FaerieFireFeral"') and contains(druid_bear, "FaerieFireFeral"), "bear should maintain feral Faerie Fire")
assert_true(contains(druid_bear, 'name = "Lacerate"') and contains(druid_bear, "min_debuff_stacks = 5") and contains(druid_bear, "max_enemy_count = 2"), "bear Lacerate should build/refresh stacks mostly for single-target tanking")
assert_true(before(druid_bear, 'name = "SwipeAoE"', 'name = "MangleBear"'), "bear should prioritize Swipe on 3+ target packs")
assert_true(contains(druid_balance, 'name = "Hurricane"') and contains(druid_balance, 'position = "target"') and contains(druid_balance, "cooldown = 60"), "Hurricane should be ground-position cast and cooldown-gated")
assert_true(contains(druid_balance, 'name = "ForceOfNature"') and contains(druid_balance, 'setting = "use_cooldowns"') and contains(druid_balance, "cooldown = 180"), "Balance should use Force of Nature as a cooldown")
assert_true(contains(druid_balance, 'name = "Wrath"') and contains(druid_balance, "not_moving = true"), "balance Wrath should not be cast while moving")
assert_true(contains(druid_caster, 'name = "Wrath"') and contains(druid_caster, "not_moving = true"), "caster Wrath should not be cast while moving")
assert_true(contains(druid_resto, 'name = "SwiftmendEmergency"') and contains(druid_resto, "has_rejuvenation") and contains(druid_resto, "has_regrowth"), "Resto should use Swiftmend only when a consumable HoT is active")
assert_true(contains(druid_resto, 'name = "NaturesSwiftness"') and contains(druid_resto, "resto_ns_hp"), "Resto should expose Nature's Swiftness emergency healing")
assert_true(contains(druid_healing, "LIFEBLOOM_MAX_STACKS = 3") and contains(druid_healing, "lifebloom_stacks") and contains(druid_healing, "lifebloom_remains"), "Resto healing should track Lifebloom stacks and refresh timing")
assert_true(contains(druid_healing, "maintain tank Lifebloom roll") and contains(druid_healing, "LIFEBLOOM_REFRESH_REMAINS"), "Resto healing should roll Lifebloom on tanks instead of only casting one stack")

local shaman = read_file("EaxRotations/classes/shaman/class_sylvanas.lua")
local shaman_enhancement = read_file("EaxRotations/classes/shaman/enhancement_sylvanas.lua")
local shaman_elemental = read_file("EaxRotations/classes/shaman/elemental_sylvanas.lua")
local shaman_restoration = read_file("EaxRotations/classes/shaman/restoration_sylvanas.lua")
local shaman_schema = read_file("EaxRotations/classes/shaman/schema_sylvanas.lua")
assert_true(contains(shaman, 'NaturesSwiftness = NS.spell_action({ 16188 }, "NaturesSwiftness")'), "Shaman Nature's Swiftness should not include druid talent ID")
assert_true(contains(shaman, 'Stormstrike = NS.spell_action({ 17364 }, "Stormstrike")'), "Stormstrike has one TBC cast spell ID")
assert_true(contains(shaman, 'FlameShock = NS.spell_action({ 25457, 29228, 10448, 10447, 8053, 8052, 8050 }, "FlameShock")'), "Flame Shock ranks should be newest-to-oldest")
assert_true(contains(shaman, 'WindfuryTotem = NS.spell_action({ 25587, 10614, 10613, 8512 }, "WindfuryTotem")'), "Enhancement totem support should use verified Windfury Totem cast IDs")
assert_true(contains(shaman, 'GraceOfAirTotem = NS.spell_action({ 25359, 10627, 8835 }, "GraceOfAirTotem")'), "Enhancement totem twisting should use Grace of Air Totem cast IDs, not aura IDs")
assert_true(contains(shaman, 'StrengthOfEarthTotem = NS.spell_action({ 25528, 10442, 8161, 8160, 8075 }, "StrengthOfEarthTotem")'), "Enhancement managed totems should expose Strength of Earth")
assert_true(contains(shaman, 'ManaSpringTotem = NS.spell_action({ 25570, 10497, 10496, 10495, 5675 }, "ManaSpringTotem")'), "Enhancement managed totems should expose Mana Spring")
assert_true(contains(shaman, 'ManaTideTotem = NS.spell_action({ 16190 }, "ManaTideTotem")'), "Restoration should expose Mana Tide Totem")
assert_true(contains(shaman, 'WaterShield = NS.spell_action({ 33736, 24398 }, "WaterShield")'), "Water Shield should use castable TBC IDs")
assert_not(contains(shaman, "17423"), "Stormstrike placeholder 17423 should not return")
assert_true(contains(shaman_enhancement, 'name = "Stormstrike"') and contains(shaman_enhancement, "cooldown = 10"), "Stormstrike should be cooldown-gated")
assert_true(contains(shaman_enhancement, 'name = "EarthShock"') and contains(shaman_enhancement, "cooldown = 6"), "enhancement shock should be cooldown-gated")
assert_true(before(shaman_enhancement, 'name = "WindfuryTotemTwist"', 'name = "Stormstrike"') and contains(shaman_enhancement, "AIR_TWIST_HOLD_MS = 9000"), "Enhancement should support optional Windfury -> Grace of Air totem twisting")
assert_true(contains(shaman_schema, 'key = "enhancement_totem_twisting"') and contains(shaman_schema, "default = false"), "Enhancement totem twisting should be explicitly user-enabled")
assert_true(contains(shaman_enhancement, 'name = "Bloodlust"') and contains(shaman_enhancement, 'setting = "use_cooldowns"') and contains(shaman_enhancement, "cooldown = 600"), "Enhancement should expose Bloodlust behind the cooldown toggle")
assert_true(contains(shaman_elemental, 'name = "ChainLightning"') and contains(shaman_elemental, "cooldown = 6"), "Chain Lightning should be cooldown-gated")
assert_true(before(shaman_elemental, 'name = "ChainLightning"', 'name = "FlameShockMoving"') and contains(shaman_elemental, 'name = "EarthShockMoving"'), "Elemental should use shocks as movement fillers after the hard-cast loop")
assert_true(contains(shaman_elemental, 'name = "Bloodlust"') and contains(shaman_elemental, 'setting = "use_cooldowns"') and contains(shaman_elemental, "cooldown = 600"), "Elemental should expose Bloodlust behind the cooldown toggle")
assert_true(contains(shaman_restoration, 'name = "Bloodlust"') and contains(shaman_restoration, "all_members_above_hp"), "Restoration should only Bloodlust when the group is stable")
assert_true(contains(shaman_restoration, 'name = "ManaTideTotem"') and contains(shaman_restoration, "restoration_mana_tide_pct") and contains(shaman_restoration, "expected_cooldown = 300"), "Restoration should use Mana Tide as a stable-group mana cooldown")

local priest = read_file("EaxRotations/classes/priest/class_sylvanas.lua")
local priest_discipline = read_file("EaxRotations/classes/priest/discipline_sylvanas.lua")
local priest_shadow = read_file("EaxRotations/classes/priest/shadow_sylvanas.lua")
assert_true(contains(priest, 'BindingHeal = NS.spell_action({ 32546 }, "BindingHeal")'), "Binding Heal should not include Symbol of Hope")
assert_true(contains(priest, 'CircleofHealing = NS.spell_action({ 34866, 34865, 34864, 34863, 34861 }, "CircleofHealing")'), "Circle of Healing should exclude missing 34862")
assert_true(contains(priest, 'PrayerOfHealing = NS.spell_action({ 25308, 25316, 10961, 10960, 996, 596 }, "PrayerOfHealing")'), "Prayer of Healing should prefer the level 68 rank before level 60 book rank")
assert_true(contains(priest, 'Shadowfiend = NS.spell_action({ 34433 }, "Shadowfiend")'), "Shadowfiend should be available for Shadow mana recovery")
assert_not(contains(priest, "25386"), "missing Holy Fire ID 25386 should not return")
assert_true(contains(priest_discipline, 'name = "EmergencyPowerWordShield"') and contains(priest_discipline, "has_weakened_soul"), "Discipline PW:S should respect Weakened Soul on group targets")
assert_true(contains(priest_discipline, 'name = "PrayerOfMendingTank"') and contains(priest_discipline, "Healing.scan_healing_targets"), "Discipline should use group healing scans instead of self-only healing")
assert_true(contains(priest_discipline, 'name = "RenewTank"') and contains(priest_discipline, "has_renew"), "Discipline Renew should not recast while active")
assert_true(contains(priest_shadow, 'name = "Shadowfiend"') and contains(priest_shadow, "(context.mana_pct or 100) > 55") and contains(priest_shadow, "expected_cooldown = 300"), "Shadow should use Shadowfiend as mana recovery")
assert_true(contains(priest_shadow, 'name = "InnerFocusMindBlast"') and contains(priest_shadow, "s.mb_ready"), "Shadow should pair Inner Focus with a ready Mind Blast")
assert_true(contains(priest_shadow, 'name = "MindBlast"') and contains(priest_shadow, "expected_cooldown = 5.5"), "Shadow should throttle Mind Blast close to the improved TBC cooldown")
assert_true(contains(priest_shadow, 'name = "ShadowWordDeath"') and contains(priest_shadow, "(context.hp or 100) < 80") and contains(priest_shadow, "expected_cooldown = 12"), "Shadow Word: Death should be a safe cooldown spell, not execute-only")
assert_true(contains(priest_shadow, 'name = "MindFlay"') and contains(priest_shadow, "context.is_casting or context.is_channeling"), "Mind Flay should not restart while already casting/channeling")
assert_true(contains(priest_shadow, "shared/mf_tick_compute_sylvanas") and contains(priest_shadow, "should_clip_mf") and contains(priest_shadow, "mf_ticks"), "Shadow should use Mind Flay tick state before clipping channels")

local warlock = read_file("EaxRotations/classes/warlock/class_sylvanas.lua")
local warlock_affliction = read_file("EaxRotations/classes/warlock/affliction_sylvanas.lua")
assert_true(contains(warlock, 'Conflagrate = NS.spell_action({ 17962 }, "Conflagrate")'), "Conflagrate should use talent cast ID only")
assert_true(contains(warlock, 'CurseOfDoom = NS.spell_action({ 30910, 603 }, "CurseOfDoom")'), "Warlock long-fight curse should expose verified Curse of Doom ranks")
assert_true(contains(warlock, 'Shadowburn = NS.spell_action({ 30546, 27263, 18871, 18870, 18869, 18868, 18867, 17877 }, "Shadowburn")'), "Shadowburn should use warlock Shadowburn ranks")
assert_not(contains(warlock, "30455"), "Mage Ice Lance ID should not be in warlock table")
assert_true(contains(warlock_affliction, 'name = "LifeTap"') and contains(warlock_affliction, "max_mana = 65"), "Life Tap should not fire when mana is already healthy")
assert_true(before(warlock_affliction, 'name = "CurseOfDoom"', 'name = "CurseOfAgony"') and contains(warlock_affliction, "require_ttd = true") and contains(warlock_affliction, "target_not_player = true"), "Affliction should prefer Curse of Doom only on known long-lived non-player targets")

local warlock_destro = read_file("EaxRotations/classes/warlock/destruction_sylvanas.lua")
local warlock_demo = read_file("EaxRotations/classes/warlock/demonology_sylvanas.lua")
assert_not(contains(warlock_destro, "11664") or contains(warlock_destro, "11663"), "destruction Immolate debuff list should use verified IDs")
assert_not(contains(warlock_demo, "11664") or contains(warlock_demo, "11663"), "demonology Immolate debuff list should use verified IDs")
assert_true(contains(warlock_destro, 'name = "Conflagrate"') and contains(warlock_destro, "moving = true") and contains(warlock_destro, "cooldown = 10"), "Conflagrate should be reserved for movement and use its TBC 10s cooldown")
assert_true(contains(warlock_destro, 'name = "Shadowburn"') and contains(warlock_destro, "cooldown = 15"), "Shadowburn should use its TBC 15s cooldown")
assert_true(before(warlock_destro, 'name = "CurseOfDoom"', 'name = "Immolate"'), "Destruction should apply long-fight Curse of Doom before normal filler setup")
assert_true(before(warlock_demo, 'name = "CurseOfDoom"', 'name = "Corruption"'), "Demonology should apply long-fight Curse of Doom before normal filler setup")

local paladin = read_file("EaxRotations/classes/paladin/class_sylvanas.lua")
local paladin_prot = read_file("EaxRotations/classes/paladin/protection_sylvanas.lua")
local paladin_ret = read_file("EaxRotations/classes/paladin/retribution_sylvanas.lua")
assert_true(contains(paladin, 'LayOnHands = NS.spell_action({ 27154, 10310, 2800, 633 }, "LayOnHands")'), "Lay on Hands should use TBC paladin ranks")
assert_true(contains(paladin, 'AvengingWrath = NS.spell_action({ 31884 }, "AvengingWrath")'), "Ret should expose Avenging Wrath")
assert_true(contains(paladin, 'Exorcism = NS.spell_action({ 27138, 10314, 10313, 10312, 5615, 5614, 879 }, "Exorcism")'), "Paladin Exorcism should use verified TBC ranks")
assert_true(contains(paladin, 'SealBlood = NS.spell_action({ 31892 }, "SealBlood")'), "Ret should expose Seal of Blood for TBC seal twisting")
assert_true(contains(paladin, 'SealCommandRank1 = NS.spell_action({ 20375 }, "SealCommandRank1")'), "Ret seal twisting should prep Rank 1 Seal of Command")
assert_true(contains(paladin_prot, 'name = "HolyShield"') and contains(paladin_prot, "cooldown = 10"), "Holy Shield should be cooldown-gated")
assert_true(contains(paladin_prot, 'name = "Consecration"') and contains(paladin_prot, "cooldown = 8"), "prot Consecration should be cooldown-gated")
assert_true(contains(paladin_prot, 'name = "Exorcism"') and contains(paladin_prot, "creature_types = DEMON_OR_UNDEAD"), "prot Exorcism should only run on undead/demon targets")
assert_true(before(paladin_prot, 'name = "SealRighteousness"', 'name = "Judgement"') and contains(paladin_prot, 'cooldown = 10'), "prot should seal before Judgement and cooldown-gate Judgement")
assert_true(contains(paladin_ret, 'name = "Consecration"') and contains(paladin_ret, "cooldown = 8"), "ret Consecration should be cooldown-gated")
assert_true(contains(paladin_ret, 'name = "Exorcism"') and contains(paladin_ret, "creature_types = DEMON_OR_UNDEAD"), "ret Exorcism should only run on undead/demon targets")
assert_true(contains(paladin_ret, 'name = "CrusaderStrike"') and contains(paladin_ret, "cooldown = 6"), "Crusader Strike should be cooldown-gated")
assert_true(contains(paladin_ret, 'name = "SealTwistBlood"') and contains(paladin_ret, "TWIST_WINDOW = 0.45"), "Ret should implement a swing-timed Seal of Command -> Blood twist")
assert_true(before(paladin_ret, 'name = "SealTwistBlood"', 'name = "CrusaderStrike"'), "Ret should prioritize twist-window seals over normal strikes")
assert_true(contains(paladin_ret, 'name = "SealTwistPrepCommand"') and contains(paladin_ret, "SealCommandRank1"), "Ret should prep Rank 1 Seal of Command before the twist window")

local warrior = read_file("EaxRotations/classes/warrior/class_sylvanas.lua")
local warrior_arms = read_file("EaxRotations/classes/warrior/arms_sylvanas.lua")
local warrior_fury = read_file("EaxRotations/classes/warrior/fury_sylvanas.lua")
assert_true(contains(warrior, 'Devastate = NS.spell_action({ 30022, 30016, 20243 }, "Devastate")'), "Devastate should not include First Aid ID 30020")
assert_true(contains(warrior, 'Revenge = NS.spell_action({ 30357, 25269, 25288, 11601, 11600, 7379, 6574, 6572 }, "Revenge")'), "Revenge should use warrior Revenge ranks")
assert_true(contains(warrior, 'CommandingShout = NS.spell_action({ 469 }, "CommandingShout")'), "Commanding Shout is a TBC Protection talent")
assert_true(contains(warrior, 'Overpower = NS.spell_action({ 11585, 7887, 7384 }, "Overpower")'), "Kebab Overpower branch needs castable TBC ranks")
assert_true(contains(warrior, 'VictoryRush = NS.spell_action({ 34428 }, "VictoryRush")'), "Warrior spell table should include Victory Rush")
assert_true(contains(warrior, 'BattleShout = NS.spell_action({ 2048, 25289, 11551, 11550, 11549, 6192, 5242, 6673 }, "BattleShout")'), "Battle Shout should prefer the level 69 rank")
assert_true(contains(warrior, 'Bloodthirst = NS.spell_action({ 30335, 25251, 23894, 23893, 23892, 23881 }, "Bloodthirst")'), "Bloodthirst ranks should be newest-to-oldest")
assert_true(contains(warrior_arms, 'name = "MortalStrike"') and contains(warrior_arms, "cooldown = 6"), "Mortal Strike should be cooldown-gated")
assert_true(contains(warrior_fury, 'name = "Bloodthirst"') and contains(warrior_fury, "cooldown = 6"), "Bloodthirst should be cooldown-gated")
assert_true(contains(warrior_fury, 'name = "Whirlwind"') and contains(warrior_fury, "cooldown = 10"), "Whirlwind should be cooldown-gated")
assert_true(before(warrior_fury, 'name = "Bloodthirst"', 'name = "Execute"') and before(warrior_fury, 'name = "Whirlwind"', 'name = "Execute"'), "Fury should keep BT/WW above Execute")
assert_true(before(warrior_arms, 'name = "MortalStrike"', 'name = "Execute"'), "Arms should keep Mortal Strike above Execute")

local warrior_prot = read_file("EaxRotations/classes/warrior/protection_sylvanas.lua")
assert_true(contains(warrior_prot, 'name = "DemoralizingShout"') and contains(warrior_prot, "cooldown = 25"), "prot Demo Shout should be throttled")
assert_true(contains(warrior_prot, 'name = "ShieldSlam"') and contains(warrior_prot, "cooldown = 6"), "Shield Slam should be cooldown-gated")
assert_true(contains(warrior_prot, 'name = "ThunderClap"') and contains(warrior_prot, "cooldown = 4"), "Thunder Clap should be cooldown-gated")

local mage_fire = read_file("EaxRotations/classes/mage/fire_sylvanas.lua")
local mage_frost = read_file("EaxRotations/classes/mage/frost_sylvanas.lua")
local core_runtime = read_file("EaxRotations/core_sylvanas.lua")
assert_true(contains(mage_fire, 'position = "target"') and contains(mage_fire, "not_moving = true"), "fire Blizzard should be position-cast and movement-gated")
assert_true(contains(mage_fire, 'debuff = { 22959 }') and contains(mage_fire, "min_debuff_stacks = 5"), "fire Scorch should build and maintain 5-stack Fire Vulnerability")
assert_true(before(mage_fire, 'name = "Flamestrike"', 'name = "Blizzard"') and contains(mage_fire, "FlamestrikeRank6"), "fire AoE should Flamestrike before Blizzard and include rank 6 pairing")
assert_true(contains(mage_frost, 'position = "target"') and contains(mage_frost, "not_moving = true"), "frost Blizzard should be position-cast and movement-gated")
assert_true(contains(core_runtime, "function NS.try_cast_position") and contains(core_runtime, "cast_position_spell"), "position-targeted spells need core position-cast support")
assert_true(contains(core_runtime, "function NS.buff_stacks") and contains(core_runtime, "get_buff_stacks"), "core should expose buff stack checks for HoT and proc logic")
assert_true(contains(core_runtime, "action.max_mana") and contains(core_runtime, "blocked: max_mana"), "action engine should support max_mana gates")
assert_true(contains(core_runtime, 'action.target == "pet"') and contains(core_runtime, "blocked: no_pet"), "pet-target spells should fail closed when no pet exists")
assert_true(contains(core_runtime, "action.blocked_debuff") and contains(core_runtime, "blocked: blocked_debuff"), "action engine should support debuff-based cast suppression")
assert_true(contains(core_runtime, "min_debuff_stacks") and contains(core_runtime, "get_debuff_stacks"), "action engine should support stack-aware debuff maintenance")
assert_true(contains(core_runtime, "action.requires_ready_spell") and contains(core_runtime, "blocked: requires_ready_spell"), "action engine should support paired cooldown readiness")
assert_true(contains(core_runtime, "action.max_enemy_count") and contains(core_runtime, "blocked: max_enemy_count"), "action engine should support upper enemy-count gates")
assert_true(contains(core_runtime, "action.not_casting") and contains(core_runtime, "blocked: already_casting"), "action engine should support cast/channel suppression gates")
assert_true(contains(core_runtime, "action.moving") and contains(core_runtime, "blocked: not_moving"), "action engine should support movement-only instant fillers")
assert_true(contains(core_runtime, "action.min_ttd") and contains(core_runtime, "blocked: min_ttd"), "action engine should support time-to-die gates")
assert_true(contains(core_runtime, "action.target_not_player") and contains(core_runtime, "blocked: target_player"), "action engine should support non-player-only spell gates")
assert_true(contains(core_runtime, "action.creature_types") and contains(core_runtime, "blocked: creature_type"), "action engine should support creature-type gates for restricted spells")
assert_true(contains(core_runtime, "function NS.is_current_spell") and contains(core_runtime, "core.spell_book and core.spell_book.is_current_spell"), "queued swing-replacement spells need current-spell detection")
assert_true(contains(core_runtime, "function NS.get_time_until_swing") and contains(core_runtime, "common/utility/auto_attack_helper"), "twist and queue-trick playstyles need swing timer helpers")
local main_runtime = read_file("EaxRotations/main_sylvanas.lua")
assert_true(contains(main_runtime, "is_channelling_spell"), "dispatcher should recognize native channel state as well as IZI channel aliases")
assert_true(contains(main_runtime, "target_time_to_die") and contains(main_runtime, "ttd_known"), "dispatcher should expose known target TTD separately from fallback TTD")

local rogue_assassination = read_file("EaxRotations/classes/rogue/assassination_sylvanas.lua")
local rogue_subtlety = read_file("EaxRotations/classes/rogue/subtlety_sylvanas.lua")
local rogue_combat = read_file("EaxRotations/classes/rogue/combat_sylvanas.lua")
assert_true(contains(rogue_assassination, 'requires_buff = { 1787, 1786, 1785, 1784 }') and contains(rogue_assassination, "requires_behind = true"), "assassination openers should accept all Stealth ranks and require behind where TBC spells do")
assert_true(contains(rogue_subtlety, 'requires_buff = { 1787, 1786, 1785, 1784 }') and contains(rogue_subtlety, "requires_behind = true"), "subtlety Ambush should accept all Stealth ranks and require behind")
assert_true(contains(rogue_combat, 'name = "SliceAndDice"') and contains(rogue_combat, 'kind = "buff"'), "Slice and Dice should not be recast while already active")
assert_true(contains(rogue_combat, 'name = "BladeFlurry"') and contains(rogue_combat, 'setting = "use_cooldowns"') and not contains(rogue_combat, 'name = "BladeFlurry", spell = SPELLS.BladeFlurry, target = "self", enemy_count = 2'), "Blade Flurry should be available as a single-target haste cooldown, not only a cleave button")
assert_true(before(rogue_combat, 'name = "Rupture"', 'name = "Eviscerate"') and contains(rogue_combat, "max_enemy_count = 1"), "Combat should prefer single-target Rupture before Eviscerate")
assert_true(before(rogue_combat, 'name = "Eviscerate"', 'name = "SinisterStrike"'), "Combat should spend 5 combo points before building more")

local hunter_bm = read_file("EaxRotations/classes/hunter/beast_mastery_sylvanas.lua")
local hunter_class = read_file("EaxRotations/classes/hunter/class_sylvanas.lua")
local hunter_mm = read_file("EaxRotations/classes/hunter/marksmanship_sylvanas.lua")
local hunter_survival = read_file("EaxRotations/classes/hunter/survival_sylvanas.lua")
assert_true(contains(hunter_class, 'ExplosiveTrap = NS.spell_action({ 27025, 14317, 14316, 13813 }, "ExplosiveTrap")'), "Explosive Trap should not include effect-only IDs")
assert_true(contains(hunter_bm, 'name = "BestialWrath"') and contains(hunter_bm, 'target = "pet"'), "Bestial Wrath should target the pet, not the player")
assert_true(contains(hunter_bm, 'name = "RapidFire"') and contains(hunter_bm, "cooldown = 300"), "BM should use Rapid Fire as an opener/burst cooldown")
assert_true(contains(hunter_bm, 'name = "KillCommand"') and contains(hunter_bm, "cooldown = 5"), "Kill Command should be cooldown-gated")
assert_true(contains(hunter_bm, 'name = "MultiShot"') and not contains(hunter_bm, 'name = "MultiShot", spell = SPELLS.MultiShot, enemy_count = 2'), "BM should weave Multi-Shot on single target too")
assert_true(before(hunter_bm, 'name = "SteadyShot"', 'name = "SerpentSting"'), "BM should not prioritize Serpent Sting above core shot rotation")
assert_true(contains(hunter_mm, 'name = "AimedShotPrepull"') and contains(hunter_mm, "ooc = true"), "Aimed Shot should be a pre-pull opener, not a normal in-combat filler")
assert_true(contains(hunter_mm, 'name = "KillCommand"') and contains(hunter_mm, "cooldown = 5"), "MM should use Kill Command when the crit proc makes it available")
assert_true(contains(hunter_mm, 'name = "MultiShot"') and not contains(hunter_mm, 'name = "MultiShot", spell = SPELLS.MultiShot, enemy_count = 2'), "MM should weave Multi-Shot on single target too")
assert_true(contains(hunter_mm, 'name = "ArcaneShot"') and before(hunter_mm, 'name = "SteadyShot"', 'name = "SerpentSting"'), "MM should have Arcane Shot moving fallback before Serpent maintenance")
assert_true(contains(hunter_survival, 'name = "RapidFire"') and contains(hunter_survival, "cooldown = 300"), "Survival should use Rapid Fire as an opener/burst cooldown")
assert_true(contains(hunter_survival, 'name = "ExplosiveTrap"') and contains(hunter_survival, "enemy_count = 7") and contains(hunter_survival, "cooldown = 30"), "Explosive Trap should be reserved for large AoE pulls")
assert_true(contains(hunter_survival, 'name = "KillCommand"') and contains(hunter_survival, "cooldown = 5"), "Survival should use Kill Command when the crit proc makes it available")
assert_true(contains(hunter_survival, 'name = "MultiShot"') and not contains(hunter_survival, 'name = "MultiShot", spell = SPELLS.MultiShot, enemy_count = 2'), "Survival should weave Multi-Shot on single target too")
assert_true(contains(hunter_survival, 'name = "ArcaneShot"') and before(hunter_survival, 'name = "SteadyShot"', 'name = "SerpentSting"'), "Survival should have Arcane Shot moving fallback before Serpent maintenance")

local kebab = read_file("EaxRotations/classes/warrior/kebab_sylvanas.lua")
assert_not(contains(kebab, "46941"), "WotLK Commanding Shout fallback should not return")
assert_true(contains(kebab, "context.oh_remain") and contains(kebab, "context.mh_remain"), "Kebab should consume swing timers for HS queue timing")
assert_true(contains(kebab, "kebab_use_ww_execute") and contains(kebab, "kebab_use_ms_execute"), "Kebab execute should leave room for configured WW/MS execute-phase usage")

print("PASS test_spell_id_table_regressions")
