-- test_pattern15_audit.lua -- regression pinning Pattern-15 header hygiene.
-- WHAT: walks every EaxRotations/shared/*.lua file (excluding gitignored
--       build artefacts) and asserts the canonical 5-key header is present
--       exactly once, with no duplicate taglines and no mid-block DECISION
--       injection.
-- WHEN:  invoked by run_rotation_tests.lua on every regression cycle.
-- WHY:   regression for the duplicate-header / separator-echo pathology that
--       stack-patches over pre-existing headers introduce.
-- SAFETY: pure file walker; no engine API calls; never raises.

package.path = "EaxRotations/?.lua;EaxRotations/?/?.lua;./?.lua;api/?.lua" .. package.path

local lfs_ok, lfs = pcall(require, "lfs")
if not lfs_ok or not lfs then
    print("SKIP test_pattern15_audit (lfs not available on this Lua build)")
    return
end

local io_open, os_exit, print = io.open, os.exit, print

-- Cross-platform lfs-based directory scan (replaces banned io.popen shell-out).
local function scan_dir(dir, pattern)
    local files = {}
    local attr = lfs.attributes(dir)
    if attr and attr.mode == "directory" then
        for entry in lfs.dir(dir) do
            if entry ~= "." and entry ~= ".." then
                local full = dir .. "/" .. entry
                local fattr = lfs.attributes(full)
                if fattr and fattr.mode == "file" then
                    if not pattern or entry:match(pattern) then
                        files[#files + 1] = { path = full, name = entry }
                    end
                end
            end
        end
    end
    table.sort(files, function(a, b) return a.name < b.name end)
    return files
end

-- Skip files matching the .gitignore:85 build-artefact glob
-- (wowhead_data_bridge_*_index_*.lua). These are regenerated by
-- build_tools/json_to_lua_data.py and tested separately. Pure-pattern
-- match (no shell) to avoid `io.popen` (banned per AGENTS.md).
local function is_gitignored(relpath)
    if not relpath then return false end
    local base = relpath:match("([^/]+)$") or relpath
    if base:sub(1, 20) ~= "wowhead_data_bridge_" then return false end
    if base:sub(-4) ~= ".lua" then return false end
    if not string.find(base, "_index_", 1, true) then return false end
    return true
end

local function strip_leading_sp(s) return (s:gsub("^%s+", ""):gsub("%s+$", "")) end
local function starts_with(s, prefix) return s:sub(1, #prefix) == prefix end

local function audit_file(path, fname)
    local f = io_open(path, "r")
    if not f then return { "READ-ERR" } end
    local src = f:read("*a") or ""
    f:close()
    local issues = {}

    local lines = {}
    for ln in src:gmatch("[^\n]+") do
        lines[#lines + 1] = ln
        if #lines >= 80 then break end
    end

    -- 1) Tagline count: how many distinct `--  filename.lua ...` preambles.
    local tag_count = 0
    for _, ln in ipairs(lines) do
        local s = strip_leading_sp(ln)
        if s == "-- " .. fname or
           starts_with(s, "-- " .. fname .. "--") or
           starts_with(s, "-- " .. fname .. " ") then
            tag_count = tag_count + 1
        end
    end
    if tag_count > 1 then issues[#issues + 1] = "DUP-TAGLINE(" .. tag_count .. ")" end

    -- 2) Collect 5-key positions.
    local positions = { WHAT = {}, WHEN = {}, WHY = {}, SAFETY = {}, DECISION = {} }
    for i, ln in ipairs(lines) do
        local s = strip_leading_sp(ln)
        for _, k in ipairs({ "WHAT", "WHEN", "WHY", "SAFETY", "DECISION" }) do
            if s == "-- " .. k .. ":" or
               starts_with(s, "-- " .. k .. ": ") then
                positions[k][#positions[k] + 1] = i
                break
            end
        end
    end

    -- 3) No-header files are acceptable for legitimately data-only modules;
    --    but at least one key should be present in shared/* (defensive).
    local any_key = false
    for _k, v in pairs(positions) do
        if #v > 0 then any_key = true; break end
    end
    if not any_key then issues[#issues + 1] = "NO-HEADER" end

    -- 4) Multi-block: any key with count > 1 -> duplicate headers stacked.
    for k, v in pairs(positions) do
        if #v > 1 then issues[#issues + 1] = "MULTI-BLOCK(" .. k .. "=" .. #v .. ")" end
    end

    -- 5) Mid-block DECISION injection.
    if #positions.DECISION > 0 then
        local dec_pos = positions.DECISION[1]
        local max_other = -1
        for _, k in ipairs({ "WHAT", "WHEN", "WHY", "SAFETY" }) do
            if positions[k][1] and positions[k][1] > max_other then
                max_other = positions[k][1]
            end
        end
        if max_other > 0 and dec_pos < max_other then
            issues[#issues + 1] = "MID-INJECT"
        end
    end

    -- 6) Code-line distance: allow large gaps when a `-- ...` comment block
    --    follows the header (legit docstring/fat-arch block). The flag
    --    fires only when NOTHING intervenes between header and code.
    local last_key = -1
    for _, k in ipairs({ "WHAT","WHEN","WHY","SAFETY","DECISION" }) do
        for _, p in ipairs(positions[k]) do
            if p > last_key then last_key = p end
        end
    end
    local first_code = -1
    for i, ln in ipairs(lines) do
        local s = strip_leading_sp(ln)
        if s ~= "" and not starts_with(s, "--") then first_code = i; break end
    end
    if last_key > 0 and first_code > 0 then
        local gap = first_code - last_key
        -- Look at the intervening lines: if >=3 are `-- ...` comments, treat
        -- as legitimate docstring block; otherwise expect <=30.
        local comment_lines = 0
        for i = last_key + 1, first_code - 1 do
            local s = strip_leading_sp(lines[i] or "")
            if starts_with(s, "--") and s ~= "" then
                comment_lines = comment_lines + 1
            end
        end
        local allowed_gap = (comment_lines >= 3) and 80 or 30
        if gap > allowed_gap then
            issues[#issues + 1] = "CODE-TOO-FAR(gap=" .. gap .. ",comments=" .. comment_lines .. ")"
        end
    end

    return issues
end

local all_files = {}
for _, f in ipairs(scan_dir("EaxRotations", "%.lua$")) do all_files[#all_files + 1] = f end
for _, f in ipairs(scan_dir("EaxRotations/core", "%.lua$")) do all_files[#all_files + 1] = f end
for _, f in ipairs(scan_dir("EaxRotations/shared", "%.lua$")) do all_files[#all_files + 1] = f end
for _, f in ipairs(scan_dir("EaxRotations/tests", "%.lua$")) do all_files[#all_files + 1] = f end
local classes = { "druid", "hunter", "mage", "paladin", "priest", "rogue", "shaman", "warlock", "warrior" }
for _, class in ipairs(classes) do
    for _, f in ipairs(scan_dir("EaxRotations/classes/" .. class, "_sylvanas%.lua$")) do
        all_files[#all_files + 1] = f
    end
end

local scanned, bad = 0, {}
for _, f in ipairs(all_files) do
    if is_gitignored(f.path) then
        -- skip build artefacts
    else
        scanned = scanned + 1
        local issues = audit_file(f.path, f.name)
        if #issues > 0 then
            bad[#bad + 1] = { f.name, issues }
        end
    end
end

if #bad > 0 then
    print("FAIL test_pattern15_audit:")
    for _, p in ipairs(bad) do
        print("  " .. p[1] .. ": " .. table.concat(p[2], ", "))
    end
    os_exit(1)
end

print("PASS test_pattern15_audit (" .. scanned .. " tracked shared/*.lua files clean)")
