-- apl_parser.lua — wowsims TypeAPL JSON parser + rotation-order conformance.
-- WHAT:  decode wowsims APL JSON fixtures (TypeAPL format, see tools/evidence/apl/)
--        into an ordered spell-action list, and check a rotation's strategy
--        priority order against that reference.
-- WHEN:  loaded by tools/apl_status.lua and tests/test_apl_conformance.lua;
--        no game API touched at load time.
-- WHY:   Phase 2 APL conformance — _wotlk.lua strategy order must match the
--        pinned wowsims APL priority list, enforced in CI so a refactor can
--        never silently reorder a rotation.
-- SAFETY: pure data module; nil-tolerant key walks; no os/io side effects.
--
-- Reference provenance (pinned at fetch time, 2026-08-09):
--   repo:   github.com/wowsims/wotlk @ 563e4a08cb15729f1fdcbcf68e6d68224553bfef
--   fire:    ui/mage/apls/fire.apl.json            -> tools/evidence/apl/fire_wotlk.apl.json
--   affl:    ui/warlock/apls/affliction.apl.json   -> tools/evidence/apl/affliction_wotlk.apl.json
--   feral:   ui/feral_druid/apls/default.apl.json  -> tools/evidence/apl/feralcat_wotlk.apl.json
--            (feral delegates to sim/druid/feral/rotation.go catOptimalRotationAction;
--             the JSON carries no spell list, so its reference order is pinned
--             from the Go doRotation() in tests/test_apl_conformance.lua)
--   2026-08-09 batch (see tools/evidence/apl/SOURCES.md + tools/apl_status.lua
--   ENTRIES for the full table): arcane/frost (mage), combat/mutilate (rogue),
--   advanced (elemental shaman), shadow (priest).

local M = {}

-- ---------------------------------------------------------------------------
-- Section 1: minimal strict JSON decoder (objects/arrays/strings/numbers/
-- bools/null). The fixtures are machine-generated by Go's json encoder, so a
-- compact recursive-descent decoder is sufficient and dependency-free.
-- ---------------------------------------------------------------------------

local json = {}

local function skip_ws(s, i)
    local c
    repeat
        c = s:sub(i, i)
        if c == " " or c == "\t" or c == "\n" or c == "\r" then i = i + 1 else break end
    until false
    return i
end

local function decode_string(s, i)
    -- s:sub(i,i) == '"'
    i = i + 1
    local out, n = {}, 0
    while i <= #s do
        local c = s:sub(i, i)
        if c == '"' then return table.concat(out), i + 1 end
        if c == "\\" then
            local e = s:sub(i + 1, i + 1)
            if e == "n" then out[n + 1] = "\n"
            elseif e == "t" then out[n + 1] = "\t"
            elseif e == "r" then out[n + 1] = "\r"
            elseif e == "b" then out[n + 1] = "\b"
            elseif e == "f" then out[n + 1] = "\f"
            elseif e == "/" then out[n + 1] = "/"
            elseif e == "\\" then out[n + 1] = "\\"
            elseif e == '"' then out[n + 1] = '"'
            elseif e == "u" then
                local hex = s:sub(i + 2, i + 5)
                local cp = tonumber(hex, 16)
                if not cp then error("apl_parser: bad \\u escape at " .. i) end
                -- BMP code point -> UTF-8
                if cp < 0x80 then out[n + 1] = string.char(cp)
                elseif cp < 0x800 then
                    out[n + 1] = string.char(0xC0 + math.floor(cp / 0x40), 0x80 + cp % 0x40)
                else
                    out[n + 1] = string.char(
                        0xE0 + math.floor(cp / 0x1000),
                        0x80 + math.floor(cp / 0x40) % 0x40,
                        0x80 + cp % 0x40)
                end
                i = i + 4
            else
                error("apl_parser: bad string escape at " .. i)
            end
            n = n + 1
            i = i + 2
        else
            out[n + 1] = c
            n = n + 1
            i = i + 1
        end
    end
    error("apl_parser: unterminated string")
end

local decode_value

local function decode_array(s, i)
    -- s:sub(i,i) == '['
    local out = {}
    i = skip_ws(s, i + 1)
    if s:sub(i, i) == "]" then return out, i + 1 end
    while true do
        local v
        v, i = decode_value(s, i)
        out[#out + 1] = v
        i = skip_ws(s, i)
        local c = s:sub(i, i)
        if c == "," then i = skip_ws(s, i + 1)
        elseif c == "]" then return out, i + 1
        else error("apl_parser: expected ',' or ']' at " .. i) end
    end
end

local function decode_object(s, i)
    -- s:sub(i,i) == '{'
    local out = {}
    i = skip_ws(s, i + 1)
    if s:sub(i, i) == "}" then return out, i + 1 end
    while true do
        local key
        key, i = decode_string(s, i)
        i = skip_ws(s, i)
        if s:sub(i, i) ~= ":" then error("apl_parser: expected ':' at " .. i) end
        local v
        v, i = decode_value(s, skip_ws(s, i + 1))
        out[key] = v
        i = skip_ws(s, i)
        local c = s:sub(i, i)
        if c == "," then i = skip_ws(s, i + 1)
        elseif c == "}" then return out, i + 1
        else error("apl_parser: expected ',' or '}' at " .. i) end
    end
end

local function decode_number(s, i)
    local j = i
    if s:sub(j, j) == "-" then j = j + 1 end
    while true do
        local c = s:sub(j, j)
        if c:match("%d") or c == "." or c == "e" or c == "E" or c == "+" or c == "-" then
            j = j + 1
        else break end
    end
    return tonumber(s:sub(i, j - 1)), j
end

decode_value = function(s, i)
    i = skip_ws(s, i)
    local c = s:sub(i, i)
    if c == "{" then return decode_object(s, i) end
    if c == "[" then return decode_array(s, i) end
    if c == '"' then return decode_string(s, i) end
    if c == "t" then
        if s:sub(i, i + 3) == "true" then return true, i + 4 end
        error("apl_parser: bad literal at " .. i)
    end
    if c == "f" then
        if s:sub(i, i + 4) == "false" then return false, i + 5 end
        error("apl_parser: bad literal at " .. i)
    end
    if c == "n" then
        if s:sub(i, i + 3) == "null" then return nil, i + 4 end
        error("apl_parser: bad literal at " .. i)
    end
    if c == "-" or c:match("%d") then return decode_number(s, i) end
    error("apl_parser: unexpected char '" .. c .. "' at " .. i)
end

function M.decode_json(text)
    local v, i = decode_value(text, 1)
    i = skip_ws(text, i)
    if i <= #text then error("apl_parser: trailing data at " .. i) end
    return v
end

-- ---------------------------------------------------------------------------
-- Section 2: TypeAPL priority extraction
-- ---------------------------------------------------------------------------

-- Extract the ordered priority-list actions from a decoded TypeAPL table.
-- Returns an array of { kind = "cast"|"channel"|"multidot"|"multishield", id = <number> }.
-- Non-spell actions (autocastOtherCooldowns, triggerIcd, activateAura,
-- condition-only entries) are skipped. Sequence entries (opener/execute
-- macros) are skipped by default — they are condition-gated one-shots, not
-- steady-state priority — pass include_sequences = true to flatten them.
-- multishield is the healer-analog of multidot (maintain N shields on the
-- raid, e.g. the wowsims disc priest APL's Power Word: Shield entry) —
-- extracted the same way so healer APLs pin fully.
-- Known TypeAPL action-node keys. The four spell-carrying forms are
-- extracted (cast/channel/multidot/multishield); the rest are documented
-- non-spell forms the parser intentionally skips (autocastOtherCooldowns,
-- sequence/strictSequence/resetSequence, schedule, wait/waitUntil, and the
-- feral catOptimalRotationAction black box). `condition` is per-action
-- metadata, not an action kind. Anything else is an UNKNOWN action kind — the
-- silent-skip defect class (the multishield gap the healer unit fixed is this
-- exact class: the disc APL's PW:S was silently dropped until multishield was
-- added). unknown_action_kinds() audits every pinned fixture so a new wowsims
-- action kind fails loudly instead of silently weakening the pin.
local KNOWN_ACTION_KINDS = {
    castSpell = true, channelSpell = true, multidot = true, multishield = true,
    autocastOtherCooldowns = true, sequence = true, strictSequence = true,
    resetSequence = true, schedule = true, wait = true, waitUntil = true,
    catOptimalRotationAction = true,
}

-- Walk the priority list and return every unknown action-kind occurrence as
-- { kind = <name>, path = <"action.sequence..."> }. Empty when every action
-- node uses only KNOWN_ACTION_KINDS. Recurses into sequence/strictSequence/
-- schedule containers so a nested unknown kind (e.g. a waitUntil inside a
-- strictSequence) is caught, not just top-level nodes.
function M.unknown_action_kinds(apl)
    local unknown = {}
    local pl = type(apl) == "table" and apl.priorityList or {}
    local function walk_node(a, path)
        if type(a) ~= "table" then return end
        for k, v in pairs(a) do
            if k == "condition" then
                -- per-action metadata (spellCanCast / spellReady / ...), not an action kind
            elseif not KNOWN_ACTION_KINDS[k] then
                unknown[#unknown + 1] = { kind = k, path = path }
            elseif k == "sequence" or k == "strictSequence" then
                if type(v) == "table" and type(v.actions) == "table" then
                    for _, sub in ipairs(v.actions) do
                        walk_node(sub.action or sub, path .. "." .. k)
                    end
                end
            elseif k == "schedule" then
                if type(v) == "table" then walk_node(v.innerAction, path .. "." .. k) end
            end
            -- castSpell/channelSpell/multidot/multishield and the non-spell
            -- leaves carry no nested action nodes; their internals (spellId,
            -- condition fields) are not action kinds.
        end
    end
    for _, entry in ipairs(pl) do
        walk_node(entry.action, "action")
    end
    return unknown
end

function M.priority_actions(apl, opts)
    local include_sequences = opts and opts.include_sequences
    local out = {}
    local pl = type(apl) == "table" and apl.priorityList or {}
    local function walk_action(a, into)
        if type(a) ~= "table" then return end
        local cast = a.castSpell
        if cast then
            local sid = type(cast) == "table" and cast.spellId
            if type(sid) == "table" and type(sid.spellId) == "number" then
                into[#into + 1] = { kind = "cast", id = sid.spellId }
            end
            return
        end
        local ch = a.channelSpell
        if ch then
            local sid = type(ch) == "table" and ch.spellId
            if type(sid) == "table" and type(sid.spellId) == "number" then
                into[#into + 1] = { kind = "channel", id = sid.spellId }
            end
            return
        end
        local md = a.multidot
        if md then
            local sid = type(md) == "table" and md.spellId
            if type(sid) == "table" and type(sid.spellId) == "number" then
                into[#into + 1] = { kind = "multidot", id = sid.spellId }
            end
            return
        end
        local ms = a.multishield
        if ms then
            local sid = type(ms) == "table" and ms.spellId
            if type(sid) == "table" and type(sid.spellId) == "number" then
                into[#into + 1] = { kind = "multishield", id = sid.spellId }
            end
            return
        end
        if include_sequences then
            local seq = a.sequence
            if seq and type(seq.actions) == "table" then
                for _, sub in ipairs(seq.actions) do
                    walk_action(sub.action or sub, into)
                end
            end
        end
        -- autocastOtherCooldowns / triggerIcd / activateAura / condition-only: no spell
    end
    for _, entry in ipairs(pl) do
        walk_action(entry.action, out)
    end
    return out
end

-- Ordered spell-id list (occurrence-preserving; use for pair-order checks).
function M.priority_ids(apl, opts)
    local out = {}
    for _, a in ipairs(M.priority_actions(apl, opts)) do
        out[#out + 1] = a.id
    end
    return out
end

-- First-occurrence unique ids (use for "which spells appear" checks).
function M.unique_ids(apl, opts)
    local seen, out = {}, {}
    for _, a in ipairs(M.priority_actions(apl, opts)) do
        if not seen[a.id] then seen[a.id] = true out[#out + 1] = a.id end
    end
    return out
end

-- ---------------------------------------------------------------------------
-- Section 3: order conformance
-- ---------------------------------------------------------------------------

-- Check that `strategy_order` (our compiled strategy names, priority-first)
-- preserves the relative order of `reference_names` (APL-derived, occurrence-
-- preserving, mapped to our strategy names). Names absent from our rotation
-- are ignored (they impose no constraint). Returns nil when conformant, else
-- a table { reason, prev, name, prev_pos, name_pos } describing the first
-- pair the APL expects earlier but our rotation places later.
function M.check_name_order(strategy_order, reference_names)
    local pos = {}
    for i, name in ipairs(strategy_order) do
        if not pos[name] then pos[name] = i end
    end
    local prev
    for _, name in ipairs(reference_names) do
        if name and pos[name] then
            if prev and pos[prev] > pos[name] then
                return {
                    reason = "order",
                    prev = prev,
                    name = name,
                    prev_pos = pos[prev],
                    name_pos = pos[name],
                }
            end
            prev = name
        end
    end
    return nil
end

-- Convenience: same check but reference is an ordered spell-id list and
-- `resolve(id)` maps a spell id to a strategy name (or nil). occurrenceCount
-- lets a multi-cast id (e.g. Scorch refresh + execute) resolve to different
-- strategy names per occurrence: resolver is called as resolve(id, occurrence)
-- where occurrence starts at 1 and increments per id occurrence in `ids`.
function M.check_id_order(strategy_order, ids, resolve)
    local names = {}
    local seen = {}
    for _, id in ipairs(ids) do
        seen[id] = (seen[id] or 0) + 1
        names[#names + 1] = resolve(id, seen[id])
    end
    return M.check_name_order(strategy_order, names)
end

return M
