-- wowhead_data_bridge_spell_detail_sylvanas.lua -- shared Wowhead data bridge for per-spell detail fields.
-- WHAT:   shared Wowhead data bridge for per-spell detail fields.
-- WHEN:   loaded at spec-class startup; consumed on spell-id match functions.
-- WHY:    enriches EaxRotations spec logic with Wowhead detail scalars.
-- SAFETY: static bridge; nil-tolerant key fetch; no api at load.
-- DECISION: pure data; consumed via require(); nil-tolerant key fetch.

-- wowhead_data_bridge_spell_detail_sylvanas.lua -- Wowhead spell-detail bridge (rank + description + cost)
-- WHAT:  expose spell-detail lookups: name, rank, cost, cast_time
-- WHEN:  module load + spec validators
-- WHY:   single source for spell metadata that the DBC does not expose
-- SAFETY: read-only table consumer; nil on missing id

-- ============================================================================
-- Shared Data: Wowhead Spell Detail
-- ============================================================================
-- Generated by: build_tools/json_to_lua_data.py
-- ============================================================================
-- Format: [spell_id] = {cost_type, cost_amount, range, cast_time, duration,
--                       periodic_amount, periodic_school, periodic_interval, flags, school, gcd}
-- Only spells with useful data beyond spell_index are included.
-- ============================================================================

local M = {}

M.spell_detail = {

}

return M.spell_detail
