-- wowhead_data_bridge_sylvanas.lua -- shared Wowhead data bridge root (spell + item table aggregator).
-- WHAT:   shared Wowhead data bridge root (spell + item table aggregator).
-- WHEN:   loaded at class-module startup by every hunter/mage/etc.
-- WHY:    centralises the wowhead_data->Lua pipeline.
-- SAFETY: static aggregate table; nil-tolerant getter; no api at load.
-- DECISION: pure data; consumed via require(); nil-tolerant key fetch.

-- ============================================================================
-- Shared Data: Wowhead Data Bridge (Embedded Lua Tables)
-- Pre-extracted spell, item, and NPC data converted from wowhead JSON.
-- Module load (cached). Used by spell_rank_resolver, spell_corpus,
-- and dot_refresh.
--
-- Ship constraint only .lua files allowed in EaxRotations: all data is embedded
-- as Lua tables; no io.open or JSON parsing needed.
--
-- Generated by: build_tools/json_to_lua_data.py
-- ============================================================================

local M = {}

-- ============================================================================
-- Lazy-loaded sub-modules — loaded on first access to save ~4 MB+ of memory
-- for processes that only touch a subset of the data (e.g. TBC specs never
-- need the vanilla index).  Cached in M after first load for fast access.
-- ============================================================================
local _loaded = {}
local _failed = {}

local _MODULE_PATHS = {
    spell_index_tbc     = "shared/wowhead_data_bridge_spell_index_tbc_sylvanas",
    spell_index_vanilla = "shared/wowhead_data_bridge_spell_index_vanilla_sylvanas",
    item_index          = "shared/wowhead_data_bridge_item_index_sylvanas",
    spell_detail        = "shared/wowhead_data_bridge_spell_detail_sylvanas",
}

local function _load_module(key)
    if _loaded[key] then return _loaded[key] end
    if _failed[key] then return nil end

    local path = _MODULE_PATHS[key]
    if not path then return nil end

    local ok, mod = pcall(require, path)
    if ok and type(mod) == "table" then
        _loaded[key] = mod
        return mod
    end

    _failed[key] = true
    return nil
end

-- Metatable: intercept first access to each sub-module key and load it on demand.
-- After first load, rawset caches the result in M itself for fast direct access.
setmetatable(M, {
    __index = function(t, key)
        local mod = _load_module(key)
        if mod ~= nil then
            rawset(t, key, mod)
            return mod
        end
        return nil
    end
})

-- ============================================================================
-- Public API — mimics the old io.open-based interfaces
-- ============================================================================






return M

