-- ============================================================================
-- Shared Data: Wowhead Spell Detail
-- ============================================================================
-- Generated by: build_tools/json_to_lua_data.py
-- ============================================================================
-- Format: [spell_id] = {cost_type, cost_amount, range, cast_time, duration,
--                       periodic_amount, periodic_school, periodic_interval, flags, school, gcd}
-- Only spells with useful data beyond spell_index are included.
-- ============================================================================

local M = {}

M.spell_detail = {

}

return M.spell_detail
