-- object_spawns.lua — WHERE the quest game objects this plugin's goals name are.
-- WHAT:  the two questions shared/spawn_patrol.lua asks of npc_spawns.lua, asked of game objects:
--        find_object_spawns(entry) -> every spawn point of that entry, and
--        find_object_ids_by_name(name) -> the entries that carry that world name.
-- WHEN:  the sweep's candidate build, for a goal whose id is a game object — a Zygor goal's
--        `targetid` is that object's entry, not a creature's — or whose target name is one only a
--        game object carries.
-- WHY:   a creature index cannot describe a quest object, so the sweep for "Ogre Remains" had no
--        coordinates at all and fell back to the step's waypoints: 108yd and 113yd legs, and never
--        a click (live, step 7). Naming the objective is a capability neither open pixel bot has —
--        they find things by nameplate and corpse pixels on screen; we are told the name and the
--        entry and can go to where the entry spawns.
-- DATA:  generated by tools/generate_object_spawns.py from the cMaNGOS tbc-db `gameobject` and
--        `gameobject_template` tables — the same database EaxAutoQuester/npc_spawns was cut from.
--        The chunks and the manifest are BUILD OUTPUT and are gitignored; the accessor is tracked.
--        `--check` in the generator fails when the two drift.
-- SAFETY: NO DATA IS A NORMAL STATE, not an error. With no manifest (or no chunks) `available` is
--        false, every answer is nil or an empty list, and the sweep behaves exactly as it did
--        before this index existed — the step's own waypoints. Nothing here invents a destination,
--        and nothing here fails loudly for a missing table it was never given.
-- DECISION: the same surface as npc_spawns.lua on purpose, so the two indexes are interchangeable
--        at the call site and a reader who knows one knows this. The two answers npc_spawns also
--        offers (`find_npc_spawn` for a single point, `search_npc_by_name` for a fuzzy scan) are
--        NOT reproduced: no consumer asks them, and an unused accessor is a maintenance surface.
-- NOTE:   Read the manifest once, at first use. `reload()` re-reads it, which is how the test
--        suite installs a fixture and how a regenerated index is picked up without restarting.

local M = {}

-- Set by load_manifest(); nil until then. Kept in a field rather than inlined at each use so
-- "is there data at all" is one question with one answer.
M.available = false
M.chunk_count = 0
M.entry_count = 0

local _loaded_chunks = {}
local _name_ids_cache = {}

--- Same cap npc_spawns.lua uses: a name that legitimately matches dozens of entries is not a
--- question worth answering with every one of them.
local MAX_NAME_IDS = 32

--- Read the generated manifest: how many chunks, how many entries, and therefore whether there is
--- an index at all. A missing manifest is the documented no-data state, not a failure.
local function load_manifest()
    _loaded_chunks = {}
    _name_ids_cache = {}
    M.available = false
    M.chunk_count = 0
    M.entry_count = 0

    local ok, manifest = pcall(require, "object_spawns/manifest")
    if not ok or type(manifest) ~= "table" then return false end
    local count = tonumber(manifest.chunk_count)
    if not count or count <= 0 then return false end

    M.chunk_count = math.floor(count)
    M.entry_count = tonumber(manifest.entry_count) or 0
    M.generated_from = manifest.generated_from
    M.available = true
    return true
end

--- One chunk, or an empty table. The require is pcall-guarded because a manifest that promises a
--- chunk the checkout does not have is a missing index, not a crash: the answers become nil and
--- the sweep falls back to the guide's waypoints.
--- @param chunk_idx integer Zero-based
--- @return table by_entry
local function load_chunk(chunk_idx)
    local cached = _loaded_chunks[chunk_idx]
    if cached then return cached end
    -- Slash-separated module path on purpose, for the same reason npc_spawns.lua uses it: it
    -- resolves through the package.path entry "./EaxAutoQuester/?.lua", so it works wherever the
    -- plugin tree is mounted.
    local path = "object_spawns/chunk_" .. string.format("%03d", chunk_idx)
    local ok, chunk = pcall(require, path)
    if ok and chunk and chunk.by_entry then
        _loaded_chunks[chunk_idx] = chunk.by_entry
        return chunk.by_entry
    end
    _loaded_chunks[chunk_idx] = {}
    return _loaded_chunks[chunk_idx]
end

--- Every spawn point recorded for a game-object entry, across every map.
--- Lazy per chunk (an entry lives in exactly one chunk), and the array is the module's own data:
--- READ-ONLY, do not mutate. Callers filter by map and distance themselves — the sweep needs both,
--- and it already does that for creature spawns.
--- @param entry integer|nil Game-object entry
--- @return table[]|nil Read-only array of { map_id, x, y, z }, or nil when unknown
function M.find_object_spawns(entry)
    if not entry or not M.available then return nil end
    local id_key = tostring(entry)
    for i = 0, M.chunk_count - 1 do
        local data = load_chunk(i)[id_key]
        if data then
            if data.maps and #data.maps > 0 then return data.maps end
            return nil
        end
    end
    return nil
end

--- Resolve a world name to the game-object entries that carry it.
--- Exact case-insensitive equality wins: "Ogre Remains" must not be answered with "Large Ogre
--- Remains" and its spawn points somewhere else, and the spawn points of the wrong object are
--- worse than none. Substring matches are returned only when nothing matches exactly, which is
--- what makes a guide's partial or pluralized target string still resolvable — the same rule, and
--- the same reasoning, as npc_spawns.find_npc_ids_by_name.
--- @param name string|nil World name
--- @return table[] Read-only array of { object_id, name }
function M.find_object_ids_by_name(name)
    if not name or name == "" then return {} end
    if not M.available then return {} end
    local cached = _name_ids_cache[name]
    if cached then return cached end

    local search_lower = string.lower(name)
    local exact, partial = {}, {}
    for i = 0, M.chunk_count - 1 do
        for id_str, entry in pairs(load_chunk(i)) do
            local entry_name = entry and entry.name
            if entry_name then
                local id = tonumber(id_str)
                if id then
                    local entry_lower = string.lower(entry_name)
                    if entry_lower == search_lower then
                        exact[#exact + 1] = { object_id = id, name = entry_name }
                    elseif string.find(entry_lower, search_lower, 1, true) then
                        partial[#partial + 1] = { object_id = id, name = entry_name }
                    end
                end
            end
        end
    end

    local result = (#exact > 0) and exact or partial
    if #result > MAX_NAME_IDS then
        local trimmed = {}
        for i = 1, MAX_NAME_IDS do trimmed[i] = result[i] end
        result = trimmed
    end
    _name_ids_cache[name] = result
    return result
end

--- Drop the name cache. Only for tests that need a cold start; production never calls it.
function M.clear_name_cache()
    _name_ids_cache = {}
end

--- Re-read the manifest and forget every chunk. How a regenerated index is picked up, and how the
--- test suite installs a fixture.
function M.reload()
    return load_manifest()
end

load_manifest()

return M
