-- EAX Warrior Protection | menu.lua
-- All menu elements are created once at require-time.

local menu = {}

local tree = core.menu.tree_node()
local utility_tree = core.menu.tree_node()
local tanking_tree = core.menu.tree_node()
local defensive_tree = core.menu.tree_node()
local burst_tree = core.menu.tree_node()

menu.enabled = core.menu.checkbox(true, "simpleprot_enabled")
menu.toggle_key = core.menu.keybind(7, false, "simpleprot_toggle_key")
menu.debug = core.menu.checkbox(false, "simpleprot_debug")
menu.mode = core.menu.combobox(1, "simpleprot_mode")

-- Core abilities
menu.use_shield_slam = core.menu.checkbox(true, "simpleprot_use_shield_slam")
menu.use_revenge = core.menu.checkbox(true, "simpleprot_use_revenge")
menu.use_devastate = core.menu.checkbox(true, "simpleprot_use_devastate")
menu.use_heroic_strike = core.menu.checkbox(true, "simpleprot_use_heroic_strike")
menu.use_cleave = core.menu.checkbox(true, "simpleprot_use_cleave")
menu.use_execute = core.menu.checkbox(false, "simpleprot_use_execute")
menu.use_battle_shout = core.menu.checkbox(false, "simpleprot_use_battle_shout")
menu.use_commanding_shout = core.menu.checkbox(true, "simpleprot_use_commanding_shout")
menu.use_bloodrage = core.menu.checkbox(true, "simpleprot_use_bloodrage")
menu.show_notifications = core.menu.checkbox(false, "simpleprot_show_notifications")
menu.use_prepull_bloodrage = core.menu.checkbox(true, "simpleprot_use_prepull_bloodrage")

-- Utility
menu.use_demo_shout = core.menu.checkbox(true, "simpleprot_use_demo_shout")
menu.use_thunder_clap = core.menu.checkbox(true, "simpleprot_use_thunder_clap")
menu.use_sunder_armor = core.menu.checkbox(false, "simpleprot_use_sunder_armor")
menu.sunder_max_stacks = core.menu.slider_int(1, 5, 5, "simpleprot_sunder_max_stacks")
menu.use_rend = core.menu.checkbox(false, "simpleprot_use_rend")
menu.use_hamstring = core.menu.checkbox(false, "simpleprot_use_hamstring")
menu.use_intercept = core.menu.checkbox(true, "simpleprot_use_intercept")
menu.intercept_min_range = core.menu.slider_int(8, 25, 10, "simpleprot_intercept_min_range")

-- Tanking
menu.auto_peel = core.menu.checkbox(true, "simpleprot_auto_peel")
menu.use_taunt = core.menu.checkbox(true, "simpleprot_use_taunt")
menu.use_shield_bash = core.menu.checkbox(true, "simpleprot_use_shield_bash")
menu.use_concussion_blow = core.menu.checkbox(true, "simpleprot_use_concussion_blow")
menu.use_mocking_blow = core.menu.checkbox(true, "simpleprot_use_mocking_blow")
menu.use_challenging_shout = core.menu.checkbox(false, "simpleprot_use_challenging_shout")
menu.use_peel_intercept = core.menu.checkbox(false, "simpleprot_use_peel_intercept")

-- Defensive
menu.use_shield_block = core.menu.checkbox(true, "simpleprot_use_shield_block")
menu.use_last_stand = core.menu.checkbox(true, "simpleprot_use_last_stand")
menu.last_stand_hp_pct = core.menu.slider_int(10, 50, 20, "simpleprot_last_stand_hp_pct")
menu.use_shield_wall = core.menu.checkbox(true, "simpleprot_use_shield_wall")
menu.shield_wall_hp_pct = core.menu.slider_int(10, 50, 25, "simpleprot_shield_wall_hp_pct")
menu.use_spell_reflection = core.menu.checkbox(true, "simpleprot_use_spell_reflection")
menu.spell_reflection_progress_pct = core.menu.slider_int(0, 90, 50, "simpleprot_spell_reflection_progress_pct")
menu.use_healthstone = core.menu.checkbox(false, "simpleprot_use_healthstone")
menu.healthstone_hp_pct = core.menu.slider_int(10, 50, 25, "simpleprot_healthstone_hp_pct")
menu.use_health_potion = core.menu.checkbox(true, "simpleprot_use_health_potion")
menu.health_potion_hp_pct = core.menu.slider_int(10, 50, 25, "simpleprot_health_potion_hp_pct")
menu.use_ironshield_potion = core.menu.checkbox(true, "simpleprot_use_ironshield_potion")
menu.use_stoneform = core.menu.checkbox(true, "simpleprot_use_stoneform")
menu.stoneform_hp_pct = core.menu.slider_int(20, 80, 40, "simpleprot_stoneform_hp_pct")

-- Burst
menu.use_death_wish = core.menu.checkbox(true, "simpleprot_use_death_wish")
menu.use_recklessness = core.menu.checkbox(true, "simpleprot_use_recklessness")
menu.use_blood_fury = core.menu.checkbox(true, "simpleprot_use_blood_fury")
menu.use_berserking = core.menu.checkbox(true, "simpleprot_use_berserking")
menu.use_trinkets = core.menu.checkbox(true, "simpleprot_use_trinkets")
menu.use_war_stomp_interrupt = core.menu.checkbox(true, "simpleprot_use_war_stomp_interrupt")
menu.intimidating_shout_key = core.menu.keybind(7, false, "simpleprot_intimidating_shout_key")
menu.use_disarm = core.menu.checkbox(true, "simpleprot_use_disarm")
menu.use_berserker_rage = core.menu.checkbox(true, "simpleprot_use_berserker_rage")
menu.use_retaliation = core.menu.checkbox(false, "simpleprot_use_retaliation")

-- Sliders
menu.heroic_strike_rage = core.menu.slider_int(20, 100, 50, "simpleprot_hs_rage")
menu.cleave_rage = core.menu.slider_int(20, 100, 45, "simpleprot_cleave_rage")
menu.heroic_strike_rage_cap = core.menu.slider_int(60, 100, 90, "simpleprot_hs_rage_cap")
menu.aoe_enemy_count = core.menu.slider_int(2, 10, 3, "simpleprot_aoe_count")
menu.execute_min_rage = core.menu.slider_int(15, 80, 31, "simpleprot_execute_min_rage")

function menu.render()
    tree:render("EAX Warrior Protection", function()
        menu.enabled:render("Enabled", "Master enable/disable toggle")
        menu.toggle_key:render("Toggle Key", "Keybind to toggle enabled state")
        menu.debug:render("Debug Logging", "Print rotation decisions to console")
        menu.mode:render("Mode", { "Auto", "Solo", "Dungeon", "Raid" })

        menu.use_shield_slam:render("Shield Slam", "Use Shield Slam on cooldown")
        menu.use_revenge:render("Revenge", "Use Revenge when proc is available")
        menu.use_devastate:render("Devastate", "Use Devastate as filler")
        menu.use_heroic_strike:render("Heroic Strike", "Queue Heroic Strike as threat dump")
        menu.use_cleave:render("Cleave", "Queue Cleave as AoE threat dump")
        menu.use_execute:render("Execute", "Use Execute below 20% HP")
        menu.use_battle_shout:render("Battle Shout", "Allow Battle Shout as the upkeep fallback when Commanding is disabled or unavailable")
        menu.use_commanding_shout:render("Commanding Shout", "Prefer Commanding Shout upkeep; if off, Battle Shout can be used when enabled")
        menu.use_bloodrage:render("Bloodrage", "Use Bloodrage when rage is low")
        menu.show_notifications:render("Notifications", "Show short on-screen flashes")
        menu.use_prepull_bloodrage:render("Pre-pull Bloodrage", "Use Bloodrage before combat")

        utility_tree:render("Utility", function()
            menu.use_demo_shout:render("Demo Shout", "Maintain Demoralizing Shout")
            menu.use_thunder_clap:render("Thunder Clap", "Use Thunder Clap for AoE threat")
            menu.use_sunder_armor:render("Sunder Armor", "Maintain Sunder Armor stacks")
            menu.sunder_max_stacks:render("Sunder Max Stacks", "Maximum Sunder Armor stacks")
            menu.use_rend:render("Rend", "Apply Rend to target")
            menu.use_hamstring:render("Hamstring", "Low-priority filler used only in solo mode")
            menu.use_intercept:render("Intercept", "Solo-only in-combat gap closer that temporarily swaps to Berserker Stance, Intercepts, then returns home")
            menu.intercept_min_range:render("Intercept Min Range", "Minimum range for Intercept")
        end)

        tanking_tree:render("Tanking", function()
            menu.auto_peel:render("Auto Peel", "Scan for off-target threats in dungeon and raid modes without changing your HUD target")
            menu.use_taunt:render("Taunt", "Dungeon/Raid automatic threat recovery when the current or recovery target is not on you")
            menu.use_shield_bash:render("Shield Bash", "Primary automatic interrupt on current and recovery targets")
            menu.use_concussion_blow:render("Concussion Blow", "Stun dangerous casters when Shield Bash cannot be used")
            menu.use_mocking_blow:render("Mocking Blow", "Dungeon/Raid fallback threat recovery tool when Taunt is unavailable")
            menu.use_challenging_shout:render("Challenging Shout", "Group-mode only rare AoE recovery tool for multi-mob threat losses")
            menu.use_peel_intercept:render("Peel Intercept", "Dungeon-only opt-in peel Intercept for healer or DPS rescue targets")
        end)

        defensive_tree:render("Defensive", function()
            menu.use_shield_block:render("Shield Block", "Solo uses Shield Block as emergency or elite mitigation; dungeon and raid use it proactively under real tank pressure")
            menu.use_last_stand:render("Last Stand", "Use Last Stand at low HP")
            menu.last_stand_hp_pct:render("Last Stand HP %", "HP threshold for Last Stand")
            menu.use_shield_wall:render("Shield Wall", "Use Shield Wall at low HP")
            menu.shield_wall_hp_pct:render("Shield Wall HP %", "HP threshold for Shield Wall")
            menu.use_spell_reflection:render("Spell Reflection", "Reflect incoming spell casts")
            menu.spell_reflection_progress_pct:render("Spell Reflection Cast %", "Wait until enemy cast is this % complete before reflecting (avoids wasting on cancelled casts)")
            menu.use_healthstone:render("Healthstone", "Use Healthstone at low HP")
            menu.healthstone_hp_pct:render("Healthstone HP %", "HP threshold for Healthstone")
            menu.use_health_potion:render("Health Potion", "Use a healing potion at low HP")
            menu.health_potion_hp_pct:render("Health Potion HP %", "HP threshold for Health Potion")
            menu.use_ironshield_potion:render("Ironshield Potion", "Solo uses Ironshield Potion only under heavy pressure or elite windows; dungeon and raid use it under tank pressure")
            menu.use_stoneform:render("Stoneform", "Use Stoneform in combat at low HP")
            menu.stoneform_hp_pct:render("Stoneform HP %", "HP threshold for Stoneform")
        end)

        burst_tree:render("Burst", function()
            menu.use_death_wish:render("Death Wish", "Use Death Wish during burst; suppressed automatically in dungeon and raid modes")
            menu.use_recklessness:render("Recklessness", "Use Recklessness during burst; suppressed automatically in dungeon and raid modes")
            menu.use_blood_fury:render("Blood Fury", "Use Blood Fury during safe burst windows")
            menu.use_berserking:render("Berserking", "Use Troll Berserking during safe burst windows")
            menu.use_trinkets:render("Trinkets", "Use ready self-cast trinkets during safe burst windows")
            menu.use_war_stomp_interrupt:render("War Stomp Interrupt", "Use War Stomp as interrupt")
            menu.intimidating_shout_key:render("Intimidating Shout Key", "Manual panic key")
            menu.use_disarm:render("Disarm", "Solo: disarm melee enemies for strong mitigation")
            menu.use_berserker_rage:render("Berserker Rage", "Use Berserker Rage to break fears and generate extra rage on crits")
            menu.use_retaliation:render("Retaliation", "Solo burst: Battle Stance cooldown that reflects melee attacks")
        end)

        menu.heroic_strike_rage:render("HS Min Rage", "Minimum rage to queue Heroic Strike")
        menu.cleave_rage:render("Cleave Min Rage", "Minimum rage to queue Cleave")
        menu.heroic_strike_rage_cap:render("HS Rage Cap Dump", "Force-queue Heroic Strike when rage exceeds this value regardless of swing window")
        menu.aoe_enemy_count:render("AoE Threshold", "Number of enemies for AoE mode")
        menu.execute_min_rage:render("Execute Min Rage", "Minimum rage to use Execute (rage above cost is consumed for bonus damage)")
        
        menu.combat_self_hp_boost = core.menu.slider_int(0, 30, 10, "simpleprot_combat_self_hp_boost")
        menu.focus_priority = core.menu.checkbox(false, "simpleprot_focus_priority")
        
        menu.combat_self_hp_boost:render("Combat Self HP Boost %", "Additional self-heal threshold when in combat")
        menu.focus_priority:render("Focus Target Priority", "Prioritize targeting your focus target")
    end)
end

return menu
