-- shaman/class_sylvanas.lua — Shaman class spells, constants, and shared helpers.
-- WHAT:  spell ID tables, stance/form mappings, and class-specific utilities.
-- WHEN:  loaded by all shaman specs; consumed via NS.ShamanSpells.
-- WHY:   single source of truth for shaman spell IDs and class constants.
-- SAFETY: nil-guarded lookups; no runtime allocations.

-- Shaman spell table, playstyle config, and child module loader.

local NS = _G.EaxRotations
if not NS then return nil end
local cl = require("shared/class_loader_sylvanas")
local load_child = cl.create_loader("shaman", "Shaman")
local load_spec = cl.create_expansion_loader("shaman", "Shaman")
local enums = cl.get_enums()
local player = NS.GetPlayer and NS.GetPlayer()
local ok_cls, cls_id = pcall(function() return player and player:get_class() end)
if not ok_cls or cls_id ~= enums.class_id.SHAMAN then return nil end

local SPELLS = {
    Bloodlust = NS.spell_action({
        name = "Bloodlust",
        ids = {2825},
        levels = {70},
        cast_time = 0,
        cooldown = 600,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    ChainHeal = NS.spell_action({
        name = "ChainHeal",
        ids = {25423, 25422, 10623, 10622, 1064},
        levels = {68, 61, 54, 46, 40},
        cast_time = 2.5,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    ChainLightning = NS.spell_action({
        name = "ChainLightning",
        ids = {25442, 25439, 10605, 2860, 930, 421},
        levels = {70, 63, 56, 48, 40, 32},
        cast_time = 2.5,
        cooldown = 6,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    EarthbindTotem = NS.spell_action({
        name = "EarthbindTotem",
        ids = {2484},
        levels = {6},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    EarthShield = NS.spell_action({
        name = "EarthShield",
        ids = {32594, 32593, 974},
        levels = {70, 60, 50},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    EarthShock = NS.spell_action({
        name = "EarthShock",
        ids = {25454, 10414, 10413, 10412, 8046, 8045, 8044, 8042},
        levels = {69, 60, 48, 36, 24, 14, 8, 4},
        cast_time = 0,
        cooldown = 6,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    ElementalMastery = NS.spell_action({
        name = "ElementalMastery",
        ids = {16166},
        levels = {50},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "none",
        school = "nature",
    }),
    FireNovaTotem = NS.spell_action({
        name = "FireNovaTotem",
        ids = {25547, 25546, 11315, 11314, 8499, 8498, 1535},
        levels = {70, 61, 52, 42, 32, 22, 12},
        cast_time = 0,
        cooldown = 3,
        power_cost = 0,
        power_type = "mana",
        school = "fire",
    }),
    FlametongueWeapon = NS.spell_action({
        name = "FlametongueWeapon",
        ids = {25489, 16342, 16341, 16339, 8030, 8027, 8024},
        levels = {64, 56, 46, 36, 26, 18, 10},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "fire",
    }),
    FlameShock = NS.spell_action({
        name = "FlameShock",
        ids = {25457, 29228, 10448, 10447, 8053, 8052, 8050},
        levels = {70, 60, 52, 40, 28, 18, 10},
        cast_time = 0,
        cooldown = 6,
        power_cost = 0,
        power_type = "mana",
        school = "fire",
    }),
    FrostShock = NS.spell_action({
        name = "FrostShock",
        ids = {25464, 10473, 10472, 8058, 8056},
        levels = {68, 58, 46, 34, 20},
        cast_time = 0,
        cooldown = 6,
        power_cost = 0,
        power_type = "mana",
        school = "frost",
    }),
    FrostbrandWeapon = NS.spell_action({
        name = "FrostbrandWeapon",
        ids = {25500, 16356, 16355, 10456, 8038, 8033},
        levels = {66, 58, 48, 38, 28, 20},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "frost",
    }),
    GhostWolf = NS.spell_action({
        name = "GhostWolf",
        ids = {2645},
        levels = {20},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    GiftOfTheNaaru = NS.spell_action({
        name = "GiftOfTheNaaru",
        ids = {28880},
        levels = {1},
        cast_time = 0,
        cooldown = 120,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    TotemicCall = NS.spell_action({
        name = "TotemicCall",
        ids = {36936},
        levels = {30},
        cast_time = 0,
        cooldown = 120,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    GraceOfAirTotem = NS.spell_action({
        name = "GraceOfAirTotem",
        ids = {25359, 10627, 8835},
        levels = {60, 56, 42},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    GroundingTotem = NS.spell_action({
        name = "GroundingTotem",
        ids = {8177},
        levels = {30},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    HealingWave = NS.spell_action({
        name = "HealingWave",
        ids = {25396, 25391, 25357, 10396, 10395, 8005, 959, 939, 913, 547, 332, 331},
        levels = {70, 63, 60, 56, 48, 40, 32, 24, 18, 12, 6, 1},
        cast_time = 3.0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    HealingStreamTotem = NS.spell_action({
        name = "HealingStreamTotem",
        ids = {25567, 10463, 10462, 6377, 6375, 5394},
        levels = {69, 60, 50, 40, 30, 20},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    LesserHealingWave = NS.spell_action({
        name = "LesserHealingWave",
        ids = {25420, 10468, 10467, 10466, 8010, 8008, 8004},
        levels = {66, 60, 52, 44, 36, 28, 20},
        cast_time = 1.5,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    LightningBolt = NS.spell_action({
        name = "LightningBolt",
        ids = {25449, 25448, 15208, 15207, 10392, 10391, 6041, 943, 915, 548, 529, 403},
        levels = {67, 62, 56, 50, 44, 38, 32, 26, 20, 14, 8, 1},
        cast_time = 3.0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    LightningShield = NS.spell_action({
        name = "LightningShield",
        ids = {25472, 25469, 10432, 10431, 8134, 945, 905, 325, 324},
        levels = {70, 63, 56, 48, 40, 32, 24, 16, 8},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    ManaSpringTotem = NS.spell_action({
        name = "ManaSpringTotem",
        ids = {25570, 10497, 10496, 10495, 5675},
        levels = {65, 56, 46, 36, 26},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    ManaTideTotem = NS.spell_action({
        name = "ManaTideTotem",
        ids = {16190},
        levels = {40},
        cast_time = 0,
        cooldown = 300,
        power_cost = 0,
        power_type = "none",
        school = "nature",
    }),
    NaturesSwiftness = NS.spell_action({
        name = "NaturesSwiftness",
        ids = {16188},
        levels = {40},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "none",
        school = "nature",
    }),
    Purge = NS.spell_action({
        name = "Purge",
        ids = {8012, 370},
        levels = {32, 12},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    RockbiterWeapon = NS.spell_action({
        name = "RockbiterWeapon",
        ids = {25485, 25479, 16316, 16315, 16314, 10399, 8019, 8018, 8017},
        levels = {70, 62, 54, 44, 34, 24, 16, 8, 1},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    SearingTotem = NS.spell_action({
        name = "SearingTotem",
        ids = {25533, 10438, 10437, 6365, 6364, 6363, 3599},
        levels = {69, 60, 50, 40, 30, 20, 10},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "fire",
    }),
    ShamanisticRage = NS.spell_action({
        name = "ShamanisticRage",
        ids = {30823},
        levels = {50},
        cast_time = 0,
        cooldown = 120,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Stormstrike = NS.spell_action({
        name = "Stormstrike",
        ids = {17364},
        levels = {40},
        cast_time = 0,
        cooldown = 10,
        power_cost = 0,
        power_type = "mana",
        school = "physical",
    }),
    StoneclawTotem = NS.spell_action({
        name = "StoneclawTotem",
        ids = {25525, 10428, 10427, 6392, 6391, 6390, 5730},
        levels = {67, 58, 48, 38, 28, 18, 8},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    StoneskinTotem = NS.spell_action({
        name = "StoneskinTotem",
        ids = {25509, 25508, 10408, 10407, 10406, 8155, 8154, 8071},
        levels = {70, 63, 54, 44, 34, 24, 14, 4},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    StrengthOfEarthTotem = NS.spell_action({
        name = "StrengthOfEarthTotem",
        ids = {25528, 25361, 10442, 8161, 8160, 8075},
        levels = {65, 60, 52, 38, 24, 10},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    TremorTotem = NS.spell_action({
        name = "TremorTotem",
        ids = {8143},
        levels = {18},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    WaterShield = NS.spell_action({
        name = "WaterShield",
        ids = {33736, 24398, 23575},
        levels = {69, 62, 50},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "nature",
    }),
    WindfuryWeapon = NS.spell_action({
        name = "WindfuryWeapon",            ids = {25505, 16362, 10486, 8235, 8232},
        levels = {68, 60, 50, 40, 30},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    WindfuryTotem = NS.spell_action({
        name = "WindfuryTotem",
        ids = {25587, 25585, 10614, 10613, 8512},
        levels = {70, 61, 52, 42, 32},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "physical",
    }),
    TotemOfWrath = NS.spell_action({
        name = "TotemOfWrath",
        ids = {30706},
        levels = {50},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "fire",
    }),
    WrathOfAirTotem = NS.spell_action({
        name = "WrathOfAirTotem",
        ids = {3738},
        levels = {64},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    LightningBoltLowerRank = NS.spell_action({
        name = "LightningBoltLowerRank",
        ids = {25448},
        levels = {62},
        cast_time = 3.0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    CurePoison = NS.spell_action({
        name = "CurePoison",
        ids = {526},
        levels = {16},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    CureDisease = NS.spell_action({
        name = "CureDisease",
        ids = {2870},
        levels = {22},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    PoisonCleansingTotem = NS.spell_action({
        name = "PoisonCleansingTotem",
        ids = {8166},
        levels = {22},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    DiseaseCleansingTotem = NS.spell_action({
        name = "DiseaseCleansingTotem",
        ids = {8170},
        levels = {38},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    MagmaTotem = NS.spell_action({
        name = "MagmaTotem",
        ids = {25552, 10587, 10586, 10585, 8190},
        levels = {65, 56, 46, 36, 26},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "fire",
    }),
    UnavailableClassicShamanBurst = nil,
    UnavailableClassicShamanResource = nil,
    UnavailableClassicShamanShieldA = nil,
    UnavailableClassicShamanShieldB = nil,
    UnavailableClassicShamanTotem = nil,
}

NS.ShamanSpells = SPELLS

local is_sod = type(NS.is_sod) == "function" and NS.is_sod() or false
local config = {
    class_key = "shaman",
    class_name = "Shaman",
    default_playstyle = "elemental",
    playstyles = {
        { name = "leveling", display_name = "Leveling" },
        { name = "elemental", display_name = "Elemental" },
        { name = "enhancement", display_name = "Enhancement" },
        { name = "restoration", display_name = "Restoration" },
    },
}
if is_sod then config.playstyles = cl.sod_playstyles("shaman") end
NS.rotation_registry:set_class_config(config)
if is_sod then
    cl.load_sod_specs("shaman", "Shaman")
    return config
end

load_child("middleware_sylvanas")
load_child("healing_sylvanas")
load_spec("leveling", true)
load_spec("elemental")
load_spec("enhancement")
load_spec("restoration")
-- class module initialized
-- Dump known spells for debugging; run once at load.
if NS.dump_class_spells then NS.dump_class_spells("Shaman") end
return config
