-- Paladin spell table, playstyle config, and child module loader.

-- ============================================================================
-- What: Paladin spell table, playstyle config, and child module loader.
-- When: Load time.
-- Why: Centralize class registration and child module wiring.
-- Safety: Class check returns cleanly; NS.* helpers only; graceful degradation.
-- ============================================================================

local NS = _G.EaxRotations
if not NS then return nil end
local cl = require("shared/class_loader_sylvanas")
local load_child = cl.create_loader("paladin", "Paladin")
local enums = cl.get_enums()
local player = NS.GetPlayer()
if not player or player:get_class() ~= enums.class_id.PALADIN then return nil end

local SPELLS = {
    AvengerShield = NS.spell_action({
        name = "AvengerShield",
        ids = {32700, 32699, 31935},
        levels = {70, 60, 50},
        cast_time = 0,
        cooldown = 30,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    AvengingWrath = NS.spell_action({
        name = "AvengingWrath",
        ids = {31884},
        levels = {60},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    BlessingOfSanctuary = NS.spell_action({
        name = "BlessingOfSanctuary",
        ids = {27168, 20914, 20913, 20912, 20911},
        levels = {70, 60, 50, 40, 30},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    GreaterBlessingOfSanctuary = NS.spell_action({
        name = "GreaterBlessingOfSanctuary",
        ids = {27169, 25899},
        levels = {70, 60},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    BlessingOfFreedom = NS.spell_action({
        name = "BlessingOfFreedom",
        ids = {1044},
        levels = {34},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    BlessingOfKings = NS.spell_action({
        name = "BlessingOfKings",
        ids = {20217},
        levels = {30},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    BlessingOfLight = NS.spell_action({
        name = "BlessingOfLight",
        ids = {27144, 19979, 19978, 19977},
        levels = {69, 60, 50, 40},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    BlessingOfMight = NS.spell_action({
        name = "BlessingOfMight",
        ids = {27140, 25291, 19838, 19837, 19836, 19835, 19834, 19740},
        levels = {70, 60, 52, 42, 32, 22, 12, 4},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    BlessingOfProtection = NS.spell_action({
        name = "BlessingOfProtection",
        ids = {10278, 5599, 1022},
        levels = {38, 24, 10},
        cast_time = 0,
        cooldown = 300,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    BlessingOfSacrifice = NS.spell_action({
        name = "BlessingOfSacrifice",
        ids = {27148, 27147, 20729, 6940},
        levels = {70, 62, 54, 46},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    BlessingOfWisdom = NS.spell_action({
        name = "BlessingOfWisdom",
        ids = {27142, 25290, 19854, 19853, 19852, 19850, 19742},
        levels = {65, 60, 54, 44, 34, 24, 14},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    GreaterBlessingOfKings = NS.spell_action({
        name = "GreaterBlessingOfKings",
        ids = {25898},
        levels = {62},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    GreaterBlessingOfLight = NS.spell_action({
        name = "GreaterBlessingOfLight",
        ids = {27145, 25890},
        levels = {69, 60},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    GreaterBlessingOfWisdom = NS.spell_action({
        name = "GreaterBlessingOfWisdom",
        ids = {27143, 25918, 25894},
        levels = {65, 60, 54},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    Cleanse = NS.spell_action({
        name = "Cleanse",
        ids = {4987},
        levels = {42},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    ConcentrationAura = NS.spell_action({
        name = "ConcentrationAura",
        ids = {19746},
        levels = {22},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    Consecration = NS.spell_action({
        name = "Consecration",
        ids = {27173, 20924, 20923, 20922, 20116, 26573},
        levels = {70, 60, 50, 40, 30, 20},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    CrusaderStrike = NS.spell_action({
        name = "CrusaderStrike",
        ids = {35395},
        levels = {60},
        cast_time = 0,
        cooldown = 6,
        power_cost = 0,
        power_type = "mana",
        school = "physical",
    }),
    DevotionAura = NS.spell_action({
        name = "DevotionAura",
        ids = {27149, 10293, 10292, 1032, 10291, 643, 10290, 465},
        levels = {70, 60, 50, 40, 30, 20, 10, 1},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    DivineProtection = NS.spell_action({
        name = "DivineProtection",
        ids = {5573, 498},
        levels = {18, 6},
        cast_time = 0,
        cooldown = 300,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    DivineFavor = NS.spell_action({
        name = "DivineFavor",
        ids = {20216},
        levels = {50},
        cast_time = 0,
        cooldown = 120,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    DivineIllumination = NS.spell_action({
        name = "DivineIllumination",
        ids = {31842},
        levels = {60},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    DivineShield = NS.spell_action({
        name = "DivineShield",
        ids = {1020, 642},
        levels = {50, 34},
        cast_time = 0,
        cooldown = 300,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    Exorcism = NS.spell_action({
        name = "Exorcism",
        ids = {27138, 10314, 10313, 10312, 5615, 5614, 879},
        levels = {68, 60, 52, 44, 36, 28, 20},
        cast_time = 1.5,
        cooldown = 15,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    FireResistanceAura = NS.spell_action({
        name = "FireResistanceAura",
        ids = {27153, 19900, 19899, 19891},
        levels = {70, 60, 48, 36},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    FlashOfLight = NS.spell_action({
        name = "FlashOfLight",
        ids = {27137, 19943, 19942, 19941, 19940, 19939, 19750},
        levels = {66, 58, 50, 42, 34, 26, 20},
        cast_time = 1.5,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    FrostResistanceAura = NS.spell_action({
        name = "FrostResistanceAura",
        ids = {27152, 19898, 19897, 19888},
        levels = {68, 56, 44, 32},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    HammerOfJustice = NS.spell_action({
        name = "HammerOfJustice",
        ids = {10308, 5589, 5588, 853},
        levels = {54, 40, 24, 8},
        cast_time = 0,
        cooldown = 60,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    HammerOfWrath = NS.spell_action({
        name = "HammerOfWrath",
        ids = {27180, 24239, 24274, 24275},
        levels = {68, 60, 52, 44},
        cast_time = 0,
        cooldown = 6,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    HolyLight = NS.spell_action({
        name = "HolyLight",
        ids = {27136, 27135, 25292, 10329, 10328, 3472, 1042, 1026, 647, 639, 635},
        levels = {70, 62, 60, 54, 46, 38, 30, 22, 14, 6, 1},
        cast_time = 2.5,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    HolyShield = NS.spell_action({
        name = "HolyShield",
        ids = {27179, 20928, 20927, 20925},
        levels = {70, 60, 50, 40},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    HolyShock = NS.spell_action({
        name = "HolyShock",
        ids = {33072, 27174, 20930, 20929, 20473},
        levels = {70, 64, 56, 48, 40},
        cast_time = 0,
        cooldown = 6,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    Judgement = NS.spell_action({
        name = "Judgement",
        ids = {20271},
        levels = {4},
        cast_time = 0,
        cooldown = 10,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    LayOnHands = NS.spell_action({
        name = "LayOnHands",
        ids = {27154, 10310, 2800, 633},
        levels = {69, 50, 30, 10},
        cast_time = 0,
        cooldown = 3600,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    Repentance = NS.spell_action({
        name = "Repentance",
        ids = {20066, 5164},
        levels = {56},
        cast_time = 0,
        cooldown = 60,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    RighteousFury = NS.spell_action({
        name = "RighteousFury",
        ids = {25780},
        levels = {16},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    Purify = NS.spell_action({
        name = "Purify",
        ids = {1152},
        levels = {8},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    SanctityAura = NS.spell_action({
        name = "SanctityAura",
        ids = {20218, 32223},
        levels = {50},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    SealBlood = NS.spell_action({ 31892 }, "SealBlood"),
    SealOfTheMartyr = NS.spell_action({ 348701, 348700 }, "SealOfTheMartyr"),
    SealCommand = NS.spell_action({ 27170, 20920, 20919, 20918, 20915, 20375 }, "SealCommand"),
    SealCommandRank1 = NS.spell_action({ 20375 }, "SealCommandRank1"),
    SealCrusader = NS.spell_action({ 27158, 20308, 20307, 20306, 20305, 21082, 20162 }, "SealCrusader"),
    SealOfJustice = NS.spell_action({
        name = "SealOfJustice",
        ids = {31895, 20164},
        levels = {48, 22},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    HolyWrath = NS.spell_action({
        name = "HolyWrath",
        ids = {27139, 10318, 2812},
        levels = {69, 60, 50},
        cast_time = 2.0,
        cooldown = 60,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    SealOfWisdom = NS.spell_action({
        name = "SealOfWisdom",
        ids = {27166, 20357, 20356, 20166},
        levels = {67, 58, 48, 38},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "holy",
    }),
    SealWisdom = NS.spell_action({ 27166, 20357, 20356, 20166 }, "SealWisdom"),
    SealRighteousness = NS.spell_action({ 27155, 20293, 20292, 20291, 20290, 20289, 20288, 20287, 21084, 20154 }, "SealRighteousness"),
    ShadowResistanceAura = NS.spell_action({
        name = "ShadowResistanceAura",
        ids = {27151, 19896, 19895, 19876},
        levels = {63, 52, 40, 28},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    RetributionAura = NS.spell_action({
        name = "RetributionAura",
        ids = {27150, 10301, 10300, 10299, 10298, 7294},
        levels = {66, 56, 46, 36, 26, 16},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
    RighteousDefense = NS.spell_action({
        name = "RighteousDefense",
        ids = {31789},
        levels = {14},
        cast_time = 0,
        cooldown = 10,
        power_cost = 0,
        power_type = "none",
        school = "holy",
    }),
}
NS.PaladinSpells = SPELLS

NS.HOLY_LIGHT_RANKS = { { spell = SPELLS.HolyLight, label = "R11", base_min = 2196, base_max = 2446 } }
NS.FLASH_OF_LIGHT_RANKS = { { spell = SPELLS.FlashOfLight, label = "R7", base_min = 448, base_max = 502 } }
NS.HL_COEFFICIENT, NS.FOL_COEFFICIENT, NS.HEALING_LIGHT_MULT = 0.714, 0.429, 1.12

local config = {
    class_key = "paladin",
    class_name = "Paladin",
    default_playstyle = "holy",
    playstyles = {
        { name = "leveling", display_name = "Leveling" },
        { name = "holy", display_name = "Holy" },
        { name = "protection", display_name = "Protection" },
        { name = "retribution", display_name = "Retribution" },
    },
}
NS.rotation_registry:set_class_config(config)

load_child("middleware_sylvanas")
load_child("heal_helper_sylvanas")
load_child("leveling_sylvanas")
load_child("holy_sylvanas")
load_child("protection_sylvanas")
load_child("retribution_sylvanas")
NS.log("Paladin class module loaded")
return config
