-- Druid spell table, playstyle config, and child module loader.


local NS = _G.EaxRotations
if not NS then return nil end
local cl = require("shared/class_loader_sylvanas")
local load_child = cl.create_loader("druid", "Druid")
local load_spec = cl.create_expansion_loader("druid", "Druid")
local enums = cl.get_enums()
local player = NS.GetPlayer()
local ok_cls, cls_id = pcall(function() return player and player:get_class() end)
if not ok_cls or cls_id ~= enums.class_id.DRUID then return nil end

local SPELLS = {
    Barkskin = NS.spell_action({
        name = "Barkskin",
        ids = {22812},
        levels = {44},
        cast_time = 0,
        cooldown = 60,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Bash = NS.spell_action({
        name = "Bash",
        ids = {8983, 6798, 5211},
        levels = {46, 30, 14},
        cast_time = 0,
        cooldown = 60,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    BearForm = NS.spell_action({
        name = "BearForm",
        ids = {9634, 5487},
        levels = {40, 10},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    CatForm = NS.spell_action({
        name = "CatForm",
        ids = {768},
        levels = {20},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    ChallengingRoar = NS.spell_action({
        name = "ChallengingRoar",
        ids = {5209},
        levels = {28},
        cast_time = 0,
        cooldown = 600,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Claw = NS.spell_action({
        name = "Claw",
        ids = {27000, 9850, 9849, 5201, 3029, 1082},
        levels = {67, 58, 48, 38, 28, 20},
        cast_time = 0,
        cooldown = 0,
        power_cost = 40,
        power_type = "energy",
        school = "physical",
    }),
    Cower = NS.spell_action({
        name = "Cower",
        ids = {27004, 9892, 8998},
        levels = {69, 60, 28},
        cast_time = 0,
        cooldown = 0,
        power_cost = 20,
        power_type = "energy",
        school = "physical",
    }),
    Dash = NS.spell_action({
        name = "Dash",
        ids = {33357, 9821, 1850},
        levels = {65, 46, 26},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    DemoralizingRoar = NS.spell_action({
        name = "DemoralizingRoar",
        ids = {26998, 9898, 9747, 9490, 1735, 99},
        levels = {62, 52, 42, 32, 20, 10},
        cast_time = 0,
        cooldown = 0,
        power_cost = 10,
        power_type = "rage",
        school = "physical",
    }),
    FaerieFire = NS.spell_action({
        name = "FaerieFire",
        ids = {26993, 9907, 9749, 778, 770},
        levels = {66, 54, 42, 30, 18},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    FaerieFireFeral = NS.spell_action({
        name = "FaerieFireFeral",
        ids = {27011, 17392, 17391, 17390, 16857},
        levels = {66, 54, 42, 30, 25},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    FeralCharge = NS.spell_action({
        name = "FeralCharge",
        ids = {16979},
        levels = {20},
        cast_time = 0,
        cooldown = 15,
        power_cost = 10,
        power_type = "rage",
        school = "physical",
    }),
    FerociousBite = NS.spell_action({
        name = "FerociousBite",
        ids = {24248, 31018, 22829, 22828, 22827, 22568},
        levels = {63, 60, 56, 48, 40, 32},
        cast_time = 0,
        cooldown = 0,
        power_cost = 35,
        power_type = "energy",
        school = "physical",
    }),
    ForceOfNature = NS.spell_action({
        name = "ForceOfNature",
        ids = {33831},
        levels = {70},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    FrenziedRegeneration = NS.spell_action({
        name = "FrenziedRegeneration",
        ids = {26999, 22896, 22895, 22842},
        levels = {65, 56, 46, 36},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "rage",
        school = "physical",
    }),
    SurvivalInstincts = NS.spell_action({
        name = "SurvivalInstincts",
        ids = {61336},
        levels = {0},
        cast_time = 0,
        cooldown = 300,
        power_cost = 0,
        school = "physical",
    }),
    Growl = NS.spell_action({
        name = "Growl",
        ids = {6795},
        levels = {10},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    GiftOfTheWild = NS.spell_action({
        name = "GiftOfTheWild",
        ids = {26991, 21850, 21849},
        levels = {70, 60, 50},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    HealingTouch = NS.spell_action({
        name = "HealingTouch",
        ids = {26979, 26978, 25297, 9889, 9888, 9758, 8903, 6778, 5189, 5188, 5187, 5186, 5185},
        levels = {69, 62, 60, 56, 50, 44, 38, 32, 26, 20, 14, 8, 1},
        cast_time = 3.5,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    HealingTouchRank4 = NS.spell_action({
        name = "HealingTouchRank4",
        ids = {5189},
        levels = {26},
        cast_time = 3.5,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    Hurricane = NS.spell_action({
        name = "Hurricane",
        ids = {27012, 17402, 17401, 16914},
        levels = {70, 60, 50, 40},
        cast_time = 0,
        cooldown = 60,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    Innervate = NS.spell_action({
        name = "Innervate",
        ids = {29166},
        levels = {40},
        cast_time = 0,
        cooldown = 360,
        power_cost = 0,
        power_type = "none",
        school = "nature",
    }),
    InsectSwarm = NS.spell_action({
        name = "InsectSwarm",
        ids = {27013, 24977, 24976, 24975, 24974, 5570},
        levels = {67, 58, 48, 38, 28, 20},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    Lacerate = NS.spell_action({
        name = "Lacerate",
        ids = {33745},
        levels = {70, 66},
        cast_time = 0,
        cooldown = 0,
        power_cost = 15,
        power_type = "rage",
        school = "physical",
    }),
    Lifebloom = NS.spell_action({
        name = "Lifebloom",
        ids = {33763},
        levels = {64},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    MangleBear = NS.spell_action({
        name = "MangleBear",
        ids = {33987, 33986, 33878},
        levels = {68, 58, 50},
        cast_time = 0,
        cooldown = 6,
        power_cost = 15,
        power_type = "rage",
        school = "physical",
    }),
    MangleCat = NS.spell_action({
        name = "MangleCat",
        ids = {33983, 33982, 33876},
        levels = {68, 58, 50},
        cast_time = 0,
        cooldown = 6,
        power_cost = 45,
        power_type = "energy",
        school = "physical",
    }),
    Maul = NS.spell_action({
        name = "Maul",
        ids = {26996, 9881, 9880, 9745, 8972, 6809, 6808, 6807},
        levels = {67, 58, 50, 42, 34, 26, 18, 10},
        cast_time = 0,
        cooldown = 0,
        power_cost = 15,
        power_type = "rage",
        school = "physical",
    }),
    Moonfire = NS.spell_action({
        name = "Moonfire",
        ids = {26988, 26987, 9835, 9834, 9833, 8929, 8928, 8927, 8926, 8925, 8924, 8921},
        levels = {70, 63, 58, 52, 46, 40, 34, 28, 22, 16, 10, 4},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "arcane",
    }),
    MoonkinForm = NS.spell_action({
        name = "MoonkinForm",
        ids = {24858},
        levels = {40},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    MarkOfTheWild = NS.spell_action({
        name = "MarkOfTheWild",
        ids = {26990, 9885, 9884, 8907, 5234, 6756, 5232, 1126},
        levels = {60, 50, 40, 30, 20, 10, 4},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    Maim = NS.spell_action({
        name = "Maim",
        ids = {22570},
        levels = {62},
        cast_time = 0,
        cooldown = 0,
        power_cost = 30,
        power_type = "energy",
        school = "physical",
    }),
    NaturesSwiftness = NS.spell_action({
        name = "NaturesSwiftness",
        ids = {17116},
        levels = {30},
        cast_time = 0,
        cooldown = 180,
        power_cost = 0,
        power_type = "none",
        school = "nature",
    }),
    NaturesGrasp = NS.spell_action({
        name = "NaturesGrasp",
        ids = {27009, 17329, 16813, 16812, 16811, 16810, 16689},
        levels = {60, 50, 40, 30, 18, 10},
        cast_time = 0,
        cooldown = 60,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    Pounce = NS.spell_action({
        name = "Pounce",
        ids = {27006, 9827, 9823, 9005},
        levels = {66, 56, 46, 36},
        cast_time = 0,
        cooldown = 0,
        power_cost = 50,
        power_type = "energy",
        school = "physical",
    }),
    Prowl = NS.spell_action({
        name = "Prowl",
        ids = {9913, 6783, 5215},
        levels = {60, 40, 20},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Rake = NS.spell_action({
        name = "Rake",
        ids = {27003, 9904, 1824, 1823, 1822},
        levels = {64, 54, 44, 34, 24},
        cast_time = 0,
        cooldown = 0,
        power_cost = 40,
        power_type = "energy",
        school = "physical",
    }),
    Ravage = NS.spell_action({
        name = "Ravage",
        ids = {27005, 9867, 9866, 6787, 6785},
        levels = {66, 58, 50, 42, 32},
        cast_time = 0,
        cooldown = 0,
        power_cost = 60,
        power_type = "energy",
        school = "physical",
    }),
    Regrowth = NS.spell_action({
        name = "Regrowth",
        ids = {26980, 9858, 9857, 9856, 9750, 8941, 8940, 8939, 8938, 8936},
        levels = {65, 60, 54, 48, 42, 36, 30, 24, 18, 12},
        cast_time = 2.0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    Rejuvenation = NS.spell_action({
        name = "Rejuvenation",
        ids = {26982, 26981, 25299, 9841, 9840, 9839, 8910, 3627, 2091, 2090, 1430, 1058, 774},
        levels = {69, 63, 60, 58, 52, 46, 40, 34, 28, 22, 16, 10, 4},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    Rip = NS.spell_action({
        name = "Rip",
        ids = {27008, 9896, 9894, 9752, 9493, 9492, 1079},
        levels = {67, 60, 52, 44, 36, 28, 20},
        cast_time = 0,
        cooldown = 0,
        power_cost = 30,
        power_type = "energy",
        school = "physical",
    }),
    Shred = NS.spell_action({
        name = "Shred",
        ids = {27002, 27001, 9830, 9829, 8992, 6800, 5221},
        levels = {70, 61, 54, 46, 38, 30, 22},
        cast_time = 0,
        cooldown = 0,
        power_cost = 50,
        power_type = "energy",
        school = "physical",
    }),
    Starfire = NS.spell_action({
        name = "Starfire",
        ids = {26986, 25298, 9876, 9875, 8951, 8950, 8949, 2912},
        levels = {70, 60, 50, 40, 30, 20, 10},
        cast_time = 3.5,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "arcane",
    }),
    Swiftmend = NS.spell_action({
        name = "Swiftmend",
        ids = {18562},
        levels = {60},
        cast_time = 0,
        cooldown = 15,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    SwipeBear = NS.spell_action({
        name = "SwipeBear",
        ids = {26997, 9908, 9754, 769, 780, 779},
        levels = {64, 54, 44, 34, 24, 16},
        cast_time = 0,
        cooldown = 0,
        power_cost = 15,
        power_type = "rage",
        school = "physical",
    }),
    Thorns = NS.spell_action({
        name = "Thorns",
        ids = {26992, 9910, 9756, 8914, 1075, 782, 467},
        levels = {60, 50, 40, 30},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    TigersFury = NS.spell_action({
        name = "TigersFury",
        ids = {9846, 9845, 6793, 5217},
        levels = {60, 48, 36, 24},
        cast_time = 0,
        cooldown = 30,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    TrackHumanoids = NS.spell_action({
        name = "TrackHumanoids",
        ids = {5225},
        levels = {32},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Tranquility = NS.spell_action({
        name = "Tranquility",
        ids = {26983, 9863, 9862, 8918, 740},
        levels = {70, 60, 50, 40, 30},
        cast_time = 0,
        cooldown = 600,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    TravelForm = NS.spell_action({
        name = "TravelForm",
        ids = {783},
        levels = {30},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    TreeOfLifeForm = NS.spell_action({
        name = "TreeOfLifeForm",
        ids = {33891},
        levels = {60},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "none",
        school = "physical",
    }),
    Wrath = NS.spell_action({
        name = "Wrath",
        ids = {26985, 26984, 9912, 8905, 6780, 5180, 5179, 5178, 5177, 5176},
        levels = {70, 60, 50, 40, 30, 20, 10, 6, 1}, -- 10 ids, 9 levels (5177 and 5176 both at level 1)
        cast_time = 2.0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    Cyclone = NS.spell_action({
        name = "Cyclone",
        ids = {33786},
        levels = {62},
        cast_time = 1.5,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    EntanglingRoots = NS.spell_action({
        name = "EntanglingRoots",
        ids = {26989, 9853, 9852, 5196, 5195, 1062, 339},
        levels = {70, 60, 50, 40, 30, 20, 14},
        cast_time = 1.5,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    RemoveCurse = NS.spell_action({
        name = "RemoveCurse",
        ids = {2782},
        levels = {48},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    AbolishPoison = NS.spell_action({
        name = "AbolishPoison",
        ids = {2893},
        levels = {46},
        cast_time = 0,
        cooldown = 0,
        power_cost = 0,
        power_type = "mana",
        school = "nature",
    }),
    Enrage = NS.spell_action({
        name = "Enrage",
        ids = {5229},
        levels = {60, 50, 36},
        cast_time = 0,
        cooldown = 60,
        power_cost = 5,
        power_type = "rage",
        school = "physical",
    }),
}
NS.DruidSpells = SPELLS

local config = {
    class_key = "druid",
    class_name = "Druid",
    default_playstyle = "balance",
    playstyles = {
        { name = "leveling", display_name = "Leveling" },
        { name = "balance", display_name = "Balance" },
        { name = "bear", display_name = "Bear" },
        { name = "cat", display_name = "Cat" },
        { name = "caster", display_name = "Caster (Leveling/Solo)" },
        { name = "resto", display_name = "Resto" },
    },
}
NS.rotation_registry:set_class_config(config)

load_spec("leveling", true)
load_child("middleware_sylvanas")
load_spec("balance")
load_spec("bear")
load_spec("cat")
load_child("caster_sylvanas")
load_child("healing_sylvanas")
load_spec("resto")
NS.log("Druid class module loaded")
return config
