#!/usr/bin/env python3
"""Regenerate EaxRotations/shared/dagger_set_sylvanas.lua from the item sources.

WHY THIS EXISTS. The engine exposes no weapon-subclass accessor -- a game_object
gives get_item_id() and the enchant fields, nothing that says "this is a dagger"
-- so dagger eligibility has to be data-driven from the item id. Before this
generator the set was a hand-pasted cMaNGOS extract whose provenance was a
comment: nothing could re-derive it, and nothing knew which items were
PROVABLY not daggers (so a sword could never be ruled out).

SOURCES (union; each is optional so the generator still runs on a machine that
only has some of them, and the committed output is the reviewed artifact):
  1. cMaNGOS item_template.json (TBC 2.4.3): every class-2 (weapon) row, with
     its subclass. subclass 15 == dagger.
  2. The TBC client DBC item table (wowheadScrape/dbc_extract/wowsims.db), which
     carries era ids the 2.4.3 dump predates.
  3. The dagger id list already committed in the output file, so a regeneration
     on a machine with no local item data keeps the reviewed set instead of
     silently shrinking it.

OUTPUT SHAPE. M.DAGGER_IDS (positive dagger identification) plus
M.WEAPON_SUBCLASS (every known weapon id -> subclass). Together they give a
three-way classification: dagger / provably-not-a-dagger / unknown. The specs
fail OPEN on "unknown" -- blocking a dagger ability on data we do not have would
silently disable a spec's main builder for an item nobody has classified.

Usage:
  python EaxRotations/tools/generate_weapon_data.py          # regenerate (manual, commit the diff)
  python EaxRotations/tools/generate_weapon_data.py --check  # drift guard (compare only, no writes)
  python EaxRotations/tools/generate_weapon_data.py --self-test
"""
import json
import os
import re
import sqlite3
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
OUT = os.path.normpath(os.path.join(ROOT, "EaxRotations", "shared", "dagger_set_sylvanas.lua"))
LIVE_DB = os.path.normpath(os.path.join(ROOT, "wowheadScrape", "dbc_extract", "wowsims.db"))
MANGOS_CANDIDATES = (
    os.path.normpath(os.path.join(ROOT, "..", "scripts-backup-20250630", "wowhead_data", "extracted", "item_template.json")),
    os.path.normpath(os.path.join(ROOT, "wowhead_data", "extracted", "item_template.json")),
)

WEAPON_CLASS = 2
DAGGER_SUBCLASS = 15
PER_LINE = 16


DAGGER_HEADER = """-- dagger_set_sylvanas.lua -- weapon item classification for dagger-using classes (GENERATED).
-- WHAT:   item_id -> dagger classification + known weapon subclass map.
-- WHEN:   loaded at spec-class startup; pure constant data (no api at load).
-- WHY:    the engine has no weapon-subclass accessor, so dagger eligibility for
--         Backstab / Ambush / Mutilate must come from the item id. classify()
--         answers dagger / provably-not-a-dagger / unknown, and the specs fail
--         OPEN on unknown (blocking on data we lack would silently disable a
--         spec's main builder).
-- SAFETY: static ID tables; nil-tolerant key fetch; no per-frame work.
-- DECISION: pure data consumed via require(); no on_update side-effects.
-- GENERATED BY: EaxRotations/tools/generate_weapon_data.py -- do NOT hand-edit.
-- SOURCES: cMaNGOS item_template (TBC 2.4.3, class/subclass per item),
--          the local DBC item table, plus the previously committed set.
-- Regenerate:  python EaxRotations/tools/generate_weapon_data.py
-- Verify:      python EaxRotations/tools/generate_weapon_data.py --check
"""


def _committed_text():
    if not os.path.exists(OUT):
        return None
    with open(OUT, "r", encoding="utf-8", errors="replace") as fh:
        return fh.read()


def load_committed(previous):
    """Pull the dagger ids (and subclass map) out of the committed file."""
    if not previous:
        return set(), {}
    daggers = set()
    m = re.search(r"M\.DAGGER_IDS\s*=\s*\{(.*?)\n\}", previous, re.S)
    if m:
        daggers = set(int(x) for x in re.findall(r"\d+", m.group(1)))
    subclasses = {}
    m = re.search(r"M\.WEAPON_SUBCLASS\s*=\s*\{(.*?)\n\}", previous, re.S)
    if m:
        for k, v in re.findall(r"\[(\d+)\]\s*=\s*(\d+)", m.group(1)):
            subclasses[int(k)] = int(v)
    return daggers, subclasses


def from_mangos(rows):
    """cMaNGOS item_template rows -> (dagger ids, {weapon id: subclass})."""
    daggers, subclasses = set(), {}
    for entry, rec in rows.items():
        if rec.get("class") != WEAPON_CLASS:
            continue
        sub = rec.get("subclass")
        if not isinstance(sub, int):
            continue
        item_id = rec.get("entry", entry)
        if not isinstance(item_id, int) or item_id <= 0:
            continue
        subclasses[item_id] = sub
        if sub == DAGGER_SUBCLASS:
            daggers.add(item_id)
    return daggers, subclasses


def load_mangos():
    for path in MANGOS_CANDIDATES:
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8", errors="replace") as fh:
                return from_mangos(json.load(fh)), path
    return (set(), {}), None


def load_live_db():
    if not os.path.exists(LIVE_DB):
        return (set(), {}), None
    daggers, subclasses = set(), {}
    con = sqlite3.connect(LIVE_DB)
    try:
        for item_id, sub in con.execute(
            "select ID, SubclassID from Item where ClassID = ?", (WEAPON_CLASS,)
        ):
            if not isinstance(item_id, int) or item_id <= 0 or not isinstance(sub, int):
                continue
            subclasses[item_id] = sub
            if sub == DAGGER_SUBCLASS:
                daggers.add(item_id)
    except sqlite3.Error:
        return (set(), {}), None
    finally:
        con.close()
    return (daggers, subclasses), LIVE_DB


def build_sources():
    """Union every available source. Returns (daggers, subclasses, provenance)."""
    daggers, subclasses = set(), {}
    provenance = []
    previous = _committed_text()
    prev_daggers, prev_sub = load_committed(previous)
    (m_dag, m_sub), m_path = load_mangos()
    if m_path:
        daggers |= m_dag
        subclasses.update(m_sub)
        provenance.append("cMaNGOS %s" % os.path.basename(m_path))
    (d_dag, d_sub), d_path = load_live_db()
    if d_path:
        daggers |= d_dag
        subclasses.update(d_sub)
        provenance.append("dbc %s" % os.path.basename(d_path))
    daggers |= prev_daggers
    subclasses.update(prev_sub)
    if previous is not None:
        provenance.append("committed set")
    return daggers, subclasses, provenance


LUA_TAIL = """
M.is_dagger = {}
for _, id in ipairs(M.DAGGER_IDS) do
    M.is_dagger[id] = true
end

-- classify(item_id) -> "dagger" | "other" | "unknown"
--   "dagger"  the item is a dagger (class 2 / subclass 15)
--   "other"   the item is a known weapon that is provably NOT a dagger
--   "unknown" this data does not describe the item (fail open at the call site)
function M.classify(item_id)
    if type(item_id) ~= "number" or item_id <= 0 then return "unknown" end
    if M.is_dagger[item_id] then return "dagger" end
    local sub = M.WEAPON_SUBCLASS[item_id]
    if sub == nil then return "unknown" end
    if sub == M.DAGGER_SUBCLASS then return "dagger" end
    return "other"
end

-- True when the item can satisfy a dagger requirement. Fails OPEN: an item this
-- data does not describe is allowed, because a false negative would silently
-- disable Backstab / Ambush / Mutilate for a perfectly good dagger.
function M.allows_dagger_ability(item_id)
    return M.classify(item_id) ~= "other"
end

-- True only for a positively identified dagger.
function M.is_dagger_item(item_id)
    return M.classify(item_id) == "dagger"
end

return M
"""


def _ids_block(ids, per_line=PER_LINE):
    out = []
    row = []
    for i in ids:
        row.append(str(i))
        if len(row) == per_line:
            out.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        out.append("    " + ", ".join(row) + ",")
    return "\n".join(out)


def render(daggers, subclasses, provenance):
    dagger_ids = sorted(daggers)
    known = sorted(subclasses)
    parts = [DAGGER_HEADER]
    parts.append("-- SOURCE RUN: " + "; ".join(provenance) + "\n")
    parts.append("\nlocal M = {}\n")
    parts.append("\n-- Weapon item class and the dagger subclass (WoW item subclass 15).\n")
    parts.append("M.WEAPON_CLASS = %d\n" % WEAPON_CLASS)
    parts.append("M.DAGGER_SUBCLASS = %d\n" % DAGGER_SUBCLASS)
    parts.append("\n-- %d dagger item ids.\n" % len(dagger_ids))
    parts.append("M.DAGGER_IDS = {\n%s\n}\n" % _ids_block(dagger_ids))
    parts.append("\n-- %d known weapon item ids -> item subclass. An id in here that is\n" % len(known))
    parts.append("-- not in M.is_dagger is a weapon we can PROVE is not a dagger.\n")
    parts.append("M.WEAPON_SUBCLASS = {\n")
    row = []
    lines = []
    for item_id in known:
        row.append("[%d]=%d" % (item_id, subclasses[item_id]))
        if len(row) == PER_LINE:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    parts.append("\n".join(lines) + "\n}\n")
    parts.append(LUA_TAIL)
    return "".join(parts)


def _normalize(text):
    return text.replace("\r\n", "\n").replace("\r", "\n")


def regenerate(write=True):
    daggers, subclasses, provenance = build_sources()
    text = render(daggers, subclasses, provenance)
    if write:
        with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
    return text


def do_check():
    committed = _committed_text()
    if committed is None:
        print("weapon-data check: SKIP (no committed %s)" % os.path.basename(OUT))
        return 0
    fresh = regenerate(write=False)
    if _normalize(committed) != _normalize(fresh):
        print("weapon-data: DRIFT -- committed %s does not match a fresh regeneration." % os.path.basename(OUT))
        print("  Fix: python EaxRotations/tools/generate_weapon_data.py  then commit the diff.")
        return 1
    print("weapon-data: in sync (dagger_set_sylvanas.lua matches a fresh regeneration)")
    return 0


def do_self_test():
    """Prove the drift guard is non-vacuous without touching the real file."""
    committed = _committed_text()
    if committed is None:
        print("self-test: SKIP (no committed file)")
        return 1
    fresh = regenerate(write=False)
    ok = 1
    if _normalize(committed) != _normalize(fresh):
        print("self-test FAIL: committed file already drifted")
        return 1
    corrupted = committed.replace("[776] ", "[776] ")  # no-op guard
    corrupted = committed + "\n-- drift probe\n"
    if _normalize(corrupted) == _normalize(fresh):
        print("self-test FAIL: appended text did not register as drift")
        ok = 0
    # classifier semantics probe on a synthetic render
    probe = render({1234}, {1234: 15, 5678: 7}, ["self-test"])
    if 'M.DAGGER_SUBCLASS = 15' not in probe or "[5678]=7" not in probe:
        print("self-test FAIL: rendered probe missing expected fields")
        ok = 0
    if ok:
        print("self-test [PASS] marker present (drift detection + render fields fire)")
    return 0 if ok else 1


def main(argv):
    if "--check" in argv:
        return do_check()
    if "--self-test" in argv:
        return do_self_test()
    regenerate(write=True)
    print("wrote %s" % os.path.relpath(OUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
